### ISSUE TITLE
请问关于财报数据信息的历史完整性？

### ISSUE THREAD

**Issue by Wier123** [yutiansut/QUANTAXIS#1020]
# 问题反馈

请问QA的上市公司财务报表。例如EPS啊ROE啊等等。。是只和tdx一样。只保留近两三年的值么？？每次save只覆盖更新？还是也有保留更早的？  截图已发您QQ
如果没有。以后有考虑扩展该序列吗？
## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
QQ:87532775
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
不是2-3年 是从1996年开始的每一个季度报都存了
