### ISSUE TITLE
QAaccount中第1206行 is宜改为==

### ISSUE THREAD

**Issue by zsl3034669** [yutiansut/QUANTAXIS#1026]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```此处如果用is 会返回false结果不会往下运行，改为==就是true了


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by zsl3034669** [comment]
is的话 返回的是false  程序不会往下运行，改为==就会返回ture 了

**Comment by zsl3034669** [comment]
账户中税金和手续费是从可用资金直接减去的，是否在个股成本价也考虑相应的税金更符合实际。

**Comment by yutiansut** [comment]
@zsl3034669 https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAARP/QAAccount.py#L1206
没有看到is啊?

**Comment by zsl3034669** [comment]
@

**Comment by yutiansut** [comment]
啥情况

**Comment by zsl3034669** [comment]
@yutiansut  不好意思 我用的旧版。。。。更新了就没事了

**Comment by zsl3034669** [comment]
@yutiansut 点错了，。。。。点成关闭了。。。不过account的成本价 那里 是不是把买入该股票的税钱 也算进去 更符合实际一些

**Comment by zsl3034669** [comment]
第1199行
