### ISSUE TITLE
QAOrder 的疑问

### ISSUE THREAD

**Issue by nehcuh** [yutiansut/QUANTAXIS#1029]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

1.3.1.dev2

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```


MacOS 


```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```
QAOrder.py 中的 self.status 是不是写错了？
在 __init__ 中定义的是 self._status = _status
但是在 __repr__ , trade 等函数中又用了 self.status, 并没有定义啊

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
惰性计算的  看下@property  因为订单的状态会因为成交数量而改变 因此 每次调用的时候才计算当前订单的状态

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAMarket/QAOrder.py#L217
