### ISSUE TITLE
QAAccount.py 错误

### ISSUE THREAD

**Issue by nehcuh** [yutiansut/QUANTAXIS#1031]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

1.3.1.dev2

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```
`QAAccount.py` 第 1583 行，
```
        # 占用保证金
        self.margin = message['accounts']['marigin']
```
写错了
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@nehcuh 收到

**Comment by yutiansut** [comment]
fixed in https://github.com/QUANTAXIS/QUANTAXIS/pull/1037
