### ISSUE TITLE
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同

### ISSUE THREAD

**Issue by tonyyang1223** [yutiansut/QUANTAXIS#1074]
# 问题反馈
Window10 
Trying updating 002225 from 1990-01-01 to 2019-03-29
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题

## 您使用的QUANTAXIS版本号是什么?
1.3.3 
1.3.4 版本 无法运行
```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
Win10 64位




```

## 您的系统环境是什么?
```
- monodb 4.0
- python 3.7
- docker(无)
```
## 您需要反馈的问题
```
系统提示版本不同 但是可以save day
会偶尔打印如下信息
Trying updating 002225 from 1990-01-01 to 2019-03-29
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
 pytdx 重新安装还是无效 试了用pytdx 1.67 1.68 两个版本都一样
卸载
另外1.3.4
Win10系统上无法用save all 命令 会报错退出
安装采用的pip install quantaxis

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
QQ 71690588 email tonyyang1223@163.com
```

THANKS

**Comment by yutiansut** [comment]
@tonyyang1223 给一下报错的时候的信息或者截图 谢谢

**Comment by tonyyang1223** [comment]
您好 下面是我截取的屏幕内容 
版本信息 Quantaxis 1.3.3 pytdx 1.67 tushare 1.2.20
系统信息 Win10  MongoDB 4.07 Conda python 3.7

Trying updating 000528 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 122 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000529 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 123 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000530 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 124 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000531 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 125 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.46% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000532
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000532 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 126 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000533 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 127 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.52% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000534
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000534 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 128 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000536 from 1990-01-01 to 2019-03-29
c:\users\administrator\anaconda3\lib\site-packages\QUANTAXIS\QAFetch\QATdx.py:342: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  code), code, (int(lens / 800) - i) * 800, 800)) for i in range(int(lens / 800) + 1)], axis=0)
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
pip uninstall pytdx
pip install pytdx
'NoneType' object has no attribute 'columns'
QUANTAXIS>> The 129 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000537
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000537 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 130 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.60% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000538 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 131 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000539 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 132 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000540
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000540 from 1990-01-01 to 2019-03-29
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
pip uninstall pytdx
pip install pytdx
'NoneType' object has no attribute 'columns'
QUANTAXIS>> The 133 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000541
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000541 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 134 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.71% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000543
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000543 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 135 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000544
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000544 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 136 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.77% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000545
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000545 from 2019-03-29 to 2019-03-29
QUANTAXIS>> The 137 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000546
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000546 from 1990-01-01 to 2019-03-29
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
pip uninstall pytdx
pip install pytdx
'NoneType' object has no attribute 'columns'
QUANTAXIS>> The 138 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000547
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000547 from 1990-01-01 to 2019-03-29
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
pip uninstall pytdx
pip install pytdx
'NoneType' object has no attribute 'columns'
QUANTAXIS>> The 139 of Total 3605
QUANTAXIS>> DOWNLOAD PROGRESS 3.85% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000548 from 1990-01-01 to 2019-03-29

发送自 Windows 10 版邮件应用

发件人: Vincent yu
发送时间: 2019年3月31日 16:56
收件人: QUANTAXIS/QUANTAXIS
抄送: tonyyang1223; Mention
主题: Re: [QUANTAXIS/QUANTAXIS] Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同 (#1074)

@tonyyang1223 给一下报错的时候的信息或者截图 谢谢

**Comment by yawnlon** [comment]
我也遇到了同样的问题，请问lz解决了吗

**Comment by yutiansut** [comment]
@tonyyang1223  @yawnlon 

原因写的很明白了呀...
```
Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
pip uninstall pytdx
pip install pytdx

```

操作就是先卸载 再安装pytdx即可

我当时在pytdx里面加了个timeout的参数 但米哥的tushare内置的pytdx没有更新代码 所以导致更新过tushare后 pytdx的代码被覆盖

**Comment by yawnlon** [comment]
> @tonyyang1223 @yawnlon
> 
> 原因写的很明白了呀...
> 
> ```
> Tushare内置的pytdx版本和QUANTAXIS使用的pytdx 版本不同, 请重新安装pytdx以解决此问题
> pip uninstall pytdx
> pip install pytdx
> ```
> 
> 操作就是先卸载 再安装pytdx即可
> 
> 我当时在pytdx里面加了个timeout的参数 但米哥的tushare内置的pytdx没有更新代码 所以导致更新过tushare后 pytdx的代码被覆盖

解决了谢谢！

**Comment by fortune-fu** [comment]
000
