### ISSUE TITLE
为什么现在的数据获取接口不支持复权了？

### ISSUE THREAD

**Issue by Weiqiang-Li** [yutiansut/QUANTAXIS#1124]
# 问题反馈

## 您使用的QUANTAXIS版本号是什么?
```
quantaxis 1.4.3
```
## 您的系统环境是什么?
```
- monodb3,4
- nodejs(无)
- python3.6
- docker(无)
```
## 您需要反馈的问题
```
为什么现在的数据获取接口不支持复权了？

以下的接口调用：
QA.QA_fetch_get_stock_day('tdx','600519','2018-04-23','2018-04-23',if_fq='qfq')
QA.QAFetch.QATdx.QA_fetch_get_stock_day('600519','2019-04-23','2019-04-23','01')
QA.QA_fetch_get_stock_day('tdx','600519','2018-04-23','2018-04-23',if_fq='hfq')
QA.QAFetch.QATdx.QA_fetch_get_stock_day('600519','2019-04-23','2019-04-23','02')
都会返回：
CURRENTLY NOT SUPPORT REALTIME FUQUAN
的信息。

我在历史版本中看到这部分代码是实现了的，为啥现在没有了呢？
[历史版本QATdx.py](https://github.com/QUANTAXIS/QUANTAXIS/blob/9ed54295701c9207c1f777a3f5fa9ede51c96a14/QUANTAXIS/QAFetch/QATdx.py)

```
THANKS

**Comment by yutiansut** [comment]
因为现在都是本地复权  免得你们for循环的去无限取数据 然后接口爆炸

**Comment by Weiqiang-Li** [comment]
> 因为现在都是本地复权 免得你们for循环的去无限取数据 然后接口爆炸

回复好快，谢谢
我刚开始接触这方面，手动写还是有些难度，所以想请教一下有没有一些便捷的方法实现复权这个功能？

**Comment by yutiansut** [comment]
DataStruct,to_qfq() @jo-ny

**Comment by Weiqiang-Li** [comment]
> DataStruct,to_qfq() @jo-ny

我去研究一下，谢谢

**Comment by jo-ny** [comment]
> DataStruct,to_qfq() @jo-ny
您好：
我尝试使用这个方法，但是遇到一个问题：
DataStruct下的获取数据方法都是返回Error
![image](https://user-images.githubusercontent.com/12858403/56777203-c7092780-6802-11e9-9869-1ea45063dea1.png)
DataFetch下的获取数据的方法返回的是DataFrame，所以也不能使用to_qfq()方法
这样的问题该怎么解决？
