### ISSUE TITLE
qadesktop的菜单会被遮住

### ISSUE THREAD

**Issue by royburns** [yutiansut/QUANTAXIS#1128]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
QUANTAXIS VERSION: 1.4.3
quantaxis_community_webpackage_0.0.2

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
windows10，64bit，8g内存
chrome  73.0.3683.75（正式版本） （64 位）




```

## 您的系统环境是什么?
```
- monodb
- nodejs(V8)
- python3.5/3.6
- docker(无)
```
## 您需要反馈的问题
```
当有多个accout时，右键点击相应的accut，弹出的菜单会被遮住
```
![image](https://user-images.githubusercontent.com/652375/56781369-836be900-6815-11e9-86c0-9666608bccc9.png)
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@royburns 鼠标右键是全页面生效的  不要放那么下面

**Comment by royburns** [comment]
😂😂😂👌
