### ISSUE TITLE
ModuleNotFoundError: No module named 'pytdx.reader.history_financial_reader'

### ISSUE THREAD

**Issue by prehonor** [yutiansut/QUANTAXIS#1159]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```1.5.0



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs
- python3.6
- docker(有)
```
## 您需要反馈的问题
```
ModuleNotFoundError: No module named 'pytdx.reader.history_financial_reader'
这个报错,不知道为什么

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
ryx19891207@163.com
```

THANKS
by yutiansut
2017.12

**Comment by prehonor** [comment]
补充:
absl-py (0.7.0)
appdirs (1.4.3)
APScheduler (3.6.0)
asn1crypto (0.24.0)
astor (0.7.1)
attrs (19.1.0)
Automat (0.7.0)
beautifulsoup4 (4.7.1)
bs4 (0.0.1)
certifi (2018.11.29)
cffi (1.12.2)
chardet (3.0.4)
click (7.0)
colorama (0.4.1)
colorlog (4.0.2)
constantly (15.1.0)
cryptography (2.6.1)
cssselect (1.0.3)
cycler (0.10.0)
DBUtils (1.3)
delegator.py (0.1.1)
demjson (2.2.4)
docopt (0.6.2)
dukpy (0.2.2)
flask (1.0.2)
flask-socketio (3.3.2)
future (0.17.1)
gast (0.2.2)
gevent (1.4.0)
gevent-websocket (0.10.
greenlet (0.4.15)
grpcio (1.18.0)
h5py (2.9.0)
hyperlink (18.0.0)
idna (2.8)
incremental (17.5.0)
itsdangerous (1.1.0)
janus (0.4.0)
javascripthon (0.10)
jinja2 (2.10.1)
jupyter-echarts-pypkg (
Keras-Applications (1.0
Keras-Preprocessing (1.
kiwisolver (1.0.1)
lml (0.0.2)
lxml (4.3.2)
macropy3 (1.1.0b2)
Markdown (3.0.1)
markupsafe (1.1.1)
matplotlib (3.0.2)
motor (2.0.0)
msgpack (0.6.1)
mysqlclient (1.4.2)
numpy (1.16.3)
pandas (0.24.1)
parsel (1.5.1)
pexpect (4.7.0)
pillow (6.0.0)
pip (9.0.1)
pqi (2.0.6)
protobuf (3.6.1)
ptyprocess (0.6.0)
pyasn1 (0.4.5)
pyasn1-modules (0.2.4)
pyconvert (0.6.3)
pycparser (2.19)
PyDispatcher (2.0.5)
pyecharts (0.5.11)
pyecharts-javascripthon
pyecharts-jupyter-insta
pyecharts-snapshot (0.2
pyee (6.0.0)
PyExecJS (1.5.1)
PyHamcrest (1.9.0)
pymongo (3.8.0)
PyMySQL (0.9.3)
pyOpenSSL (19.0.0)
pyparsing (2.3.1)
pyppeteer (0.0.25)
pytdx (1.68)
pytesseract (0.2.6)
python-dateutil (2.8.0)
python-engineio (3.5.1)
python-socketio (3.1.2)
pytz (2019.1)
pywin32 (224)
pyzmq (18.0.1)
quantaxis (1.5.0, f:\eb
queuelib (1.5.0)
requests (2.21.0)
retrying (1.3.3)
scipy (1.2.1)
Scrapy (1.6.0)
seaborn (0.9.0)
selenium (3.141.0)
service-identity (18.1.
setuptools (40.8.0)
simplejson (3.16.0)
six (1.12.0)
soupsieve (1.9)
sqlalchemy (1.3.3)
tabulate (0.8.3)
tensorboard (1.12.2)
tensorflow-gpu (1.12.0)
termcolor (1.1.0)
tornado (6.0.2)
tqdm (4.31.1)
tushare (1.2.22)
Twisted (18.9.0)
tzlocal (1.5.1)
urllib3 (1.24.1)
w3lib (1.20.0)
websockets (7.0)
Werkzeug (0.14.1)
wheel (0.33.1)
wincertstore (0.2)
xlwt (1.3.0)
zenlog (1.1)
zope.interface (4.6.0)

**Comment by yutiansut** [comment]
@prehonor 

pip uninstall pytdx

pip install pytdx

因为tushare内置了一份早版本的pytdx 会覆盖pytdx代码但不会覆盖pytdx版本信息, 因此不容易查出来
