### ISSUE TITLE
分钟线的数据太多，如何删除？

### ISSUE THREAD

**Issue by gzMichael** [yutiansut/QUANTAXIS#1242]
# 问题反馈

使用 update_x.py 脚本更新后，发现分钟线的历史数据占用空间太大，如何去除这部分数据？

## 您使用的QUANTAXIS版本号是什么?

```
V1.5.3
```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

```

## 您的系统环境是什么?
```
- python/3.6
- docker(无)
```

**Comment by yutiansut** [comment]
彻底删除 还是?

**Comment by gzMichael** [comment]
彻底删除，后面需要时再重新更新装载

**Comment by yutiansut** [comment]
如果不会mongo shell的话 就下一个mongo3T 可视化的 可以一键删除  群文件也有

**Comment by gzMichael** [comment]
好的，先用shell清表
