### ISSUE TITLE
mongoDB中缺少一些可转债的数据

### ISSUE THREAD

**Issue by izhangmh** [yutiansut/QUANTAXIS#1315]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

QUANTAXIS 1.3.0

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
WIN10 64 24G





```

## 您的系统环境是什么?
```
- monodb
- nodejs
- python3.7
- docker(有)
```
## 您需要反馈的问题
mongoDB中缺少一些可转债的数据，比如
db.getCollection('stock_day').find({"code":"113013"})
db.getCollection('stock_min').find({"code":"113013"})
日线和分钟线数据都为空。

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```

```
## 您的联系方式(QQ/EMAIL)
qq: 9192578

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
你先试试用 

实时 QA_fetch_get_index_day/min...

数据库  QA_fetch_index_day/min

**Comment by izhangmh** [comment]
也失败了，取正股没问题。

>>> QA.QA_fetch_get_index_day('tdx','113013', '2019-01-01', '2020-01-05')
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datetime'


>>> QA.QA_fetch_index_day('113013', '2017-01-01', '2020-01-05')
array(None, dtype=object)

**Comment by yutiansut** [comment]
好的  我搞一下

**Comment by yutiansut** [comment]
@izhangmh 
QA.QA_fetch_get_bond_list('tdx') 我查了下好像没有这个债券的

**Comment by izhangmh** [comment]
新浪接口有，那是pytdx的问题吗？
http://hq.sinajs.cn/list=sh113013
var hq_str_sh113013="国君转债,119.600,118.750,117.640,119.600,117.010,117.010,117.640,77370,9186333.000,100,117.010,3180,117.000,100,116.680,20,116.650,1030,116.060,490,117.640,490,117.650,10,117.860,500,117.870,390,117.880,2019-09-30,15:00:12,00,";

**Comment by yutiansut** [comment]
```

code | volunit | decimal_point | name | pre_close | sse | sec
-- | -- | -- | -- | -- | -- | --

100303 | 10 | 3 | 国债0303 | 101.495003 | sz | bond_cn
100504 | 10 | 3 | 国债0504 | 100.000000 | sz | bond_cn
100512 | 10 | 3 | 国债0512 | 100.000000 | sz | bond_cn


```


```
QA.QAFetch.QATdx.QA_fetch_get_bond_day('100303','2019-01-01','2019-09-20')



open | close | high | low | vol | amount | date | code | date_stamp
-- | -- | -- | -- | -- | -- | -- | -- | --

100.578 | 100.580 | 100.586 | 100.558 | 5.877472e-39 | 3.922448e+04 | 2019-01-02 | 100303 | 1.546358e+09
100.580 | 100.822 | 101.000 | 100.340 | 5.000000e+00 | 6.011144e+05 | 2019-01-03 | 100303 | 1.546445e+09
100.995 | 100.830 | 101.288 | 100.791 | 8.194000e+03 | 4.242068e+05 | 2019-01-04 | 100303 | 1.546531e+09
100.513 | 101.000 | 101.200 | 100.513 | 5.877472e-39 | 8.382354e+04 | 2019-01-07 | 100303 | 1.546790e+09
100.901 | 101.011 | 101.097 | 100.901 | 4.098000e+03 | 3.312843e+05 | 2019-01-08 | 100303 | 1.546877e+09
101.487 | 101.027 | 101.487 | 100.967 | 4.098000e+03 | 3.031744e+05 | 2019-01-09 | 100303 | 1.546963e+09
101.087 | 100.997 | 101.087 | 100.924 | 4.098000e+03 | 3.939199e+05 | 2019-01-10 | 100303 | 1.547050e+09


```

**Comment by yutiansut** [comment]
@izhangmh 哦 我想起来当时我没写可转债 你稍等

当时我判断上海的可转债 11开头的 我就只查找了110开头的

```
        # sh
        # 110×××
        # 120×××企业债券；
        # 129×××
        # 100×××可转换债券；

        # sz
        # 10xxxx 国债现货
        # 11xxxx 债券
        # 12xxxx 可转换债券
        # 12xxxx 国债回购
```

**Comment by yutiansut** [comment]
@izhangmh 我加你qq了 qq上聊哈

**Comment by yutiansut** [comment]
我查了下 可转换债券的主要是这几个开头

```       
# 110×××
# 128xxxx
# 113xxxx
# 132xxxx
```

**Comment by yutiansut** [comment]
[15234 rows x 7 columns]
>>> QA.QA_fetch_get_bond_list('tdx').query('code=="113013"')
              code  volunit  decimal_point  name  pre_close sse      sec
code   sse
113013 sh   113013       10              3  国君转债     118.75  sh  bond_cn
>>>

**Comment by yutiansut** [comment]
![image](https://user-images.githubusercontent.com/11537812/66249469-c6d46700-e766-11e9-92f2-a125b37e6843.png)
![image](https://user-images.githubusercontent.com/11537812/66249470-ca67ee00-e766-11e9-8e62-16aa8048d355.png)

**Comment by yutiansut** [comment]
已经ok了 至此 qa对于债券的支持应该是完善了
