### ISSUE TITLE
dealprice的显示小数位数

### ISSUE THREAD

**Issue by rafaelchan** [yutiansut/QUANTAXIS#1355]
def callback_message(self):
        # 这是标准的return back message
        return [
            self.order.account_cookie,
            self.order.sending_time,
            self.trade_time,
            self.order.code,
            None,
            self.order.towards,
            float("%.2f" % float(self.deal_price)),
            self.order.price,
            self.status,
            self.order.amount,
            self.deal_amount,
            self.trade_money,
            0,
            self.order.order_id,
            QA_util_random_with_topic('Trade')
        ]

国债期货是3位小数  所以这里是不是应该3位格式显示

**Comment by yutiansut** [comment]
....唔 这里考虑的确实不是很周全
