### ISSUE TITLE
回测时没有交易信号报错

### ISSUE THREAD

**Issue by rafaelchan** [yutiansut/QUANTAXIS#1358]
使用qastrategy类回测，没有交易信号（因为使用过程中遇到了其他问题，sendorder注释了没有调用），使用的是那个cci的回测类。 错误和QAstrategy类应该是没关系。错误提示如下：

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-32825e265c02> in <module>
     38         # pprint.pprint(self.qifiacc.message)
     39 strategy =CCI(code='RB2001', frequence='1min',strategy_id='a3916de0-bd28-4b9c-bea1-94d91f1744ac',start='2019-09-03',end='2019-09-04')
---> 40 strategy.run_backtest()

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in run_backtest(self)
    130         self.acc.save()
    131 
--> 132         risk = QA_Risk(self.acc)
    133         risk.save()
    134 

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QARisk.py in __init__(self, account, benchmark_code, benchmark_type, if_fq, market_data, auto_reload)
    191                     ).fillna(method='pad')
    192             else:
--> 193                 self._assets = self.account.daily_cash.set_index('date'
    194                                                                  ).cash.fillna(
    195                     method='pad'

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QAAccountPro.py in daily_cash(self)
    728         res = self.cash_table.drop_duplicates(subset='date', keep='last')
    729         le = pd.DataFrame(pd.Series(data=None, index=pd.to_datetime(
--> 730             self.trade_range_max).set_names('date'), name='predrop'))
    731         ri = res.set_index('date')
    732         res_ = pd.merge(le, ri, how='left', left_index=True, right_index=True)

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QAAccountPro.py in trade_range_max(self)
    561     @property
    562     def trade_range_max(self):
--> 563         if self.start_date < str(min(self.time_index_max))[0:10]:
    564             return QA_util_get_trade_range(self.start_date, self.end_date)
    565         else:

ValueError: min() arg is an empty sequence

**Comment by yutiansut** [comment]
没信号很正常呀……

**Comment by rafaelchan** [comment]
好的 那我忽略了  不需要LIST为空时异常处理

**Comment by rafaelchan** [comment]
好的 那我忽略了  不需要LIST为空时异常处理
现在我把代买复原  也就是测试源码了  碰到的错误提示是：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-dc6367618b6f> in <module>
     39 
     40 strategy =CCI(code='RB2001', frequence='1min',strategy_id='a3916de0-bd28-4b9c-bea1-94d91f1744ac',start='2019-09-04', end='2019-09-04')
---> 41 strategy.run_backtest()

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in run_backtest(self)
    127 
    128     def run_backtest(self):
--> 129         self.debug()
    130         self.acc.save()
    131 

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in debug(self)
    172             self.on_bar(item)
    173 
--> 174         data.data.apply(x1, axis=1)
    175 
    176     def debug_t0(self):

/usr/local/lib/python3.6/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6485                          args=args,
   6486                          kwds=kwds)
-> 6487         return op.get_result()
   6488 
   6489     def applymap(self, func):

/usr/local/lib/python3.6/site-packages/pandas/core/apply.py in get_result(self)
    149             return self.apply_raw()
    150 
--> 151         return self.apply_standard()
    152 
    153     def apply_empty_result(self):

/usr/local/lib/python3.6/site-packages/pandas/core/apply.py in apply_standard(self)
    255 
    256         # compute the result using the series generator
--> 257         self.apply_series_generator()
    258 
    259         # wrap results

/usr/local/lib/python3.6/site-packages/pandas/core/apply.py in apply_series_generator(self)
    284             try:
    285                 for i, v in enumerate(series_gen):
--> 286                     results[i] = self.f(v)
    287                     keys.append(v.name)
    288             except Exception as e:

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in x1(item)
    170             self._market_data.append(item)
    171             self.running_time = str(item.name[0])
--> 172             self.on_bar(item)
    173 
    174         data.data.apply(x1, axis=1)

<ipython-input-13-dc6367618b6f> in on_bar(self, bar)
     25 
     26         elif res.CCI[-1] > 100:
---> 27             if self.positions.volume_short == 0:
     28                 self.send_order('SELL', 'OPEN', price=bar['close'], volume=1)
     29             if self.positions.volume_long > 0:

AttributeError: ("'dict' object has no attribute 'volume_short'", 'occurred at index (2019-09-04 10:31:00, RB2001)')

我这边只能self.positions['volume_short'] 这样使用，不能像 self.positions.volume_short这样使用  但是又没看到其他人反映这个问题  是什么原因啊

**Comment by yutiansut** [comment]
哦 你是不是相同strategy_id跑了两遍？ 换strategy_id

**Comment by rafaelchan** [comment]
没有，我还是刚pull的docker,我这边打印positions，是一个dict变量。

**Comment by yutiansut** [comment]
> 没有，我还是刚pull的docker,我这边打印positions，是一个dict变量。

换一个strategyid 这跟镜像无关

**Comment by rafaelchan** [comment]
似乎和strategyid无关  看github代码self.positions应该是一个QAPosition对象，但打印出来是<class 'dict'>
{'volume_long': 0, 'volume_short': 0, 'volume_long_frozen': 0, 'volume_short_frozen': 0}

**Comment by yutiansut** [comment]
你换一个strategy_id跑出来还是这个样？ 你换了吗

**Comment by rafaelchan** [comment]
换了 随意换了一串数字

**Comment by rafaelchan** [comment]
pip install 的版本是： Successfully installed qastrategy-0.0.13

**Comment by yutiansut** [comment]
可复现的源代码贴一下

**Comment by rafaelchan** [comment]
from QAStrategy import QAStrategyCTABase
import QUANTAXIS as QA
import pprint


class CCI(QAStrategyCTABase):

    def on_bar(self, bar):

        res = self.cci()

        print(res.iloc[-1])

        if res.CCI[-1] < -100:

            print('LONG')

            if self.positions.volume_long == 0:
                self.send_order('BUY', 'OPEN', price=bar['close'], volume=1)

            if self.positions.volume_short > 0:
                self.send_order('SELL', 'CLOSE', price=bar['close'], volume=1)

        elif res.CCI[-1] > 100:
            print(self.running_mode)
            print(self.positions)
            print(type(self.positions))
            print(self.acc.get_position(code='rb2001'))
            print(self.acc.market_type)
            if self.positions.volume_short == 0:
                self.send_order('SELL', 'OPEN', price=bar['close'], volume=1)
            if self.positions.volume_long > 0:
                self.send_order('BUY', 'CLOSE', price=bar['close'], volume=1)

                
    def cci(self,):
        return QA.QA_indicator_CCI(self.market_data, 61)

    def risk_check(self):
        pass
        # pprint.pprint(self.qifiacc.message)
        
        
strategy =CCI(code='RB2001', frequence='1min',strategy_id='xxxxxx3333333',start='2019-09-04', end='2019-09-04')    
strategy.run_backtest()

**Comment by rafaelchan** [comment]
同样的代码 我在本地配置的环境运行完全正常 没有碰到这个问题了  之前的问题是在docker中碰到的 关了吧
