### ISSUE TITLE
QAStratety 模拟的问题

### ISSUE THREAD

**Issue by rafaelchan** [yutiansut/QUANTAXIS#1361]
环境：本地化，非docker，代码就是教程例子，如下：

from QAStrategy import QAStrategyCTABase
import QUANTAXIS as QA
import pprint
class CCI(QAStrategyCTABase):
    def on_bar(self, bar):
        print('test')
        print(bar)
        res = self.cci()
        print(res.iloc[-1])
        if res.CCI[-1] < -100:
            if self.positions.volume_long == 0:
                print('LONG')
                self.send_order('BUY', 'OPEN', price=bar['close'], volume=1)
            if self.positions.volume_short > 0:
                self.send_order('SELL', 'CLOSE', price=bar['close'], volume=1)
        elif res.CCI[-1] > 100:
           
            if self.positions.volume_short == 0:
                print('SHORT')
                self.send_order('SELL', 'OPEN', price=bar['close'], volume=1)
            if self.positions.volume_long > 0:
                self.send_order('BUY', 'CLOSE', price=bar['close'], volume=1)

    def cci(self,):
        return QA.QA_indicator_CCI(self.market_data, 61)

    def risk_check(self):
        pass
        # pprint.pprint(self.qifiacc.message)    
strategy =CCI(code='RB2001', frequence='1min',strategy_id='zzzzzzz2222')
strategy.debug_sim()

错误提示如下，回测是正常的。
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-6fa4a247b7a4> in <module>
     40 
     41 strategy =CCI(code='RB2001', frequence='1min',strategy_id='zzzzzzz2222')
---> 42 strategy.debug_sim()

c:\python37\lib\site-packages\QAStrategy\qactabase.py in debug_sim(self)
    118 
    119     def debug_sim(self):
--> 120         self._debug_sim()
    121         threading.Thread(target=self.sub.start, daemon=True).start()
    122 

c:\python37\lib\site-packages\QAStrategy\qactabase.py in _debug_sim(self)
    103 
    104         self.acc = QIFI_Account(
--> 105             username=self.strategy_id, password=self.strategy_id, trade_host=mongo_ip, init_cash=self.init_cash)
    106         self.acc.initial()
    107 
TypeError: __init__() got an unexpected keyword argument 'init_cash'

**Comment by yutiansut** [comment]
哦 升级qifiaccount

**Comment by rafaelchan** [comment]
刚才问了群友原来是位置不对 https://github.com/yutiansut/QIFIAccount/blob/master/QIFIAccount/QAQIFIAccount.py
https://github.com/QUANTAXIS/QIFIAccount/blob/master/QIFIAccount/QAQIFIAccount.py
我搞成了下面的链接

**Comment by rafaelchan** [comment]
还有一个疑问 https://github.com/QUANTAXIS/QAOTGBROKER  OTG的地址是这个吗？
从这里clone本地 版本后安装版本是1.9.0  但是从python官网install 是1.9.2

**Comment by yutiansut** [comment]
没事 放心升级

**Comment by yutiansut** [comment]
pip install quantaxis-otgbroker -U

**Comment by yutiansut** [comment]
https://pypi.org/user/yutiansut/ 这里面的都可以直接pip install

**Comment by rafaelchan** [comment]
好的 关了
