### ISSUE TITLE
发现错别字

### ISSUE THREAD

**Issue by MrSoya** [yutiansut/QUANTAXIS#1362]
解约时间/人员成本

**Comment by yutiansut** [comment]
唔....

**Comment by yutiansut** [comment]
尴尬😅

**Comment by yutiansut** [comment]
fix  in https://github.com/QUANTAXIS/QUANTAXIS/commit/c413b641e5c0ff30675fd21f73c1ef094f3a0a8c


已修改 @MrSoya
