### ISSUE TITLE
策略中realtime_min 单/多标的数据不能顺利获取并报错，之前realtime_tick数据获取成功了

### ISSUE THREAD

**Issue by ToughStyle** [yutiansut/QUANTAXIS#1368]
您使用的QUANTAXIS版本号是什么?
1.6.12

您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10, x64

您的系统环境是什么?
- monodb
- nodejs(V9以下版本)
- python3.7
- docker(无)

您需要反馈的问题

import QUANTAXIS as QA
from QAStrategy.qactabase import QAStrategyCTABase

class CCI(QAStrategyCTABase):

    def on_tick(self, tick):
        print('tick=======================================\n',tick)
        
    def on_bar(self, bar):
        print('1min=======================================\n',bar)

    def cci(self, code):

        market_data = self.get_code_marketdata(code)
        return QA.QA_indicator_CCI(market_data, 61)

code0 = 'NI2003'
code1= 'NI2002'

strategy = CCI(code=code0, frequence='min',
               strategy_id='a3916de0-bx8-4b19c-bxxax1-94d91f1744ac', start='2019-10-01', end='2019-11-01')
strategy.run_sim()

---------------------------------------------------------------------------
QUANTAXIS>> Selecting the Best Server IP of TDX
USING DEFAULT STOCK IP
USING DEFAULT FUTURE IP
QUANTAXIS>> === The BEST SERVER ===
 stock_ip 180.153.18.170 future_ip 124.74.236.94
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
c:\vnstudio\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2656             try:
-> 2657                 return self._engine.get_loc(key)
   2658             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'datetime'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-391c4a496ce9> in <module>
     32 strategy = CCI(code=code0, frequence='min',
     33                strategy_id='a3916de0-bx8-4b19c-bxxax1-94d91f1744ac', start='2019-10-01', end='2019-11-01')
---> 34 strategy.run_sim()
     35 
     36 

c:\vnstudio\lib\site-packages\QAStrategy\qactabase.py in run_sim(self)
    146 
    147     def run_sim(self):
--> 148         self._debug_sim()
    149 
    150         self.sub.start()

c:\vnstudio\lib\site-packages\QAStrategy\qactabase.py in _debug_sim(self)
    106             if isinstance(self.code, str):
    107                 self._old_data = QA.QA_fetch_get_future_min('tdx', self.code.upper(), QA.QA_util_get_last_day(
--> 108                     QA.QA_util_get_real_date(str(datetime.date.today()))), str(datetime.datetime.now()), self.frequence)[:-1].set_index(['datetime', 'code'])
    109                 self._old_data = self._old_data.assign(volume=self._old_data.trade).loc[:, [
    110                     'open', 'high', 'low', 'close', 'volume']]

c:\vnstudio\lib\site-packages\QUANTAXIS\QAFetch\__init__.py in QA_fetch_get_future_min(package, code, start, end, frequence)
    326     Engine = use(package)
    327     if package in ['tdx', 'pytdx']:
--> 328         return Engine.QA_fetch_get_future_min(code, start, end, frequence=frequence)
    329     else:
    330         return 'Unsupport packages'

c:\vnstudio\lib\site-packages\QUANTAXIS\QAFetch\QATdx.py in QA_fetch_get_future_min(code, start, end, frequence, ip, port)
   2221         # print(data.datetime)
   2222         data = data \
-> 2223             .assign(tradetime=data['datetime'].apply(str), code=str(code),
   2224                     datetime=pd.to_datetime(
   2225                 data['datetime'].apply(QA_util_future_to_realdatetime, 1))) \

c:\vnstudio\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2925             if self.columns.nlevels > 1:
   2926                 return self._getitem_multilevel(key)
-> 2927             indexer = self.columns.get_loc(key)
   2928             if is_integer(indexer):
   2929                 indexer = [indexer]

c:\vnstudio\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2657                 return self._engine.get_loc(key)
   2658             except KeyError:
-> 2659                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2660         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2661         if indexer.ndim > 1 or indexer.size > 1:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'datetime'

**Comment by yutiansut** [comment]
你没有指定你订阅的周期啊

**Comment by ToughStyle** [comment]
strategy = CCI(code=code0, frequence='min',这里不是吗？请问哪里可以指定订阅周期啊

**Comment by yutiansut** [comment]
是 但是要指定啊 frequence='15min' 比如  @pilotao
