### ISSUE TITLE
QAData QAIndicatorStruct 中get_timerange函数有小错误

### ISSUE THREAD

**Issue by zx403413599** [yutiansut/QUANTAXIS#1370]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

最新版本的QUANTAXIS1.7

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python33.6
- docker(无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12
天神，QAData QAIndicatorStruct 中get_timerange函数好像有小错误

    def get_timerange(self, start, end, code=None):
        """
        获取某一段时间的某一只股票的指标
        """
        try:
            return self.data.loc[(slice(pd.Timestamp(start), pd.Timestamp(end)), slice(code)), :]
        except:
            return ValueError('CANNOT FOUND THIS TIME RANGE')
函数如果是取一只票的话应该不能用slice吧？
我觉得改成如下的用法
    def get_timerange(self, start, end, code=None):
        """
        获取某一段时间的某一只股票的指标
        """
        try:
            return self.data.loc[(slice(pd.Timestamp(start), pd.Timestamp(end)), code), :]
        except:
            return ValueError('CANNOT FOUND THIS TIME RANGE')

**Comment by yutiansut** [comment]
确认是bug  你可以发个pr来成为开发者 😁  @zx403413599

**Comment by zx403413599** [comment]
> 确认是bug 你可以发个pr来成为开发者 😁 @zx403413599

哈哈 谢谢天神 ，开发能力还不行 ，只会用代码 出错了 找下bug。

**Comment by yutiansut** [comment]
> > 确认是bug 你可以发个pr来成为开发者 😁 @zx403413599
> 
> 哈哈 谢谢天神 ，开发能力还不行 ，只会用代码 出错了 找下bug。

https://github.com/QUANTAXIS/QUANTAXIS/pull/1372 fixed

**Comment by yutiansut** [comment]
release  in  1.7.1  https://github.com/QUANTAXIS/QUANTAXIS/releases/tag/1.7.1
