### ISSUE TITLE
使用quantaxis_webserver和qatrader时自动退出 ，求解答

### ISSUE THREAD

**Issue by zx403413599** [yutiansut/QUANTAXIS#1371]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

最新1.7

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.6
- docker(无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)：
```

```

THANKS
by yutiansut
2017.12

windows cmd使用quantaxis_webserver或者qatrader或者QARC_WEBSERVER等，过一段时间就自动报错了：
Error while finding module specification for '__main__' (ValueError: __main__.__spec__ is None)。具体见下图：

![1](https://user-images.githubusercontent.com/13033322/71544674-7fecbb00-29bd-11ea-8a31-e69e8e1849c1.png)

不知道大家有没有这种问题？是不是我应该注意一些 操作呢？

**Comment by yutiansut** [comment]
再观察观察  应该没啥 问题
