### ISSUE TITLE
前复权和wind的前复权差点点

### ISSUE THREAD

**Issue by panyuan5056** [yutiansut/QUANTAXIS#1410]
根据qa的公式计算出来的前复权
比如
qa:
002916            date   close    preclose
0    2017-12-13   27.79   22.844123
1    2017-12-14   30.57   25.129357
2    2017-12-15   33.63   27.644759
3    2017-12-18   36.99   30.406769
而wind
2017-12-13 00:00:00.005     22.844958
2017-12-14 00:00:00.005     25.130275
2017-12-15 00:00:00.005     27.645769
2017-12-18 00:00:00.005     30.407880

**Comment by yutiansut** [comment]
是这样 我们是定点的 而wind的默认应该是从最新的交易日开始的  你如果要比较需要一直取到最新的一天再做


这样的原因是 假设你只要做2017-2018年的回测 不至于吧2019年的信息因为复权的问题而带入了未来数据
