### ISSUE TITLE
策略回测对于指数的支持

### ISSUE THREAD

**Issue by shenxingbei** [yutiansut/QUANTAXIS#143]
在示例策略中：
    #benchmark 必须是指数代码
    QB.benchmark_code='399300'

    QB.strategy_stock_list=['000001','000002','600010','601801'] # 回测的股票列表
    QB.strategy_start_date='2016-07-01'  # 回测开始日期
    QB.strategy_end_date='2017-07-10'    # 回测结束日期

回测的股票池必须是股票，是否可以改成对指数进行回测，这样可以编写指数择时类型的策略。

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/pull/157
