### ISSUE TITLE
回测中使用QA_AccountPRO如何设置滑点

### ISSUE THREAD

**Issue by luohan475947645** [yutiansut/QUANTAXIS#1430]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.8.0


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
docker




```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
最近在看项目的实现源码，QAStrategy中使用QA_Account进行回测时，有佣金、税率的初始化参数，但没有`滑点`，这个对于回测同重要的。使用的时候是否可以在account.receive_deal的参数字典中，将成交价格调高，实现这种测试呢。

对整个项目的账户结算过程还没来得及详细看内部计算方法，所以伸手直接问下天神了。。。
```python
class QA_AccountPRO(QA_Worker):
    def __init__(
        self,
        user_cookie: str,
        portfolio_cookie: str,
        account_cookie=None,
        strategy_name=None,
        market_type=MARKET_TYPE.STOCK_CN,
        frequence=FREQUENCE.DAY,
        broker=BROKER_TYPE.BACKETEST,
        init_hold={},
        init_cash=1000000,
        commission_coeff=0.00025,
        tax_coeff=0.001,
        margin_level={},
        allow_t0=False,
        allow_sellopen=False,
        allow_margin=False,
        running_environment=RUNNING_ENVIRONMENT.BACKETEST,
        auto_reload=False,
        generated='direct',
        start=None,
        end=None
    ):
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
475947645
```

THANKS
by yutiansut
2017.12

**Comment by luohan475947645** [comment]
还有一个，股票结算的问题，考虑了 分红 送股 这些内容吗，我在QA_Account.settle()这个函数中好像没有读到

**Comment by yutiansut** [comment]
哦 简单 你可以直接在你的成交价格上加啊....

**Comment by yutiansut** [comment]
跟账户没关系  就跟真实情况一样 这不是账户类需要操心的事情....

**Comment by yutiansut** [comment]
> 还有一个，股票结算的问题，考虑了 分红 送股 这些内容吗，我在QA_Account.settle()这个函数中好像没有读到

结算不考虑  只是记录下你的持仓数量 在QARisk里面算账户净值的时候 会用复权数据来计算你的账户市值 这样就把分红配送股考虑进去了

**Comment by luohan475947645** [comment]
> > 还有一个，股票结算的问题，考虑了 分红 送股 这些内容吗，我在QA_Account.settle()这个函数中好像没有读到
> 
> 结算不考虑 只是记录下你的持仓数量 在QARisk里面算账户净值的时候 会用复权数据来计算你的账户市值 这样就把分红配送股考虑进去了

ok，基本明白了 忽略了还有QARisk做统计分析
