### ISSUE TITLE
cci 样咧代码测试报错，

### ISSUE THREAD

**Issue by bradbann** [yutiansut/QUANTAXIS#1456]
# 问题反馈
docker  少numba 包

测试代码如下
https://github.com/QUANTAXIS/QAStrategy/blob/master/example/CCI_EXample.py

QUANTAXIS>> QA something wrong with date
QA Error QA_fetch_future_day_adv parameter code=[] start=None end=None call QA_fetch_future_day return None
QAACCOUNT: THIS ACCOUNT DOESNOT HAVE ANY TRADE
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-e7c5e381a908> in <module>
     59     """ 回测
     60     """
---> 61     strategy.run_backtest()

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in run_backtest(self)
    157         self.acc.save()
    158 

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
 1.8.3

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
首先你应该从教程开始看  比如 你的问题是  没有存数据 ...http://www.yutiansut.com:3000/topic/5dc5da7dc466af76e9e3bc5d

**Comment by yutiansut** [comment]
[cciexample_result.zip](https://github.com/QUANTAXIS/QUANTAXIS/files/4246263/cciexample_result.zip)
我已经上传了cci_example跑的完整ipynb文件 自己对着看看吧

@bradbann
