### ISSUE TITLE
QAStratety做回测时所拿到的最大k线数量

### ISSUE THREAD

**Issue by sunkokin** [yutiansut/QUANTAXIS#1501]
我在用QAStratety写代码的时候，发现所用到的k线数量最多是100，这个数字在哪里可以调吗，我的代码可能需要用到更多的k线。

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
哦哦哦 可以改的 在QAStrategy里面设置即可

**Comment by sunkokin** [comment]
@property
    def market_data(self):

        if self.running_mode == 'sim':
            return self._market_data
        elif self.running_mode == 'backtest':
            return pd.concat(self._market_data[-100:], axis=1, sort=False).T

是不是修改这里的这个100就可以了？

**Comment by sunkokin** [comment]
好像不对，改了没有效果

**Comment by yutiansut** [comment]
@sunkokin https://github.com/yutiansut/QAStrategy/blob/master/QAStrategy/qactabase.py#L386
这个文件的

**Comment by sunkokin** [comment]
可以了就是那个地方，kernel重启一把就好，多谢
