### ISSUE TITLE
求助：买卖信号的k线图详情出不来

### ISSUE THREAD

**Issue by sunkokin** [yutiansut/QUANTAXIS#1502]
# 问题反馈
大神，再请教一个问题
![image](https://user-images.githubusercontent.com/62975996/78214521-0b5b7800-74e8-11ea-9fdb-a79bd6bf7661.png)

我的界面里，买卖信号的k线图详情，一直都出不来，docker的也试了，本地安装也试了，都出不来，能不能给点参考？

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
是我的bug 之后会修复
