### ISSUE TITLE
janus 0.5.0 兼容版本问题

### ISSUE THREAD

**Issue by Rgveda** [yutiansut/QUANTAXIS#1513]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

1.9.16

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

Win10 Pro 64位 
内存64G
CPU E5-2699

```

## 您的系统环境是什么?
```
- monodb  4.3.7
- nodejs(V9以下版本)
- python3.5/3.6  3.7.7
- docker(有无)   无
```
## 您需要反馈的问题
```
janus              0.5.0 版本问题
janus              0.4.0 没问题，
服务器意外升级 0.50 报错，应该在安装脚本中指定一下janus版本，我看看我会不会改
  File "d:\app\quantaxis\QUANTAXIS\QAEngine\QAAsyncThread.py", line 13, in QA_AsyncThread
    _queue: QA_AsyncQueue = QA_AsyncQueue(loop=_loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by Rgveda** [comment]
解决办法，降级 janus，
python -m pip install -U janus
pip install janus==0.4.0 -i https://pypi.doubanio.com/simple

**Comment by yutiansut** [comment]
fixed in https://github.com/QUANTAXIS/QUANTAXIS/pull/1516
