### ISSUE TITLE
关于收费数据

### ISSUE THREAD

**Issue by zhimiQi** [yutiansut/QUANTAXIS#1537]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```
我看到这个数据是取自通达信的数据，那么如果我在通达信上购买服务，如我开通L2的权限，请问我能通过此系统取得逐笔数据或是L2的行情数据吗？
感谢您的回复。
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
没看懂你想问啥

**Comment by yutiansut** [comment]
l2部分需要你自己获取

**Comment by zhimiQi** [comment]
> l2部分需要你自己获取

好的，感谢回复
