### ISSUE TITLE
docker安装之后，用QAStrategy回测报错~

### ISSUE THREAD

**Issue by wangxu666** [yutiansut/QUANTAXIS#1543]
prortfolio with user_cookie  USER_yfQK2poG  already exist!!
QAACCPRO: reload from DATABASE
{}
< QA_AccountPRO 1dd8b22d-7902-4a85-adb2-fbac4bb977fe market: future_cn>
future_cn
QAACCOUNT: THIS ACCOUNT DOESNOT HAVE ANY TRADE
QAACCOUNT: THIS ACCOUNT DOESNOT HAVE ANY TRADE
QAACCOUNT: THIS ACCOUNT DOESNOT HAVE ANY TRADE
QAACCOUNT: THIS ACCOUNT DOESNOT HAVE ANY TRADE
QUANTAXIS>> QA something wrong with date
QA Error QA_fetch_future_day_adv parameter code=[] start=None end=None call QA_fetch_future_day return None
QAACCOUNT: THIS ACCOUNT DOESNOT HAVE ANY TRADE
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-752ea9adc172> in <module>
     40     DMA = DMA(code='rb2005', frequence='1min',
     41          strategy_id='1dd8b22d-7902-4a85-adb2-fbac4bb977fe', start='2019-10-01', end='2019-11-01') 
---> 42     DMA.run_backtest()

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in run_backtest(self)
    190         self.acc.save()
    191 
--> 192         risk = QA_Risk(self.acc)
    193         risk.save()
    194 

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QARisk.py in __init__(self, account, benchmark_code, benchmark_type, if_fq, market_data, auto_reload)
    180                     self._assets = (self.market_value.sum(axis=1) + self.account.daily_cash.set_index('date').cash).fillna(method='pad')
    181             else:
--> 182                 self._assets = self.account.daily_cash.set_index('date').cash.fillna(method='pad')
    183 
    184             self.time_gap = QA_util_get_trade_gap(self.account.start_date,

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QAAccountPro.py in daily_cash(self)
    634             pd.Series(
    635                 data=None,
--> 636                 index=pd.to_datetime(self.trade_range_max).set_names('date'),
    637                 name='predrop'
    638             )

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QAAccountPro.py in trade_range_max(self)
    437     @property
    438     def trade_range_max(self):
--> 439         if self.start_date < str(min(self.time_index_max))[0:10]:
    440             return QA_util_get_trade_range(self.start_date, self.end_date)
    441         else:

ValueError: min() arg is an empty sequence

**Comment by yutiansut** [comment]
账户没有任何交易  就会导致这个问题 直接try except 即可
