### ISSUE TITLE
数据无限重复下载？

### ISSUE THREAD

**Issue by john012343210** [yutiansut/QUANTAXIS#1544]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
 1.9.24

## 您需要反馈的问题

![photo_2020-06-07_15-58-11](https://user-images.githubusercontent.com/36737465/83963355-02b46300-a8d8-11ea-93b2-965dd6ef292d.jpg)

**Comment by yutiansut** [comment]
已经fix了呀
