### ISSUE TITLE
获取日数据出现QA Error，无返回数据

### ISSUE THREAD

**Issue by jasonber** [yutiansut/QUANTAXIS#1546]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.9.24


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

win10 2004 64位 16G内存



```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
获取数据报错，没有返回任何数据
```
QA Error QA_fetch_stock_day_adv parameter code=000001 , start=2017-01-01, end=2017-10-01 call QA_fetch_stock_day return None

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```
大佬牛P！ 大佬加油！


```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
没有存数据  请看下教程
