### ISSUE TITLE
获取股票数据时显示USING DEFAULT STOCK IP、USING DEFAULT FUTURE IP

### ISSUE THREAD

**Issue by TakeDumbbell** [yutiansut/QUANTAXIS#1550]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

1.9.23

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

win10专业版 64 8g



```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.6
- docker(有)
```
## 您需要反馈的问题
```
无法获取股票数据和期货数据
![图片](https://user-images.githubusercontent.com/31396458/87108575-35fe5f00-c295-11ea-9c6c-4d4c3fb77519.png)


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```

谢谢天神！

```
## 您的联系方式(QQ/EMAIL)
```
QQ:2399644890
```

THANKS
by yutiansut
2017.12

**Comment by TakeDumbbell** [comment]
已解决，得到的结果进入data了，jupyter不自动打印。。。。谢谢天神

**Comment by yutiansut** [comment]
ok  那我close了  @TakeDumbbell
