### ISSUE TITLE
无法获取 20200630 的财务数据

### ISSUE THREAD

**Issue by kent119952** [yutiansut/QUANTAXIS#1590]
# 问题反馈

## 您使用的QUANTAXIS版本号是什么?
```
直接 clone 下来的代码
master branch
```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
在docker container 中直接运行 QACmd.CLI.do_save("financialfiles")
docker image: Alpine

```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python: 3.6
- docker：有，在container 里运行 QACmd.CLI.do_save("financialfiles")
```
## 您需要反馈的问题

![image](https://user-images.githubusercontent.com/69895239/96859982-c3f10500-1494-11eb-9767-e7d0baa9f75d.png)

![image](https://user-images.githubusercontent.com/69895239/96858678-2ba65080-1493-11eb-8f37-c6600c91c90c.png)

```
2020年06月30日的财务数据应该是已经有了，但是无法通过 QACmd.CLI.do_save("financialfiles") 下载。
其他时间点的财务数据都正常更新了，唯独20200630的不行。
Log 如上图1 所示。

我尝试用浏览器手动下载，出现上图2 的错误。
但是我看 http://data.yutiansut.com/content.txt 中显示：
gpcw20200630.zip,9703d1603650104363287a81c0eaf70c,311726

貌似20200630应该是有数据的才对。

请问如何解决？ 谢谢。

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
1486528404
```

**Comment by yutiansut** [comment]
@kent119952 已更新
