### ISSUE TITLE
QUANTAXIS的爬虫如何运行?如何构建自己的自定义爬虫?

### ISSUE THREAD

**Issue by yutiansut** [yutiansut/QUANTAXIS#16]

**Comment by yutiansut** [comment]
准备把爬虫框架组合,标准化一下,搞成爬虫脚手架

**Comment by wh1100717** [comment]
@yutiansut  哈哈 赞赞哒 你这是打算做一个scrapy啊

**Comment by yutiansut** [comment]
哈哈 没有scrapy那么麻烦辣~~

其实很多人的需求很简单 要么是有反爬的要么是没有反爬的,我准备标准化三套代码 一套是直接爬的那种 不用登录什么限制都没有的  一套是加入模拟登录,加入随机UserAgent , 第三套是加入更换sessionid,cookie的那种  

然后标准化输出,主要是 数据和舆情信息,类似你们的Mod的概念,我觉得ricequant的mod想法很赞.
这样大家就可以根据自己要爬的网站的需求,以及目标网站的反爬level进行自主选择框架,以标准化的形式存进数据库可以很容易集成到原来的框架里面来.

类似脚手架的感觉,这样比较方便公共代码复用

**Comment by wh1100717** [comment]
@yutiansut 恩恩 不过scrapy的 pipeline机制还是可以借鉴的  每个人的需求可能都比较简单，但每个人的业务场景未必是一样的，所以如果做通用性的scaffold 还是比较难的。

**Comment by better319** [comment]
那个mod的模式确实挺好的
