### ISSUE TITLE
使用QAStrategy 回测，没有交易，QARisk处理时出现异常。

### ISSUE THREAD

**Issue by newlyedward** [yutiansut/QUANTAXIS#1604]
# 问题反馈

from QAStrategy import QAStrategyCTABase
import QUANTAXIS as QA

class Strategy(QAStrategyCTABase):

    def on_bar(self, bar):
        print(bar)
        
s = Strategy(code='RBL8', frequence='5min', strategy_id= 'xxx3', start='2020-12-20', end='2020-12-27') 
s.run_backtest()

debug跟踪了一下源代码  self.account.start_date和self.account.end_date都是None
QARisk.py中161行  
                elif self.account.market_type == MARKET_TYPE.FUTURE_CN:
                    self.market_data = QA_fetch_future_day_adv([item.upper() for item in self.account.code],
                                                               self.account.start_date,
                                                               self.account.end_date)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-85896d947f5d> in <module>
      8 
      9 s = Strategy(code='RBL8', frequence='5min', strategy_id= 'xxx3', start='2020-12-20', end='2020-12-27')
---> 10 s.run_backtest()

/usr/local/lib/python3.6/site-packages/QAStrategy/qactabase.py in run_backtest(self)
    190         self.acc.save()
    191 
--> 192         risk = QA_Risk(self.acc)
    193         risk.save()
    194 

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QARisk.py in __init__(self, account, benchmark_code, benchmark_type, if_fq, market_data, auto_reload)
    182                         axis=1) + self.account.daily_cash.set_index('date').cash).fillna(method='pad')
    183             else:
--> 184                 self._assets = self.account.daily_cash.set_index(
    185                     'date').cash.fillna(method='pad')
    186 

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QAAccountPro.py in daily_cash(self)
    634             pd.Series(
    635                 data=None,
--> 636                 index=pd.to_datetime(self.trade_range_max).set_names('date'),
    637                 name='predrop'
    638             )

/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAARP/QAAccountPro.py in trade_range_max(self)
    437     @property
    438     def trade_range_max(self):
--> 439         if self.start_date < str(min(self.time_index_max))[0:10]:
    440             return QA_util_get_trade_range(self.start_date, self.end_date)
    441         else:

ValueError: min() arg is an empty sequence

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.10.1


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
没有交易 你用risk不报异常还想做啥？

**Comment by newlyedward** [comment]
好
