### ISSUE TITLE
文档图片都挂了

### ISSUE THREAD

**Issue by lux182** [yutiansut/QUANTAXIS#1635]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
master
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
64

## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有无)
```

## 您需要反馈的问题

文档图片都挂了

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
已经修复图床问题
