### ISSUE TITLE
数据初始化存储失败了

### ISSUE THREAD

**Issue by balsid** [yutiansut/QUANTAXIS#1637]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.9

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
Windows 10 Home, x64, 8G RAM

## 您的系统环境是什么?
```
- monodb 4.4
- python 3.8.5
- docker(无)
```

## 您需要反馈的问题

第一次安装quantaxis, 按照https://github.com/yutiansut/QUANTAXIS/blob/master/Documents/install.md
安装后在运行save all时出错了，如下。不知为什么。谢谢。

QUANTAXIS> save all
...
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688981 from 1990-01-01 to 2021-01-20
__enter__
'NoneType' object has no attribute 'columns'
QUANTAXIS>> The 4187 of Total 4188
QUANTAXIS>> DOWNLOAD PROGRESS 99.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 689009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 689009 from 1990-01-01 to 2021-01-20
__enter__
'NoneType' object has no attribute 'columns'
QUANTAXIS>> ERROR CODE

QUANTAXIS>> ['000019', '000088', '000089', '000090', '000096', '000099', '000155', '000661', '000691', '000762', '000780', '000782', '000783', '000785', '000786', '000795', '000798', '000800', '000801', '000802', '000803', '000806', '000807', '000809', '000810', '000821', '000822', '000823', '000825', '000826', '000828', '000831', '000852', '000868', '000869', '000929', '000930', '000931', '000932', '000933', '000935', '000936', '000937', '000938', '000948', '000949', '000950', '000951', '000952', '000953', '000955', '000957', '000958', '000959', '000960', '000961', '000962', '000963', '000965', '000966', '000967', '000968', '000969', '000970', '000971', '000972', '000973', '000975', '000976', '000977', '000978', '000980', '000981', '000982', '000983', '000985', '000987', '000988', '000989', '000990', '000993', '000996', '000997', '000998', '000999', '001696', '001914', '001965', '001979', '002001', '002002', '002003', '002004', '002005', '002006', '002007', '002008', '002009', '002010', '002011', '002012', '002013', '002014', '002015', '002016', '002017', '002019', '002020', '002021', '002022', '002023', '002024', '002025', '002026', '002027', '002028', '002029', '002030', '002031', '002032', '002033', '002034', '002035', '002036', '002037', '002038', '002039', '002040', '002041', '002042', '002043', '002044', '002045', '002046', '002047', '002048', '002049', '002050', '002051', '002052', '002053', '002054', '002055', '002056', '002057', '002058', '002059', '002060', '002061', '002062', '002063', '002064', '002065', '002066', '002067', '002068', '002069', '002071', '002072', '002073', '002074', '002075', '002076', '002077', '002078', '002079', '002080', '002081', '002082', '002083', '002084', '002085', '002086', '002087', '002088', '002089', '002090', '002091', '002092', '002093', '002094', '002095', '002096', '002097', '002098', '002099', '002100', '002101', '002102', '002103', '002104', '002105', '002106', '002107', '002108', '002109', '002110', '002111', '002112', '002113', '002114', '002115', '002116', '002117', '002118', '002119', '002120', '002121', '002122', '002123', '002124', '002125', '002126', '002127', '002128', '002129', '002130', '002131', '002132', '002133', '002134', '002135', '002136', '002137', '002138', '002139', '002140', '002141', '002142', '002144', '002145', '002146', '002147', '002148', '002149', '002150', '002151', '002152', '002153', '002154', '002155', '002156', '002157', '002158', '002159', '002160', '002161', '002162', '002163', '002164', '002165', '002166', '002167', '002168', '002169', '002170', '002171', '002172', '002173', '002174', '002175', '002176', '002177', '002178', '002179', '002180', '002181', '002182', '002183', '002184', '002185', '002186', '002187', '002188', '002189', '002190', '002191', '002192', '002193', '002194', '002195', '002196', '002197', '002198', '002199', '002200', '002201', '002202', '002203', '002204', '002205', '002206', '002207', '002208', '002209', '002210', '002211', '002212', '002213', '002214', '002215', '002216', '002217', '002218', '002219', '002221', '002222', '002223', '002224', '002225', '002226', '002227', '002228', '002229', '002230', '002231', '002232', '002233', '002234', '002235', '002236', '002237', '002238', '002239', '002240', '002241', '002242', '002243', '002244', '002245', '002246', '002247', '002248', '002249', '002250', '002251', '002252', '002253', '002254', '002255', '002256', '002258', '002259', '002260', '002261', '002262', '002263', '002264', '002265', '002266', '002267', '002268', '002269', '002270', '002271', '002272', '002273', '002274', '002275', '002276', '002277', '002278', '002279', '002280', '002281', '002282', '002283', '002284', '002285', '002286', '002287', '002288', '002289', '002290', '002291', '002292', '002293', '002294', '002295', '002296', '002297', '002298', '002299', '002300', '002301', '002302', '002303', '002304', '002305', '002306', '002307', '002308', '002309', '002310', '002311', '002312', '002313', '002314', '002315', '002316', '002317', '002318', '002319', '002320', '002321', '002322', '002323', '002324', '002325', '002326', '002327', '002328', '002329', '002330', '002331', '002332', '002333', '002334', '002335', '002336', '002337', '002338', '002339', '002340', '002341', '002342', '002343', '002344', '002345', '002346', '002347', '002348', '002349', '002350', '002351', '002352', '002353', '002354', '002355', '002356', '002357', '002358', '002359', '002360', '002361', '002362', '002363', '002364', '002365', '002366', '002367', '002368', '002369', '002370', '002371', '002372', '002373', '002374', '002375', '002376', '002377', '002378', '002379', '002380', '002381', '002382', '002383', '002384', '002385', '002386', '002387', '002388', '002389', '002390', '002391', '002392', '002393', '002394', '002395', '002396', '002397', '002398', '002399', '002400', '002401', '002402', '002403', '002404', '002405', '002406', '002407', '002408', '002409', '002410', '002411', '002412', '002413', '002414', '002415', '002416', '002419', '002420', '002421', '002440', '002471', '002488', '002517', '002518', '002519', '002520', '002521', '002573', '002622', '002671', '002710', '002720', '002776', '002790', '002791', '002792', '002793', '002795', '002807', '002881', '002882', '002883', '002884', '002885', '002937', '002938', '002939', '002956', '002957', '002958', '002973', '002975', '003036', '003037', '300014', '300017', '300024', '300030', '300031', '300032', '300033', '300066', '300072', '300106', '300166', '300167', '300168', '300169', '300170', '300194', '300195', '300196', '300197', '300198', '300201', '300211', '300212', '300213', '300214', '300215', '300406', '300435', '300470', '300471', '300472', '300521', '300522', '300523', '300540', '300546', '300547', '300548', '300549', '300550', '300555', '300562', '300582', '300587', '300604', '300615', '300616', '300617', '300618', '300619', '300666', '300667', '300668', '300669', '300670', '300671', '300672', '300673', '300674', '300680', '300698', '300713', '300715', '300716', '300717', '300718', '300719', '300720', '300721', '300722', '300723', '300724', '300725', '300726', '300727', '300728', '300729', '300730', '300733', '300735', '300736', '300737', '300738', '300757', '300864', '300930', '300931', '300932', '300933', '300936', '300937', '300938', '300939', '300940', '600059', '600150', '600171', '600180', '600293', '600295', '600297', '600298', '600299', '600311', '600496', '600536', '600597', '600598', '600599', '600600', '600601', '600681', '600697', '600728', '600729', '600730', '600734', '600764', '600809', '600831', '600833', '600834', '600835', '600857', '600858', '600861', '600887', '600900', '600916', '600958', '600970', '600975', '600976', '600977', '600993', '601000', '601012', '601099', '601162', '601206', '601231', '601233', '601236', '601238', '601258', '601518', '601567', '601600', '601608', '601668', '601857', '601858', '601865', '601866', '601880', '601886', '601888', '601890', '601928', '601963', '601990', '601999', '603003', '603006', '603037', '603040', '603063', '603067', '603069', '603076', '603095', '603099', '603110', '603115', '603116', '603128', '603129', '603136', '603155', '603157', '603161', '603168', '603169', '603177', '603178', '603189', '603212', '603226', '603266', '603278', '603297', '603300', '603301', '603302', '603303', '603313', '603319', '603320', '603329', '603335', '603338', '603351', '603421', '603486', '603506', '603557', '603578', '603598', '603602', '603603', '603605', '603606', '603607', '603608', '603618', '603655', '603700', '603703', '603707', '603708', '603713', '603733', '603738', '603739', '603766', '603777', '603778', '603786', '603833', '603867', '603878', '603882', '603883', '603886', '603889', '603896', '603920', '603936', '603939', '603958', '603960', '603967', '603977', '603982', '603983', '605055', '605100', '605118', '605179', '605183', '605258', '605266', '605303', '605318', '605337', '605358', '605368', '605388', '605398', '688002', '688005', '688012', '688019', '688022', '688023', '688029', '688033', '688050', '688051', '688055', '688057', '688065', '688078', '688085', '688089', '688090', '688093', '688096', '688101', '688108', '688111', '688126', '688127', '688133', '688135', '688139', '688156', '688158', '688165', '688166', '688185', '688188', '688196', '688229', '688233', '688258', '688277', '688286', '688299', '688300', '688301', '688308', '688309', '688312', '688318', '688330', '688335', '688336', '688338', '688350', '688357', '688360', '688365', '688379', '688386', '688466', '688488', '688513', '688519', '688520', '688521', '688566', '688567', '688568', '688569', '688571', '688577', '688578', '688579', '688580', '688585', '688586', '688588', '688589', '688590', '688595', '688596', '688598', '688599', '688600', '688607', '688608', '688617', '688618', '688628', '688656', '688658', '688668', '688669', '688678', '688679', '688680', '688686', '688687', '688688', '688689', '688698', '688699', '688777', '688788', '688819', '688981', '689009']
Traceback (most recent call last):
  File "D:\anaconda3\Scripts\quantaxis-script.py", line 33, in <module>
    sys.exit(load_entry_point('quantaxis', 'console_scripts', 'quantaxis')())
  File "d:\quantaxis\QUANTAXIS\QACmd\__init__.py", line 735, in QA_cmd
    cli.cmdloop()
  File "D:\anaconda3\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "D:\anaconda3\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "d:\quantaxis\QUANTAXIS\QACmd\__init__.py", line 381, in do_save
    QA_SU_save_stock_xdxr("tdx")
  File "d:\quantaxis\QUANTAXIS\QASU\main.py", line 528, in QA_SU_save_stock_xdxr
    engine.QA_SU_save_stock_xdxr(client=client)
  File "d:\quantaxis\QUANTAXIS\QASU\save_tdx.py", line 606, in QA_SU_save_stock_xdxr
    stock_list = QA_fetch_get_stock_list().code.unique().tolist()
  File "D:\anaconda3\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\anaconda3\lib\site-packages\retrying.py", line 212, in call
    raise attempt.get()
  File "D:\anaconda3\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\anaconda3\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "d:\quantaxis\QUANTAXIS\QAFetch\QATdx.py", line 704, in QA_fetch_get_stock_list
    with api.connect(ip, port):
AttributeError: __enter__

## 您的联系方式(QQ/EMAIL)
dislab@gmail.com

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
哦 这个是网络不大好  多试几次

**Comment by balsid** [comment]
谢谢！我重启后又跑了一遍，这次没有这个错误了。
