### ISSUE TITLE
如何生成或找到几个示例策略？

### ISSUE THREAD

**Issue by balsid** [yutiansut/QUANTAXIS#1639]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.9
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
Windows 10 Home, x64, 8G RAM

## 您的系统环境是什么?
```
- monodb 4.4
- python 3.8.5
- docker(无)
```

## 您需要反馈的问题

我刚安装了这个软件。部署文档中说：“输入examples 在当前目录下生成一个示例策略， 运行这个示例策略: python backtest.py”
我按照部署文档所说，生成了一个示例策略QADEMO，但里面没有backtest.py，也没有其他示例策略。请问在哪儿能找到几个例子试一下？谢谢！

## 您的联系方式(QQ/EMAIL)
dislab@gmail.com

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
哦 那个代码是 QADEMO的  不推荐了  现在推荐看看 QAstrategy

**Comment by balsid** [comment]
谢谢！
