### ISSUE TITLE
docker启动后找不到进入jupyter的界面

### ISSUE THREAD

**Issue by neorz** [yutiansut/QUANTAXIS#1640]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
2021-24-1拉去的最新节点的镜像

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
ubuntu 20

## 您的系统环境是什么?
```
- monodb
- python3.8
- docker(有)
```

## 您需要反馈的问题

docker启动后找不到进入jupyter的界面

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by neorz** [comment]
这个问题总算找到了答案。
现在（2021-1-24），“研究” 已经在网页界面里找不到了。 自己打开浏览器，定位到docker webserver所在地址的8888端口，然后按照下面的帖子更新数据。

https://github.com/QUANTAXIS/QUANTAXIS/issues/1630

**Comment by Lion0871** [comment]
同遇到这个问题，原因是main.min.js 404，折腾了半天，放弃了，直接新开窗口了
