### ISSUE TITLE
请问如何在局域网内使用浏览器访问webserver？

### ISSUE THREAD

**Issue by neorz** [yutiansut/QUANTAXIS#1641]
我是ubuntu本地部署。
部署完毕后可以在本地打开web server，然后访问网页。
我希望可以用常用的win的电脑访问ubuntu上部署的web server。然而在win上访问web server所在的81端口，出来登录界面后，无论点击什么按钮都没有响应。
查了一下本站，好像说到本地部署都是默认在本地访问web server的。请问向我这种情况应该如何设置？

**Comment by yutiansut** [comment]
哦哦哦  多半是 windows 浏览器的问题 换个 chrome 试一下  @neorz

**Comment by neorz** [comment]
确实如此。
问题解决了。多谢~~~~
