### ISSUE TITLE
QA_util_get_next_trade_date 功能变化

### ISSUE THREAD

**Issue by oraix** [yutiansut/QUANTAXIS#1642]
## 您使用的QUANTAXIS版本号是什么?
1.10.9

## 您需要反馈的问题
@nehcuh  @yutiansut 
commit
https://github.com/QUANTAXIS/QUANTAXIS/commit/2fe76817c66940c4ce2a8eb08eebec1108512527
这次的提交改变了原有 QA_util_get_next_trade_date的功能

## 感谢您的反馈 如有意见和建议,请在此说明:
这里参数n在更新后的代码中没有被使用, 只能简单获取下一个交易日, 而不能获得第n天后的交易日
建议QA_util_get_next_trade_date保留该能力

## 您的联系方式(QQ/EMAIL)

THANKS

**Comment by yutiansut** [comment]
fixed
