### ISSUE TITLE
启动 quantaxis_webserver 报错

### ISSUE THREAD

**Issue by nuswgg** [yutiansut/QUANTAXIS#1647]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.9
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10 64位 16G内存

## 您的系统环境是什么?
```
- monodb 4.2.6
- python 3.8
- docker(无)
```

## 感谢您的反馈 如有意见和建议,请在此说明:
启动 quantaxis_webserver 报如下错误
>quantaxis_webserver
jqdatasdk not installed
PLEASE run "pip install peakutils" to call these modules
========WELCOME QUANTAXIS_WEBSERVER============
QUANTAXIS VERSION: 1.10.9
QUANTAXIS WEBSERVER is Listening on: http://localhost:8010
请打开浏览器/使用JavaScript等来使用该后台, 并且不要关闭当前命令行窗口
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\ProgramData\Anaconda3\Scripts\quantaxis_webserver.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\QAWebServer\QA_Web.py", line 158, in main
    start_server(handlers, address, port)
  File "d:\programdata\anaconda3\lib\site-packages\QAWebServer\QA_Web.py", line 176, in start_server
    http_server.start(1)
  File "d:\programdata\anaconda3\lib\site-packages\tornado\tcpserver.py", line 222, in start
    self.add_sockets(sockets)
  File "d:\programdata\anaconda3\lib\site-packages\tornado\tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "d:\programdata\anaconda3\lib\site-packages\tornado\netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "d:\programdata\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 79, in add_handler
    self.asyncio_loop.add_reader(
  File "d:\programdata\anaconda3\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

## 您的联系方式(QQ/EMAIL)
95528736

THANKS
by eric
2021.1.28

**Comment by yutiansut** [comment]
windows下似乎有这个不兼容的问题 暂时没搞清楚是哪个模块更新了 mac和ubuntu正常 推荐docker吧

**Comment by rolandqi** [comment]
same here

```
wait_for_it.sh: waiting 15 seconds for qaeventmq:5672

wait_for_it.sh: qaeventmq:5672 is available after 6 seconds

start backend & celery

mgdb

pyamqp://admin:admin@qaeventmq:5672//

start celery

pyamqp://admin:admin@qaeventmq:5672//


-------------- celery@aee53a64c7e8 v5.0.5 (singularity)

--- ***** -----

-- ******* ---- Linux-4.19.121-linuxkit-x86_64-with-glibc2.10 2021-01-31 22:12:57

- *** --- * ---

- ** ---------- [config]

- ** ---------- .> app: quantaxis_run:0x7fece9402910

- ** ---------- .> transport: amqp://admin:**@qaeventmq:5672//

- ** ---------- .> results: rpc://

- *** --- * --- .> concurrency: 2 (prefork)

-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)

--- ***** -----

-------------- [queues]

.> default exchange=default(direct) key=default



[tasks]

. quantaxis_run.monitor_daily

. quantaxis_run.monitor_trading

. quantaxis_run.quantaxis_run

. quantaxis_run.run_shell


/opt/conda/lib/python3.8/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is

absolutely not recommended!


Please specify a different user using the --uid option.


User information: uid=0 euid=0 gid=0 egid=0


warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(

[2021-01-31 22:12:58,010: INFO/MainProcess] Connected to amqp://admin:**@qaeventmq:5672//

[2021-01-31 22:12:58,029: INFO/MainProcess] mingle: searching for neighbors

[2021-01-31 22:12:59,054: INFO/MainProcess] mingle: all alone

[2021-01-31 22:12:59,072: INFO/MainProcess] celery@aee53a64c7e8 ready.

jqdatasdk not installed

you are using non-interactive mdoel quantaxis

Traceback (most recent call last):

File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>

from QAWebServer.QA_Web import main

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>

from QAWebServer.QA_Web import main

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>

from QAWebServer.select_codehandler import SelectCodehandler

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>

class SelectCodehandler(QABaseHandler):

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler

stocklist= QA.QA_fetch_stock_list_adv()

File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv

stock_list_items = QA_fetch_stock_list(collections)

File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list

return pd.DataFrame([item for item in collections.find()]).drop(

File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop

return super().drop(

File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop

obj = obj._drop_axis(labels, axis, level=level, errors=errors)

File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis

new_axis = axis.drop(labels, errors=errors)

File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop

raise KeyError(f"{labels[mask]} not found in axis")

KeyError: "['_id'] not found in axis"
```

**Comment by yutiansut** [comment]
> same here
> 
> ```
> wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
> 
> wait_for_it.sh: qaeventmq:5672 is available after 6 seconds
> 
> start backend & celery
> 
> mgdb
> 
> pyamqp://admin:admin@qaeventmq:5672//
> 
> start celery
> 
> pyamqp://admin:admin@qaeventmq:5672//
> 
> 
> -------------- celery@aee53a64c7e8 v5.0.5 (singularity)
> 
> --- ***** -----
> 
> -- ******* ---- Linux-4.19.121-linuxkit-x86_64-with-glibc2.10 2021-01-31 22:12:57
> 
> - *** --- * ---
> 
> - ** ---------- [config]
> 
> - ** ---------- .> app: quantaxis_run:0x7fece9402910
> 
> - ** ---------- .> transport: amqp://admin:**@qaeventmq:5672//
> 
> - ** ---------- .> results: rpc://
> 
> - *** --- * --- .> concurrency: 2 (prefork)
> 
> -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
> 
> --- ***** -----
> 
> -------------- [queues]
> 
> .> default exchange=default(direct) key=default
> 
> 
> 
> [tasks]
> 
> . quantaxis_run.monitor_daily
> 
> . quantaxis_run.monitor_trading
> 
> . quantaxis_run.quantaxis_run
> 
> . quantaxis_run.run_shell
> 
> 
> /opt/conda/lib/python3.8/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
> 
> absolutely not recommended!
> 
> 
> Please specify a different user using the --uid option.
> 
> 
> User information: uid=0 euid=0 gid=0 egid=0
> 
> 
> warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
> 
> [2021-01-31 22:12:58,010: INFO/MainProcess] Connected to amqp://admin:**@qaeventmq:5672//
> 
> [2021-01-31 22:12:58,029: INFO/MainProcess] mingle: searching for neighbors
> 
> [2021-01-31 22:12:59,054: INFO/MainProcess] mingle: all alone
> 
> [2021-01-31 22:12:59,072: INFO/MainProcess] celery@aee53a64c7e8 ready.
> 
> jqdatasdk not installed
> 
> you are using non-interactive mdoel quantaxis
> 
> Traceback (most recent call last):
> 
> File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>
> 
> from QAWebServer.QA_Web import main
> 
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
> 
> from QAWebServer.QA_Web import main
> 
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
> 
> from QAWebServer.select_codehandler import SelectCodehandler
> 
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
> 
> class SelectCodehandler(QABaseHandler):
> 
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
> 
> stocklist= QA.QA_fetch_stock_list_adv()
> 
> File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
> 
> stock_list_items = QA_fetch_stock_list(collections)
> 
> File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
> 
> return pd.DataFrame([item for item in collections.find()]).drop(
> 
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
> 
> return super().drop(
> 
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
> 
> obj = obj._drop_axis(labels, axis, level=level, errors=errors)
> 
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
> 
> new_axis = axis.drop(labels, errors=errors)
> 
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
> 
> raise KeyError(f"{labels[mask]} not found in axis")
> 
> KeyError: "['_id'] not found in axis"
> ```

这是因为你没有存stock_list的数据 论坛里有文档 自己看一下吧

**Comment by rolandqi** [comment]
> > same here
> > ```
> > wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
> > 
> > wait_for_it.sh: qaeventmq:5672 is available after 6 seconds
> > 
> > start backend & celery
> > 
> > mgdb
> > 
> > pyamqp://admin:admin@qaeventmq:5672//
> > 
> > start celery
> > 
> > pyamqp://admin:admin@qaeventmq:5672//
> > 
> > 
> > -------------- celery@aee53a64c7e8 v5.0.5 (singularity)
> > 
> > --- ***** -----
> > 
> > -- ******* ---- Linux-4.19.121-linuxkit-x86_64-with-glibc2.10 2021-01-31 22:12:57
> > 
> > - *** --- * ---
> > 
> > - ** ---------- [config]
> > 
> > - ** ---------- .> app: quantaxis_run:0x7fece9402910
> > 
> > - ** ---------- .> transport: amqp://admin:**@qaeventmq:5672//
> > 
> > - ** ---------- .> results: rpc://
> > 
> > - *** --- * --- .> concurrency: 2 (prefork)
> > 
> > -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
> > 
> > --- ***** -----
> > 
> > -------------- [queues]
> > 
> > .> default exchange=default(direct) key=default
> > 
> > 
> > 
> > [tasks]
> > 
> > . quantaxis_run.monitor_daily
> > 
> > . quantaxis_run.monitor_trading
> > 
> > . quantaxis_run.quantaxis_run
> > 
> > . quantaxis_run.run_shell
> > 
> > 
> > /opt/conda/lib/python3.8/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
> > 
> > absolutely not recommended!
> > 
> > 
> > Please specify a different user using the --uid option.
> > 
> > 
> > User information: uid=0 euid=0 gid=0 egid=0
> > 
> > 
> > warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
> > 
> > [2021-01-31 22:12:58,010: INFO/MainProcess] Connected to amqp://admin:**@qaeventmq:5672//
> > 
> > [2021-01-31 22:12:58,029: INFO/MainProcess] mingle: searching for neighbors
> > 
> > [2021-01-31 22:12:59,054: INFO/MainProcess] mingle: all alone
> > 
> > [2021-01-31 22:12:59,072: INFO/MainProcess] celery@aee53a64c7e8 ready.
> > 
> > jqdatasdk not installed
> > 
> > you are using non-interactive mdoel quantaxis
> > 
> > Traceback (most recent call last):
> > 
> > File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>
> > 
> > from QAWebServer.QA_Web import main
> > 
> > File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
> > 
> > from QAWebServer.QA_Web import main
> > 
> > File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
> > 
> > from QAWebServer.select_codehandler import SelectCodehandler
> > 
> > File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
> > 
> > class SelectCodehandler(QABaseHandler):
> > 
> > File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
> > 
> > stocklist= QA.QA_fetch_stock_list_adv()
> > 
> > File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
> > 
> > stock_list_items = QA_fetch_stock_list(collections)
> > 
> > File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
> > 
> > return pd.DataFrame([item for item in collections.find()]).drop(
> > 
> > File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
> > 
> > return super().drop(
> > 
> > File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
> > 
> > obj = obj._drop_axis(labels, axis, level=level, errors=errors)
> > 
> > File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
> > 
> > new_axis = axis.drop(labels, errors=errors)
> > 
> > File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
> > 
> > raise KeyError(f"{labels[mask]} not found in axis")
> > 
> > KeyError: "['_id'] not found in axis"
> > ```
> 
> 这是因为你没有存stock_list的数据 论坛里有文档 自己看一下吧

明白了，多谢
