### ISSUE TITLE
启动docker image后

### ISSUE THREAD

**Issue by balsid** [yutiansut/QUANTAXIS#1649]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.9

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
Windows 10 Home, x64, 8G RAM

## 您的系统环境是什么?
```
- monodb 4.4
- python 3.8.5
- docker(有)
```

## 您需要反馈的问题

安装docker和QuantAxis后，在powershell里运行“docker-compose up”，看到qaweb有一些错误，如下。然后访问 http://localhost:81/，可看到登录页面，但点击“登录“后无反应。请问可能是什么问题？谢谢！
![screen1](https://user-images.githubusercontent.com/77765343/106231349-7edd1d00-61bf-11eb-8dcb-496e3da45eca.PNG)

PS D:\qa> docker-compose up
Starting qa_qaeventmq_1 ... done
Starting qa_mgdb_1      ... done
Starting qaweb            ... done
Starting qa_qatrader_1    ... done
Starting qacommunity-rust ... done
Attaching to qa_qaeventmq_1, qa_mgdb_1, qa_qatrader_1, qaweb, qacommunity-rust
qaweb        | Traceback (most recent call last):
qaweb        |   File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>
qaweb        |     from QAWebServer.QA_Web import main
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
qaweb        |     from QAWebServer.QA_Web import main
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
qaweb        |     from QAWebServer.select_codehandler import SelectCodehandler
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
qaweb        |     class SelectCodehandler(QABaseHandler):
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
qaweb        |     stocklist= QA.QA_fetch_stock_list_adv()
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
qaweb        |     stock_list_items = QA_fetch_stock_list(collections)
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
qaweb        |     return pd.DataFrame([item for item in collections.find()]).drop(
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
qaweb        |     return super().drop(
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
qaweb        |     obj = obj._drop_axis(labels, axis, level=level, errors=errors)
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
qaweb        |     new_axis = axis.drop(labels, errors=errors)
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
qaweb        |     raise KeyError(f"{labels[mask]} not found in axis")
qaweb        | KeyError: "['_id'] not found in axis"

## 您的联系方式(QQ/EMAIL)
dislab@gmail.com

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
看说明啊 .... 先去存stock_list @balsid




http://www.yutiansut.com:3000/topic/5fe1704f072fcf2c6ccb1381

**Comment by balsid** [comment]
搞好了，谢谢！第一次用docker和quantaxis，没找到正确的说明，才知道是在http://www.yutiansut.com:3000/。另外问一下，我是在windows 10 home上装了WSL2 后装的docker，还需要在docker里装ubuntu吗？似乎不用也可以运行。

**Comment by yutiansut** [comment]
@balsid 随意的 qa是微服务作为核心  你在windows上装 还是在wsl  还是在wsl里开个docker 还是直接开docker  还是局域网里的docker 或者局域网里的ubuntu 只要能提供端口号 就能提供服务

**Comment by balsid** [comment]
多谢！
