### ISSUE TITLE
docker部署失败

### ISSUE THREAD

**Issue by kelvin1757** [yutiansut/QUANTAXIS#1651]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.2

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10家庭版 64 16g

## 您的系统环境是什么?
```
- monodb 3.6.22
- python3.8
- docker(有)
```

## 您需要反馈的问题

>  qaeventmq_1  |  completed with 4 plugins.
qaweb        | [2021-02-03 16:36:28,763: INFO/MainProcess] celery@c7191b2c1fb6 ready.
qaweb        | jqdatasdk not installed
mgdb_1       | 2021-02-03T16:36:22.536+0800 I  NETWORK  [conn5] end connection 172.19.0.9:40260 (2 connections now open)
mgdb_1       | 2021-02-03T16:36:32.733+0800 I  NETWORK  [listener] connection accepted from 172.19.0.4:46230 #7 (3 connections now open)
mgdb_1       | 2021-02-03T16:36:32.742+0800 I  NETWORK  [conn7] received client metadata from 172.19.0.4:46230 conn7: { driver: { name: "PyMongo", version: "3.11.2" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.8.5.final.0" }
qaweb        | you are using non-interactive mdoel quantaxis
qaweb        | Traceback (most recent call last):
qaweb        |   File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>
qaweb        |     from QAWebServer.QA_Web import main
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
qaweb        |     from QAWebServer.QA_Web import main
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
qaweb        |     from QAWebServer.select_codehandler import SelectCodehandler
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
qaweb        |     class SelectCodehandler(QABaseHandler):
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
qaweb        |     stocklist= QA.QA_fetch_stock_list_adv()
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
qaweb        |     stock_list_items = QA_fetch_stock_list(collections)
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
qaweb        |     return pd.DataFrame([item for item in collections.find()]).drop(
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
qaweb        |     return super().drop(
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
qaweb        |     obj = obj._drop_axis(labels, axis, level=level, errors=errors)
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
qaweb        |     new_axis = axis.drop(labels, errors=errors)
qaweb        |   File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
qaweb        |     raise KeyError(f"{labels[mask]} not found in axis")
mgdb_1       | 2021-02-03T16:36:32.749+0800 I  SHARDING [conn7] Marking collection quantaxis.stock_list as collection version: <unsharded>
mgdb_1       | 2021-02-03T16:36:32.918+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40276 #8 (4 connections now open)
mgdb_1       | 2021-02-03T16:36:32.918+0800 I  NETWORK  [conn8] received client metadata from 172.19.0.9:40276 conn8: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:32.921+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40278 #9 (5 connections now open)
mgdb_1       | 2021-02-03T16:36:32.922+0800 I  NETWORK  [conn9] received client metadata from 172.19.0.9:40278 conn9: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:32.931+0800 I  NETWORK  [conn8] end connection 172.19.0.9:40276 (4 connections now open)
mgdb_1       | 2021-02-03T16:36:32.931+0800 I  NETWORK  [conn9] end connection 172.19.0.9:40278 (3 connections now open)
mgdb_1       | 2021-02-03T16:36:32.934+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40280 #10 (4 connections now open)
mgdb_1       | 2021-02-03T16:36:32.935+0800 I  NETWORK  [conn10] received client metadata from 172.19.0.9:40280 conn10: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:32.937+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40282 #11 (5 connections now open)
mgdb_1       | 2021-02-03T16:36:32.938+0800 I  NETWORK  [conn11] received client metadata from 172.19.0.9:40282 conn11: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:32.940+0800 I  NETWORK  [conn11] end connection 172.19.0.9:40282 (4 connections now open)
mgdb_1       | 2021-02-03T16:36:32.940+0800 I  NETWORK  [conn10] end connection 172.19.0.9:40280 (3 connections now open)
mgdb_1       | 2021-02-03T16:36:32.942+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40284 #12 (4 connections now open)
mgdb_1       | 2021-02-03T16:36:32.943+0800 I  NETWORK  [conn12] received client metadata from 172.19.0.9:40284 conn12: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:32.944+0800 I  SHARDING [conn12] Marking collection quantaxis.portfolio as collection version: <unsharded>
mgdb_1       | 2021-02-03T16:36:32.949+0800 I  SHARDING [conn12] Marking collection quantaxis.account as collection version: <unsharded>
mgdb_1       | 2021-02-03T16:36:32.955+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40286 #13 (5 connections now open)
mgdb_1       | 2021-02-03T16:36:32.956+0800 I  NETWORK  [conn13] received client metadata from 172.19.0.9:40286 conn13: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:32.959+0800 I  NETWORK  [listener] connection accepted from 172.19.0.9:40288 #14 (6 connections now open)
mgdb_1       | 2021-02-03T16:36:32.960+0800 I  NETWORK  [conn14] received client metadata from 172.19.0.9:40288 conn14: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.89-boot2docker" }, platform: "CPython 3.6.5.final.0" }
mgdb_1       | 2021-02-03T16:36:33.240+0800 I  NETWORK  [conn7] end connection 172.19.0.4:46230 (5 connections now open)

在docker下首次启动失败。

## 您的联系方式(QQ/EMAIL)
1011033727@qq.com

THANKS
by kelvin
2021.2.3

**Comment by yutiansut** [comment]
看下文档  存下 stock_list 即可
