### ISSUE TITLE
为什么docker搭建好进入地址ip+81端口，点击登录没反应（quantaxislogo背景是时间界面）？

### ISSUE THREAD

**Issue by kuuliao** [yutiansut/QUANTAXIS#1658]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
allin-20201222
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
centos7.3 64位，16g内存

## 您的系统环境是什么?
```docker
- monodb
- python3.7/3.8
- docker(有无)
```

## 您需要反馈的问题
为什么docker搭建好进入地址ip+81端口，点击登录没反应（quantaxislogo背景是时间界面）？

## 您的联系方式(QQ/EMAIL)

1526495886@qq.com

THANKS
by yutiansut
2017.12

**Comment by icaca** [comment]
我也是这样 应该是qaweb报错了
我在win10 ubuntu16都试了,都是一样的报错

[2021-02-13 19:21:40,424: INFO/MainProcess] Connected to amqp://admin:**@qaeventmq:5672//
[2021-02-13 19:21:40,435: INFO/MainProcess] mingle: searching for neighbors
[2021-02-13 19:21:41,463: INFO/MainProcess] mingle: all alone
[2021-02-13 19:21:41,488: INFO/MainProcess] celery@94c178ba5159 ready.
jqdatasdk not installed
you are using non-interactive mdoel quantaxis
Traceback (most recent call last):
  File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>
    from QAWebServer.QA_Web import main
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
    from QAWebServer.QA_Web import main
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
    from QAWebServer.select_codehandler import SelectCodehandler
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
    class SelectCodehandler(QABaseHandler):
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
    stocklist= QA.QA_fetch_stock_list_adv()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
    stock_list_items = QA_fetch_stock_list(collections)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
    return pd.DataFrame([item for item in collections.find()]).drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
    return super().drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"

**Comment by icaca** [comment]
https://raw.githubusercontent.com/QUANTAXIS/QUANTAXIS/578ae808a1db889ab44b9c4ff16338e1328be4cb/docker/qa-service/docker-compose.yaml

我用上一个版本安装可以运行,你试试

**Comment by yutiansut** [comment]
> 我也是这样 应该是qaweb报错了
> 我在win10 ubuntu16都试了,都是一样的报错
> 
> [2021-02-13 19:21:40,424: INFO/MainProcess] Connected to amqp://admin:**@qaeventmq:5672//
> [2021-02-13 19:21:40,435: INFO/MainProcess] mingle: searching for neighbors
> [2021-02-13 19:21:41,463: INFO/MainProcess] mingle: all alone
> [2021-02-13 19:21:41,488: INFO/MainProcess] celery@94c178ba5159 ready.
> jqdatasdk not installed
> you are using non-interactive mdoel quantaxis
> Traceback (most recent call last):
> File "/opt/conda/bin/quantaxis_webserver", line 5, in 
> from QAWebServer.QA_Web import main
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/**init**.py", line 29, in 
> from QAWebServer.QA_Web import main
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in 
> from QAWebServer.select_codehandler import SelectCodehandler
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in 
> class SelectCodehandler(QABaseHandler):
> File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
> stocklist= QA.QA_fetch_stock_list_adv()
> File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
> stock_list_items = QA_fetch_stock_list(collections)
> File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
> return pd.DataFrame([item for item in collections.find()]).drop(
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
> return super().drop(
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
> obj = obj._drop_axis(labels, axis, level=level, errors=errors)
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
> new_axis = axis.drop(labels, errors=errors)
> File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
> raise KeyError(f"{labels[mask]} not found in axis")
> KeyError: "['_id'] not found in axis"

已经说了好久好久好久的问题了 先存stock_list

**Comment by yutiansut** [comment]
为什么文档不看看呢？？？？

**Comment by icaca** [comment]
照着 https://doc.yutiansut.com/ 部署的,没看到这个呢

**Comment by yutiansut** [comment]
> 照着 https://doc.yutiansut.com/ 部署的,没看到这个呢

好吧  现在有论坛 当时这个镜像是发在论坛里的 http://www.yutiansut.com:3000/topic/5fe1704f072fcf2c6ccb1381  看下这个吧

**Comment by joeat1** [comment]
如果按照指令还不成功，则在登陆的时候需要注意页面第三个空中地址是否为 目标IP（127.0.0.1或者分配的ip）+8010 的格式，因为可能默认的 IP 不是127.0.0.1 （如在虚拟机中安装）此时需要更改，之后才能正常登录

**Comment by sobriver** [comment]
论坛的帖子没有了

**Comment by admin123-cloud** [comment]
论坛域名过期了  http://www.yutiansut.com:3000/topic/5fe1704f072fcf2c6ccb1381
哪位大神能帮忙提供下 吗
