### ISSUE TITLE
请教天神及各位老师最新的docker做qifi回测的话好像vifi可视化还是有问题看不了，只能看到历史记录

### ISSUE THREAD

**Issue by chengtao1997** [yutiansut/QUANTAXIS#1668]
# 问题反馈

请教天神及各位老师最新的docker做qifi回测的话好像vifi可视化还是有问题看不了，只能看到历史记录,是需要再手动开启什么东西吗？目前8029报错HTTP 404
如下是报错信息
#
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1569, in _execute
    result = self.prepare()
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 2322, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
#

## 您使用的QUANTAXIS版本号是什么?
quantaxis==1.10.14
qifi_account==1.14.0
qifimanager==1.2.3

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
Linux version 5.4.0-58-generic
Ubuntu 9.3.0-17ubuntu1~20.04
64位操作系统
VM虚拟机可用内存RAM==8G

## 您的系统环境是什么?

- monodb == 有（docker）
- python3.7/3.8 == 3.8
- docker(有无) ==有
- 基于VM虚拟机运行的ubuntu ，使用docker镜像

```
- monodb == Yes
- python3.7/3.8 == 3.8
- docker(有无) ==Yes
```

## 您需要反馈的问题
请教天神及各位老师最新的docker做qifi回测的话好像vifi可视化还是有问题看不了，只能看到历史记录

**Comment by yutiansut** [comment]
正常的啊

**Comment by yutiansut** [comment]
去按这个访问   http://127.0.0.1:8029/testk?code=000001&frequence=day&start=2020-09-01&end=2021-02-18&market=stock_cn&raw=true
