### ISSUE TITLE
pyecharts版本升级没有修改api调用方式导致的异常

### ISSUE THREAD

**Issue by tonglei1989** [yutiansut/QUANTAXIS#1669]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.12

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
windows10 专业版（64bit) ， 16GB内存， i5 8250u

## 您的系统环境是什么?
使用docker-desktop + docker-compose 启动服务

## 您需要反馈的问题

QA.QA_fetch_stock_day_adv('002555','2021-01-01','2021-02-22').plot() 抛出如下异常

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-be6d8046b562> in <module>
      1 import QUANTAXIS as QA
      2 
----> 3 QA.QA_fetch_stock_day_adv('002555','2021-01-01','2021-02-22').plot()

/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAData/base_datastruct.py in plot(self, code)
    782             self.if_fq
    783         )
--> 784         self.kline_echarts(code).render(path_name)
    785         webbrowser.open(path_name)
    786         QA_util_log_info(

/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAData/base_datastruct.py in kline_echarts(self, code)
    693             path_name = '.' + os.sep + 'QA_' + self.type + \
    694                 '_codepackage_' + self.if_fq + '.html'
--> 695             kline = Kline(
    696                 'CodePackage_' + self.if_fq + '_' + self.type,
    697                 width=1360,

TypeError: __init__() got an unexpected keyword argument 'width'

因为pycharts-1.9版本的api和0.5.x有差异，所以需要修改Kline、Bar等类的调用代码。比如Kline.__init__()的参数和旧版本不同，旧版本的add方法已经不存在，改为了add_axis()方法。

## 您的联系方式(QQ/EMAIL)
QQ:790059623 (在563280067群中）

THANKS
by yutiansut
2017.12

**Comment by Froid-M** [comment]
测试了下，QA.QA_fetch_stock_day_adv('002555','2021-01-01','2021-02-22').data.plot()  是正确的
不是回答对了没。

**Comment by haydengao** [comment]
网友似乎说的是QA.QA_fetch_stock_day_adv('002555','2021-01-01','2021-02-22').plot()方法出错，确实版本问题不兼容，需要修改对应的kline代码初始化，已经细节调用相关代码，才可以正确绘制k线图。
