### ISSUE TITLE
使用QA_data_marketvalue后增加了非交易日数据

### ISSUE THREAD

**Issue by well847** [yutiansut/QUANTAXIS#1671]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.11
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10（64）24G

## 您的系统环境是什么?
```
- monodb
- python3.7/
- docker(无)
```

## 您需要反馈的问题
total_list = list(QA.QA_fetch_get_stock_list('tdx'))
end_date = QA.QA_util_get_real_date(datetime.datetime.now())
df = QA.QA_fetch_stock_day_adv(total_stock_list,QA.QA_util_get_last_day(end_date,60),end_date).to_qfq().data
temp1 = df.reset_index()
temp2 = QA.QA_data_marketvalue(df).reset_index()

print(len(temp1[temp1.date == '2020-11-28']))
Out[85]: 
Empty DataFrame
Columns: [date, code, open, high, low, close, volume, amount, adj]
Index: []

print(len(temp2[temp2.date == '2020-11-28']))
Out[86]: 
            date    code  open  high  low  close  volume  amount  liquidity_mv
16259 2020-11-28  600201   NaN   NaN  NaN    NaN     NaN     NaN           NaN

 '2020-11-28'是周六，非交易日
烦请给看看，多谢！

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
nan 直接drop了呗
