### ISSUE TITLE
jupyter 保存文件时报错 '_xsrf' argument missing from POST

### ISSUE THREAD

**Issue by zhangsuzerain** [yutiansut/QUANTAXIS#1680]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有无)
```

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by barretthugh** [comment]
确保网络没问题，然后刷新浏览器
