### ISSUE TITLE
请教如何订阅TDX的商品指数

### ISSUE THREAD

**Issue by samsonsua** [yutiansut/QUANTAXIS#1684]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.18
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win 10 64位
内存 16G

## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有)
```

## 您需要反馈的问题
CTP推送的只有交易合约，没有大宗、工业品、农产品等相关商品指数，而TDX就有，那怎样才能订阅到TDX商品指数的实时推送？

## 您的联系方式(QQ/EMAIL)
417334

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
QA_fetch_get_future_day/min
