### ISSUE TITLE
股票市场误认为期货市场

### ISSUE THREAD

**Issue by zhanglianzhong** [yutiansut/QUANTAXIS#1689]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有无)
```

最新的QAStrategy ,使用样例代码qastockbase.py进行调试时发现,传进去的为stock_cn,可识别为future-cn

## 您需要反馈的问题
<img width="1037" alt="截屏2021-04-18 上午11 29 41" src="https://user-images.githubusercontent.com/42383433/115136960-cef8ac80-a055-11eb-92c5-df92e61130f9.png">
<img width="520" alt="截屏2021-04-18 上午11 30 03" src="https://user-images.githubusercontent.com/42383433/115136965-d8821480-a055-11eb-89e3-fa48e6a384a6.png">
<img width="972" alt="截屏2021-04-18 上午11 30 36" src="https://user-images.githubusercontent.com/42383433/115136975-e46dd680-a055-11eb-93d1-7e038767bdb1.png">

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by sunshe35** [comment]
我之前遇到过，是因为你的策略id(strategy_id)在之前用期货跑过，它读取的是数据库的缓存。
你新建一个策略id或者在数据库删除原来的id就ok了。
