### ISSUE TITLE
QA.QA_fetch_stock_day_adv('000001','2017-01-01','2017-10-01') 获取不到数据

### ISSUE THREAD

**Issue by holdonbaby** [yutiansut/QUANTAXIS#1691]
# 问题反馈
QA.QA_fetch_stock_day_adv('000300','2021-04-16','2021-04-18')
QA Error QA_fetch_stock_day_adv parameter code=000300 , start=2021-04-16, end=2021-04-18 call QA_fetch_stock_day return None
获取不到数据

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
最新

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10 64  16G

## 您的系统环境是什么?
```
- monodb
- python3.8
- docker(有)
```

## 您的联系方式(QQ/EMAIL)
QQ:495921109

THANKS
by yutiansut
2017.12

**Comment by nehcuh** [comment]
这个是本地获取数据的接口，首先需要你保存数据到本地，如果是docker内的话，打开docker内的terminal，然后进入bash环境，输入 quantaxis，之后 save x

**Comment by holdonbaby** [comment]
谢谢！
