### ISSUE TITLE
QA_fetch系列借口并发优化

### ISSUE THREAD

**Issue by labbbirder** [yutiansut/QUANTAXIS#1695]
你好，我的伙计。
我注意到当我调用QA_fetch系列接口时，我的多核CPU只有一个处于忙碌状态，其余的CPU是闲置的。
我想知道如果我能并发地加载证券数据，使多核CPU和磁盘IO得到最大化的利用。

**Comment by yutiansut** [comment]
QA_fetch 更推荐的是从本地数据库获取数据 因此也没必要这么做
