### ISSUE TITLE
Windows安装问题

### ISSUE THREAD

**Issue by FeverCombo3** [yutiansut/QUANTAXIS#170]
在执行到pip install -e . 的时候会提示报错
error :package directory 'QUANTIXIS\Data\proto' does not exit
手动添加了这个目录后不会报错了，但继续执行在输入quantixas初始化数据时又会报错
No module named 'QUANTIXIS.QAData.proto'

**Comment by yutiansut** [comment]
不好意思...少打了几个东西..  应该是QAData\proto

**Comment by yutiansut** [comment]
已经修改 https://github.com/yutiansut/QUANTAXIS/pull/171
