### ISSUE TITLE
save_tdx.QA_SU_save_stock_block exception!

### ISSUE THREAD

**Issue by theone-pang** [yutiansut/QUANTAXIS#1712]
# 问题反馈

安装方式 pip install quantaxis
version:  1.10.19
window10 环境 python3.6 无docker

QUANTAXIS>> tdx Block ====
HTTP Error 403: Forbidden
QUANTAXIS>> 'NoneType' object has no attribute 'columns'
Error save_tdx.QA_SU_save_stock_block exception!

**Comment by LionZhang2020** [comment]
Same issue!

**Comment by LionZhang2020** [comment]
好像是tdx API  授权有问题。

QUANTAXIS> save stock_block
QUANTAXIS>> ##JOB09 Now Saving STOCK_BlOCK ====
QUANTAXIS>> tdx Block ====
HTTP Error 403: Forbidden
QUANTAXIS>> 'NoneType' object has no attribute 'columns'
 Error save_tdx.QA_SU_save_stock_block exception!

**Comment by anno189** [comment]
Same issue!

**Comment by iStar-s** [comment]
板块更新好了，只是里面多了用tushare更新板块的代码，你先检查一下数据库，如果存在板块数据忽略就行了
