### ISSUE TITLE
get_account调用错误

### ISSUE THREAD

**Issue by zhongweidai** [yutiansut/QUANTAXIS#1713]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么? 

**1.10.19**

## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有无)
```

## 您需要反馈的问题

**QAUser文件的419行的调用get_account错误，应调用get_account_by_cookie方法**

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
本模块已经移除
