### ISSUE TITLE
可否指导下QUANTAXIS修改源码后的本地安装

### ISSUE THREAD

**Issue by zhanglianzhong** [yutiansut/QUANTAXIS#1718]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您的系统环境是什么?
```
- monodb
- python3.8
- docker有
```

## 您需要反馈的问题
 想对QUANTAXIS进行改造,以适配数字货币的量化交易.修改了QUANTAXIS的部分源码后,进入QUANTAXIS目录,执行python setup.py install命令. 显示安装成功

<img width="544" alt="截屏2021-07-24 下午5 48 50" src="https://user-images.githubusercontent.com/42383433/126864859-d5effa94-5239-4504-8574-774dc26ccd12.png">

但执行命令 查看当前版本 却依然是旧的版本
<img width="708" alt="截屏2021-07-24 下午5 50 16" src="https://user-images.githubusercontent.com/42383433/126864884-64fe1792-aa3c-4b12-8a73-7583385ec0ca.png">

## 您的联系方式(QQ/EMAIL)

QQ:1353810395

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
```pip install -e  . ```
