### ISSUE TITLE
建议： 有多处使用了 MongoClient(mongo_ip)，对非本地安装的mongodb不友好，建议改成 uri

### ISSUE THREAD

**Issue by kent119** [yutiansut/QUANTAXIS#1738]
![image](https://user-images.githubusercontent.com/18453664/143978302-e7d96a30-d0ce-4a58-b3b9-47d3c2a195f4.png)

如图所示，有多处使用了 `pymongo.MongoClient(mongo_ip)`，对非本地安装或有用户名密码的 MongoDB 很不友好，建议改成 uri。

**Comment by yutiansut** [comment]
mongoip同时也可以就是uri
