### ISSUE TITLE
使用docker，出现问题-- 无法保存 --2021-11-30

### ISSUE THREAD

**Issue by suzhouclark** [yutiansut/QUANTAXIS#1739]
按照这个官方指南
[https://github.com/QUANTAXIS/QUANTAXIS/tree/master/docker](url)
和这个民间指南
[https://www.cnblogs.com/sunshe35/p/14694275.html](url)

运行
`save stock_list`
出现这个问题
`saving ip list to future cache 5`
`QUANTAXIS>> === The BEST SERVER ===`
 `stock_ip 60.12.136.250 future_ip 106.14.95.149`
`QUANTAXIS>> cannot handle a non-unique multi-index!`
 `Error save_tdx.QA_SU_save_stock_list exception!`
`QUANTAXIS> `

系统版本
`daocloud.io/quantaxis/qaeventmq             latest           b166b6189252   9 months ago    187MB`
`daocloud.io/quantaxis/qacommunity-rust-go   allin-20210218   f423729e137c   9 months ago    6.97GB`
`daocloud.io/quantaxis/qamongo_single        latest           d6b743c2f710   22 months ago   386MB`
`daocloud.io/quantaxis/qatrader              latest           632ed71d743d   2 years ago     1.63GB`

**Comment by yichang99** [comment]
me too

**Comment by yutiansut** [comment]
更新群文件里的pytdx版本

**Comment by suzhouclark** [comment]
登录QQ群,下载两个文件,考入docker，注意，找自己对应的DOCKER id
`docker cp /home/xxx/pytdx-1.72r2-py3-none  f423729e137c:/usr/local/pytdx-1.72r2-py3-none-any.whl`
`docker cp /home/xxx/quantaxis-1.10.19r1-py3-none-any.whl  f423729e137c:/usr/local/quantaxis-1.10.19r1-py3-none-any.whl`

在主机上运行  
`sudo docker exec -it f423729e137c /bin/bash`

安装刚拷贝进去的 whl
`root@f423729e137c:/usr/local# pip install pytdx-1.72r2-py3-none-any.whl`
`root@f423729e137c:/usr/local# pip install quantaxis-1.10.19r1-py3-none-any.whl`

可以运行 民间指南中的两个 save命令

**Comment by kevin-meng** [comment]
> 登录QQ群,下载两个文件,考入docker，注意，找自己对应的DOCKER id `docker cp /home/xxx/pytdx-1.72r2-py3-none f423729e137c:/usr/local/pytdx-1.72r2-py3-none-any.whl` `docker cp /home/xxx/quantaxis-1.10.19r1-py3-none-any.whl f423729e137c:/usr/local/quantaxis-1.10.19r1-py3-none-any.whl`
> 
> 在主机上运行 `sudo docker exec -it f423729e137c /bin/bash`
> 
> 安装刚拷贝进去的 whl `root@f423729e137c:/usr/local# pip install pytdx-1.72r2-py3-none-any.whl` `root@f423729e137c:/usr/local# pip install quantaxis-1.10.19r1-py3-none-any.whl`
> 
> 可以运行 民间指南中的两个 save命令

可否邮箱分享下这两个包, qq群加不上
meng_fr595@163.com
感谢!

**Comment by yichang99** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： Kevin Meng ***@***.***>日期： 2021年12月18日周六 01:54收件人： QUANTAXIS/QUANTAXIS ***@***.***>抄送： reg64 ***@***.***>, Comment ***@***.***>主    题： Re: [QUANTAXIS/QUANTAXIS] 使用docker，出现问题-- 无法保存 --2021-11-30 (Issue #1739)



登录QQ群,下载两个文件,考入docker，注意，找自己对应的DOCKER id docker cp /home/xxx/pytdx-1.72r2-py3-none f423729e137c:/usr/local/pytdx-1.72r2-py3-none-any.whl docker cp /home/xxx/quantaxis-1.10.19r1-py3-none-any.whl f423729e137c:/usr/local/quantaxis-1.10.19r1-py3-none-any.whl

在主机上运行 sudo docker exec -it f423729e137c /bin/bash

安装刚拷贝进去的 whl ***@***.***:/usr/local# pip install pytdx-1.72r2-py3-none-any.whl ***@***.***:/usr/local# pip install quantaxis-1.10.19r1-py3-none-any.whl

可以运行 民间指南中的两个 save命令



可否邮箱分享下这两个包, qq群加不上

***@***.***

感谢!

**Comment by YokisChen** [comment]
我也遇到了相同的问题，能否邮箱分享一下这两个包，多谢~ 826843767@qq.com

**Comment by yichang99** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： YokisChen ***@***.***>日期： 2022年1月17日周一 13:45收件人： QUANTAXIS/QUANTAXIS ***@***.***>抄送： reg64 ***@***.***>, Comment ***@***.***>主    题： Re: [QUANTAXIS/QUANTAXIS] 使用docker，出现问题-- 无法保存 --2021-11-30 (Issue #1739)

我也遇到了相同的问题，能否邮箱分享一下这两个包，多谢~ ***@***.***

**Comment by JerryYao80** [comment]
> 更新群文件里的pytdx版本

不知道 https://pypi.org/ 上两个对应的whl文件是否也行呢？
另外，操作的是哪一个镜像的容器？

**Comment by xjtukanif** [comment]
> 

这个两个文件麻烦放到git吧，感谢

**Comment by kevin-meng** [comment]
两个所需的安装包
pytdx-1.72r2-py3-none-any.whl
quantaxis-1.10.19r1-py3-none-any.whl

链接: https://pan.baidu.com/s/1QzPwzlyKoKcR9UUGu01Njw?pwd=jzng 提取码: jzng

**Comment by cncowboy** [comment]
> 两个所需的安装包 pytdx-1.72r2-py3-none-any.whl quantaxis-1.10.19r1-py3-none-any.whl
> 
> 链接: https://pan.baidu.com/s/1QzPwzlyKoKcR9UUGu01Njw?pwd=jzng 提取码: jzng

感谢感谢，不过，安装后，还是报错：Error save_tdx.QA_SU_save_stock_list exception

**Comment by BaskDuan** [comment]
> > 两个所需的安装包 pytdx-1.72r2-py3-none-any.whl quantaxis-1.10.19r1-py3-none-any.whl
> > 链接: https://pan.baidu.com/s/1QzPwzlyKoKcR9UUGu01Njw?pwd=jzng 提取码: jzng
> 
> 感谢感谢，不过，安装后，还是报错：Error save_tdx.QA_SU_save_stock_list exception

试下这个，在docker 的 localhost:8888 中的 terminal 的 bash下 输入以下命令


`wget https://github.com/DuanTzXavier/quantaxis-file/raw/main/quantaxis-1.10.19r1-py3-none-any.whl`
`pip install pytdx-1.72r2-py3-none-any.whl`


`wget https://github.com/DuanTzXavier/quantaxis-file/raw/main/pytdx-1.72r2-py3-none-any.whl`
`pip install quantaxis-1.10.19r1-py3-none-any.whl`
