### ISSUE TITLE
使用docker，出现问题-- 无法登录网页 --2021-12-01

### ISSUE THREAD

**Issue by suzhouclark** [yutiansut/QUANTAXIS#1741]
按照这个官方指南
[https://github.com/QUANTAXIS/QUANTAXIS/tree/master/docker](url)
和这个民间指南
[https://www.cnblogs.com/sunshe35/p/14694275.html](url)

运行完两个 save 命令后，登录 81端口网页，按登录无反应。
![q](https://user-images.githubusercontent.com/3823093/144168975-f34e4afd-d20e-4a03-be40-fcf27302cbcd.png)

系统版本
`daocloud.io/quantaxis/qaeventmq             latest           b166b6189252   9 months ago    187MB`
`daocloud.io/quantaxis/qacommunity-rust-go   allin-20210218   f423729e137c   9 months ago    6.97GB`
`daocloud.io/quantaxis/qamongo_single        latest           d6b743c2f710   22 months ago   386MB`
`daocloud.io/quantaxis/qatrader              latest           632ed71d743d   2 years ago     1.63GB`

**Comment by yutiansut** [comment]
重启一下docker即可

**Comment by suzhouclark** [comment]
好了。
