### ISSUE TITLE
docker目录qa-community-rust中，entrypoiny.sh文件名错误，正确应该是entrypoint.sh

### ISSUE THREAD

**Issue by wxj0916** [yutiansut/QUANTAXIS#1748]
https://github.com/QUANTAXIS/QUANTAXIS/tree/master/docker/qa-community-rust中，entrypoiny.sh文件名与Dockerfile文件中的对应的copy指令行文件名entrypoint.sh不符，会导致build镜像报错

**Comment by yutiansut** [comment]
fixed
