### ISSUE TITLE
您好，我想问一下问什么获取到的数据只更新到2021-12-31

### ISSUE THREAD

**Issue by Zavianx** [yutiansut/QUANTAXIS#1802]
代码中trade_date_sse已经更新到最新日期了，但是获取数据时还是只能到2021-12-31

**Comment by yutiansut** [comment]
2.0dev还是1.x的

**Comment by Zavianx** [comment]
找到问题了，发现docker里面文件是旧的，已经修改成功。还有一个问题请问您，如果想使用2.0dev该怎么部署



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vincent ***@***.***&gt;; 
发送时间: 2022年6月21日(星期二) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [QUANTAXIS/QUANTAXIS] 您好，我想问一下问什么获取到的数据只更新到2021-12-31 (Issue #1802)





 
2.0dev还是1.x的

**Comment by yutiansut** [comment]
2.0dev 主要是基于clickhouse的数据源的 docker先拉ck的数据库 然后我给了个rq/jq类的存储协议 2.0就不怎么用mongodb了
