### ISSUE TITLE
使用docker pull 时报网络错误

### ISSUE THREAD

**Issue by hxl123789** [yutiansut/QUANTAXIS#1813]

**Comment by hxl123789** [comment]
![image](https://user-images.githubusercontent.com/2535778/197547493-ef4317c8-2a0b-481b-a272-70555e394aa9.png)
[root@VM-20-5-centos quantaxis_docker]# docker-compose up
Pulling mgdb (daocloud.io/quantaxis/qamongo_single:latest)...
ERROR: Head "https://daocloud.io/v2/quantaxis/qamongo_single/manifests/latest": Get "https://daohub-auth.daocloud.io/auth?scope=repository%3Aquantaxis%2Fqamongo_single%3Apull&service=daocloud.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by QingYong** [comment]
可以换源到 image: cdy1263/xxx:latest

**Comment by hxl123789** [comment]
已解决
