### ISSUE TITLE
股票分钟回测和指数分钟回测问题

### ISSUE THREAD

**Issue by shenxingbei** [yutiansut/QUANTAXIS#188]
f24b600046987f1c3c66e883741aed6383f5b820更新后，股票分钟回测会报错。
**1.** 在CLI中生成默认backtest.py，将QB.backtest_type改为‘60min’以后，回测会出现如下错误：
![image](https://user-images.githubusercontent.com/24872944/30805808-b6ed2f6c-a225-11e7-8847-243446d2bfe6.png)

**2.**指数日线回测时，在strategy()函数中调用QB.QA_backtest_get_market_data(QB, code, QB.today)，可以返回当前交易日前gap个日线bar数据。**但是在指数分钟回测时**，调用QB.QA_backtest_get_market_data(QB, code, QB.now) 却只能返回当天开盘到QB.now时刻的分钟bar数据，比如15min回测，那么回测第一次调用strategy()的时间是09:45，QA_backtest_get_market_data返回开盘后1个bar，回测第二次调用strategy()的时间是10:30，QA_backtest_get_market_data返回2个bar，直到调用了gap次之后，每次返回的都是gap个bar，但数据的内容却没在更新，始终是从回测首日开盘后的gap个bar。
![image](https://user-images.githubusercontent.com/24872944/30806375-207cf51e-a228-11e7-87af-de67e4c78f2f.png)

**Comment by shenxingbei** [comment]
关于第1个问题，30min也不行，只有15min及以下的分钟回测可以正常运行。

**Comment by yutiansut** [comment]
是的 下午临走的时候我也发现了 早上折腾日线的时候没注意...

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/pull/193

https://github.com/yutiansut/QUANTAXIS/pull/191
