### ISSUE TITLE
QA将2021年5月4日和5月5日设置成交易日了

### ISSUE THREAD

**Issue by yinxiuqu** [yutiansut/QUANTAXIS#204]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.18
## 您的系统环境是什么?
```
- monodb
- python3.8
- docker(无)
```

## 您需要反馈的问题

QA将2021年5月4日和5月5日设置成交易日了

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
fixed
