### ISSUE TITLE
在安装TA-Lib之前，需要安装Numpy

### ISSUE THREAD

**Issue by xiaobitao** [yutiansut/QUANTAXIS#221]
在安装TA-Lib之前，需要安装Numpy

> sudo apt-get update
sudo apt-get install python3.6-dev
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar -xzvf ta-lib-0.4.0-src.tar.gz
cd ta-lib
./configure --prefix=/usr
make
sudo make install
cd ..
pip install TA-Lib

**Comment by yutiansut** [comment]
(⊙o⊙)哦! 这样...我写的时候 已经有numpy了 没注意

**Comment by yutiansut** [comment]
@xiaobitao  https://github.com/yutiansut/QUANTAXIS/commit/0506846cb3e25f430d8097a50d4204de2c0d554c  在这个commit已经更新

**Comment by xiaobitao** [comment]
@yutiansut 效率真高啊

**Comment by fenggui321** [comment]
这里必须下源代码编一次么？我感觉pip install ta-lib就可以了的样子

**Comment by yutiansut** [comment]
@fenggui321 如果你装起来就不用再装了
