### ISSUE TITLE
save的时候出错了

### ISSUE THREAD

**Issue by haohello** [yutiansut/QUANTAXIS#256]
QUANTAXIS>> DOWNLOAD PROGRESS 99.9 %
QUANTAXIS>> ##JOB02 Now Saving XDXR INFO ==== 000155
QUANTAXIS>> ERROR CODE 
 
QUANTAXIS>> []
/home/ubuntu/projects/QUANTAXIS/QUANTAXIS/QAFetch/QATdx.py:317: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  return pd.concat([data[data['sse'] == 'sz'][data.assign(code=data['code'].apply(lambda x: int(x)))['code'] // 1000 >= 399],
/home/ubuntu/projects/QUANTAXIS/QUANTAXIS/QAFetch/QATdx.py:318: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['sse'] == 'sh'][data.assign(code=data['code'].apply(lambda x: int(x)))['code'] // 1000 == 0]]) \
QUANTAXIS>> The 0 of Total 581
QUANTAXIS>> DOWNLOAD PROGRESS 0.0 %
QUANTAXIS>> ##JOB04 Now Saving INDEX_DAY====

**Comment by yutiansut** [comment]
没有出错 warning而已 @haohello

**Comment by yssource** [comment]
`QA_util_log_info('ERROR CODE \n ')`
为啥代码中留下这样的log, 即使正确下载完数据?

`QUANTAXIS>> ERROR CODE`
很容易让人误解

**Comment by yutiansut** [comment]
这个是 如果有错就会append 不然就是空的
