### ISSUE TITLE
关于to_qhq的优化建议

### ISSUE THREAD

**Issue by hadrianl** [yutiansut/QUANTAXIS#265]
目前to_qhq里面包含了比较多的拆分计算合并。所以dataframe里的索引，concat，还有除权数据的查询次数都较多。
核心部分可以尝试用self.data=self.data.groupby('code').apply(qhq_func,args=(xdxr_data,))来达到分拆处理合并的作用。

另外，关于整个框架的优化，可能索引方面要区分使用各种索引方法，因为里面涉及的dataframe索引太多了，各种索引方法的性能差别还是挺大的。根据经验以下使用优先级由高到低：
df.iat，df.iloc，df.loc, df[n:m], df['label'], df.ix[], df[][]

**Comment by yutiansut** [comment]
咦 可以这样?  我试试

**Comment by yutiansut** [comment]
我明天搞吧  数据库还没更新好

**Comment by yutiansut** [comment]
索引已经更新  groupby暂时用在min的复权上
