### ISSUE TITLE
无法创建examples

### ISSUE THREAD

**Issue by doskoi** [yutiansut/QUANTAXIS#270]
QUANTAXIS> examples
Traceback (most recent call last):
  File "/root/anaconda3/bin/quantaxis", line 11, in <module>
    load_entry_point('quantaxis', 'console_scripts', 'quantaxis')()
  File "/root/quantaxis/QUANTAXIS/QACmd/__init__.py", line 223, in QA_cmd
    cli.cmdloop()
  File "/root/anaconda3/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/root/anaconda3/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: do_examples() got an unexpected keyword argument 'e'

Env:
debian:/strategy# pip -V
pip 9.0.1 from /root/anaconda3/lib/python3.6/site-packages (python 3.6)
debian:/strategy# python -V
Python 3.6.2 :: Anaconda, Inc.

python等环境还试过升级，之前是3.0
也试过重新安装QUANTAXIS

**Comment by yutiansut** [comment]
click装坏了？

**Comment by doskoi** [comment]
试了一下重装click, 依旧这个错

**Comment by yutiansut** [comment]
quantaxis版本号告知一下

**Comment by doskoi** [comment]
git pull 最新的，不是quantaxis的问题的话，就关了issue吧，我找时间重做下那个机器。

**Comment by yutiansut** [comment]
我感觉不是最新的 我是说你的版本  你这个出错原因很像之前的一个版本的东西

```python
    #@click.command()
    #@click.option('--e', default=1, help='Number of greetings.')
    def do_examples(self, arg):
        QA_util_log_info('QUANTAXIS example')
        now_path = os.getcwd()
        project_dir = os.path.dirname(os.path.abspath(__file__))
        file_dir = ''

        if platform.system() == 'Windows':
```

你出错附近的代码是这样的 ,当初我想用click去改写命令行模式的,然后我就写了个click option.
后来我发现click有点坑 代码我就注释掉了  但是这个click option里面有个 -e的参数

而你的错误里面
```
TypeError: do_examples() got an unexpected keyword argument 'e'
```
有一个e的参数, 出错了  所以我估计你的代码版本是我之前的版本的

你看下你的代码版本  @doskoi

**Comment by yutiansut** [comment]
@doskoi  如果没有错 你的版本应该是'0.5.6'   但是我估计你的版本不是这个

**Comment by yutiansut** [comment]
@doskoi  我看了你的github  你fork的代码是28天前的代码 比我代码落后了209个commit  你更新一下你的github吧  https://github.com/doskoi/QUANTAXIS

**Comment by doskoi** [comment]
谢谢，但是我check了下，出问题的机器的git remote就是你的repo地址。

**Comment by yutiansut** [comment]
你告诉我版本号啊.......

**Comment by yutiansut** [comment]
你找个命令行输入quantaxis 就有版本号了

```
λ  quantaxis
QUANTAXIS>> start QUANTAXIS
QUANTAXIS>> ip:127.0.0.1   port:27017
QUANTAXIS>> Selecting the Best Server IP of TDX
QUANTAXIS>> ===The BEST SERVER is :  218.75.126.9 ===
QUANTAXIS>> Welcome to QUANTAXIS, the Version is 0.5.6
QUANTAXIS>>
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``########`````##````````##``````````##`````````####````````##```##########````````#``````##``````###```##`````######``
  `##``````## ```##````````##`````````####````````##`##```````##```````##```````````###``````##````##`````##```##`````##`
  ##````````##```##````````##````````##`##````````##``##``````##```````##``````````####```````#```##``````##```##``````##
  ##````````##```##````````##```````##```##```````##```##`````##```````##`````````##`##```````##`##```````##````##```````
  ##````````##```##````````##``````##`````##``````##````##````##```````##````````##``###```````###````````##`````##``````
  ##````````##```##````````##``````##``````##`````##`````##```##```````##```````##````##```````###````````##``````###````
  ##````````##```##````````##`````##````````##````##``````##``##```````##``````##``````##`````##`##```````##````````##```
  ##````````##```##````````##````#############````##```````##`##```````##`````###########`````##``##``````##`````````##``
  ###```````##```##````````##```##```````````##```##```````##`##```````##````##`````````##```##```##``````##```##`````##`
  `##``````###````##``````###``##`````````````##``##````````####```````##```##``````````##``###````##`````##````##`````##
  ``#########``````########```##``````````````###`##``````````##```````##``##````````````##`##``````##````##`````##````##
  ````````#####`````````````````````````````````````````````````````````````````````````````````````````````````````####`
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``````````````````````````Copyright``yutiansut``2017``````QUANTITATIVE FINANCIAL FRAMEWORK`````````````````````````````
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

QUANTAXIS>


```

**Comment by doskoi** [comment]
0.5.0，又重新pull了下，重新装了次，这次好了，谢谢。

**Comment by yutiansut** [comment]
@doskoi  这就对了  0.5.0就是200多个commit以前 东西

**Comment by doskoi** [comment]
嗯，问问目前项目支持自动更新数据吗，save只能在quantaxis命令下执行，quantaxis好像不支持启动参数。
所以没法写在cronjob里。

**Comment by yutiansut** [comment]
哦 你可以执行函数...

**Comment by yutiansut** [comment]
突然想起一件可怕的事情...你是不是存储代码...是0.5.0的版本的.....

**Comment by doskoi** [comment]
啊，什么可怕？那个机器就3周前clone了下，今天中午pull过，记得看见pull结果里文件改动的内容了。不知道为什么没成功，刚才又pull了次重装就好了。

**Comment by yutiansut** [comment]
因为我改过一次数据库索引结构 你之后的save 第一次会非常漫长 因为要重做索引
