### ISSUE TITLE
说明文档

### ISSUE THREAD

**Issue by njuxiaoxs** [yutiansut/QUANTAXIS#30]
你好，我对这个系统非常感兴趣，想尝试使用，但是按照README中的说明遇到很多问题，请问你们是否有详细的说明文档？

**Comment by yutiansut** [comment]
是的，版本还不稳定，一些细节的函数名还在变化，目前RC快要完成了，要不等两天？ 我这周日前 把完整的[Protocol](https://github.com/yutiansut/QUANTAXIS/tree/0.3.8-dev-RC-ARP/QUANTAXISProtocol) 放出来
#28

**Comment by yutiansut** [comment]
目前正在测试自动生成的策略示例，如果顺利，会写好标准的Backtest_example

**Comment by better319** [comment]
求傻瓜版本的入门教程

**Comment by johnsonchak** [comment]
傻瓜入门教程...即将开始...

**Comment by better319** [comment]
你的教程呢，你是不是偷懒了

**Comment by yutiansut** [comment]
TAT 泪汪汪  最近忙着做webkit这块 天地良心我绝对没有偷懒QAAQ

**Comment by yutiansut** [comment]
现在支持一键部署了,你可以看下readme @njuxiaoxs @better319
