### ISSUE TITLE
回测中股票池处理问题

### ISSUE THREAD

**Issue by longilacus** [yutiansut/QUANTAXIS#300]
QA目前是QB.strategy_stock_list里的股票一次能够加载到内存，但是策略里可能会因为财务数据或者技术指标二次筛选股票池，这样就可能存在for item in QB.strategy_stock_list 和for item in smaller_list多个for循环问题，导致速度变慢，希望能针对多重逻辑循环选股进行优化。

**Comment by yutiansut** [comment]
现在已经设置了外部的数据源 通过设置 
```
QB.outside_data=(QADATASTRUCT)
```
即可加载外部数据
