### ISSUE TITLE
QB.strategy_stock_list反馈

### ISSUE THREAD

**Issue by longilacus** [yutiansut/QUANTAXIS#302]
由于回测中可能经常使用板块作为股票池  建议封装一个简化的函数等价于QA.QA_fetch_stock_block_adv().get_block('沪深300').code

**Comment by yutiansut** [comment]
0.5.18 新增 QA_backtest_get_block()

examples
QB.strategy_stock_list=QB.QA_backtest_get_block(QB,['昨日涨停','钢铁'])

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/pull/305
