### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by JaysonAlbert** [yutiansut/QUANTAXIS#310]
get_history_transaction一次性可以拿2000个数据
你那样的写法很简练，但是如果直接把800改成2000，会进行冗余的请求，所以我按照下面这种写法来做。
 https://github.com/JaysonAlbert/tdx/blob/83747446720152b07cf4a6c59916e80fc36fcba4/tdx/engine.py#L219

**Comment by yutiansut** [comment]
已经更新 https://github.com/yutiansut/QUANTAXIS/pull/331
