### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhy0313** [yutiansut/QUANTAXIS#32]
\web\node_modules\quantaxiswebkit\client\app\src\renderer\main.js Unexpected token (47:2
 You may need an appropriate loader to handle this file type.
 | new Vue({
 |   router,
 |   ...App
 | }).$mount('#app')
 |
  @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js

**Comment by yutiansut** [comment]
npm install 装了吗

**Comment by zhy0313** [comment]
装了 D:\zhy\ceshi\QUANTAXIS\web\node_modules\quantaxiswebkit>npm version
{ quantaxiswebkit: '0.3.8-dev-alphapackage',
  npm: '4.3.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

**Comment by zhy0313** [comment]
您那用的npm版本是？

**Comment by yutiansut** [comment]
我是说 模块都安装了吗

**Comment by yutiansut** [comment]
因为是三个模块  (后台/前端/客户端),我写了一个集成的 直接用npm run install可以装所有的  linux下可能要sudo

**Comment by zhy0313** [comment]
都安装了 菜单那个界面能看到

**Comment by yutiansut** [comment]
你在webkit目录下 npm run Xweb试试?

**Comment by zhy0313** [comment]
npm run Xclient  是这个报错  npm run Xweb是正常的

**Comment by yutiansut** [comment]
你先用web把

**Comment by yutiansut** [comment]
你的nodejs 版本是不是低于7?
