### ISSUE TITLE
backtest.py 初始化失败

### ISSUE THREAD

**Issue by yssource** [yutiansut/QUANTAXIS#366]
* Reproduce:
  - 下载最新数据 save all
  - block 数据不含有 '钢铁', [backtest.py](https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QACmd/backtest.py#L104)

* Result:
  - `QB.strategy_stock_list` 为 空值, backtest.py 初始化失败

**Comment by yutiansut** [comment]
是的  你没有save stock_block吧 @yssource

**Comment by yutiansut** [comment]
先对项目 ```git pull ```更新  然后在quantaxis cli命令行中输入 ```save stock_block```

**Comment by yutiansut** [comment]
@yssource

**Comment by yssource** [comment]
你应该是有旧的数据残留吧. 我是最新建的DB, 也执行了 save stock_block

![screenshot from 2017-12-05 20-00-46](https://user-images.githubusercontent.com/3756334/33606135-5d70cf70-d9f7-11e7-8f32-d913e6409c41.png)

![screenshot from 2017-12-05 20-00-14](https://user-images.githubusercontent.com/3756334/33606136-5db1437a-d9f7-11e7-8190-f56051183ebc.png)

**Comment by yutiansut** [comment]
是这样的 这几天同花顺爬虫呗封了 已经更新了新版本 防封的 所以说需要git pull

**Comment by yutiansut** [comment]
@yssource

**Comment by yssource** [comment]
1. 我已经 git pull 最新的了, 估计我这里爬虫又被block掉了.
2. 提供一点我的想法, 防block
   独立出一个 util 文件, agents.py
    a.  agents.py

```
   AGENTS = [
            "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.0 Safari/532.5",
            "Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.310.0 Safari/532.9",
            "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.514.0 Safari/534.7",
            "Mozilla/3.01Gold (Win95; I)",
            "Mozilla/4.8 [en] (Windows NT 5.1; U)",
            "Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.4) Gecko Netscape/7.1 (ax)",
            "Opera/7.50 (Windows XP; U)",
            "Opera/7.50 (Windows ME; U) [en]",
            "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/534.14 (KHTML, like Gecko) Chrome/9.0.601.0 Safari/534.14",
            # ... 更多的 agents
   ]

```
   
     b. main.py

```
  from agents import AGENTS

  agent = random.choice(AGENTS)
  request.headers['User-Agent'] = agent

```

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QAThs.py#L63
在这里做了headers的处理 早上是亲测可行的 

你可以在ipython里执行一下 QA.QA_fetch_get_stock_block('ths')来看下结果

**Comment by yssource** [comment]
1. 版本是新的
![screenshot from 2017-12-05 20-48-59](https://user-images.githubusercontent.com/3756334/33607972-cceca170-d9fd-11e7-8380-b072b4eec801.png)
2. 空
![screenshot from 2017-12-05 20-47-17](https://user-images.githubusercontent.com/3756334/33607973-cd34a3a8-d9fd-11e7-96bf-110048f6defd.png)

**Comment by yutiansut** [comment]
是的 http://q.10jqka.com.cn/stock/thshy/ 同花顺自己直接崩了

**Comment by yutiansut** [comment]
你看下还能访问吗

**Comment by yssource** [comment]
1. 原来如此. 401 Authorization Required
2. 谢谢你的项目, 刚接触. 晚点我再研究一下.

**Comment by yutiansut** [comment]
暂时提供一个修改办法  现在把默认策略的板块换成 MSCI成份了  现在你可以试一下

**Comment by yssource** [comment]
成功的.

**Comment by yutiansut** [comment]
ok 暂时先这样吧

**Comment by yutiansut** [comment]
同花顺这个 电脑都没办法访问了  可能是在维护

**Comment by yssource** [comment]
thx, 由你来close这个issue了
