### ISSUE TITLE
奇怪的 '大数据i'

### ISSUE THREAD

**Issue by yssource** [yutiansut/QUANTAXIS#367]
- 为啥是 '大数据i'? 而不是 '大数据'
- 是数据解析错误吗? 多了一个 `i`

![screenshot from 2017-12-04 23-20-16](https://user-images.githubusercontent.com/3756334/33561677-4311a626-d94e-11e7-9beb-d6f9ba236253.png)

**Comment by yutiansut** [comment]
不是 这个是通达信的行业
![qq 20171205094424](https://user-images.githubusercontent.com/11537812/33585792-023fd89a-d9a1-11e7-8b34-aec22b11d332.png)
