### ISSUE TITLE
能给个在win7 64下面的部署步骤吗？

### ISSUE THREAD

**Issue by better319** [yutiansut/QUANTAXIS#37]
Windows/Linux(ubuntu) 已测试通过
python3.6优先(开发环境) python2系列要改个Queue的名字
nodejs 需要安装>7的版本,来支持es6语法
mongodb是必须要装的
Wind万得数据库 机构版/免费(大奖章版)
一个简易demo(需要先安装并启动mongodb,python版本需要大于3)

git clone https://github.com/yutiansut/quantaxis
cd quantaxis 
(sudo) python setup.py install
python easy_start_tushare.py(会存全市场的数据,较慢)
python test_strategy.py(一个简单的策略)
启动网络插件(nodejs 版本号需要大于6,最好是7)

cd QUANTAXISWebkit
(sudo) npm run install
(sudo) npm run Xweb
会自动启动localhost:8080网页端口,用账户名admin,密码admin登录
-----------------------------------------------
git clone https://github.com/yutiansut/quantaxis
cd quantaxis 
(sudo) python setup.py install
我已经运行到这里了
然后你这个文件呢？ easy_start_tushare.py

**Comment by better319** [comment]
easy_start_tushare.py
test_strategy.py
这两个文件好像找不到

**Comment by yutiansut** [comment]
git pull 一下

**Comment by yutiansut** [comment]
easy_start_tushare.py
[文件地址](https://github.com/yutiansut/QUANTAXIS/blob/master/easy_start_tushare.py)

**Comment by better319** [comment]
看到了
