### ISSUE TITLE
QATdx QA_fetch_get_stock_min error

### ISSUE THREAD

**Issue by gaizoule** [yutiansut/QUANTAXIS#374]
from QUANTAXIS.QAFetch.QATdx import *
QA_fetch_get_stock_min("000001", "2015-01-01", "2017-12-05")

ValueError: time data 'nan' does not match format '%Y-%m-%d'

**Comment by gaizoule** [comment]
改为 5 分钟：
QA_fetch_get_stock_min("000001", "2015-01-01", "2017-12-05", level = "5") 
可以取到数据，是不同的服务器能取的数据有限制吗？

**Comment by yutiansut** [comment]
level是指1分钟还是5分钟还是15分钟还是30min

**Comment by gaizoule** [comment]
@yutiansut 默认一分钟无法取到数据，应该是tdx服务器的问题

**Comment by yutiansut** [comment]
一分钟的不能拿太久  只能拿到20800个bar 大概是3-4个月

**Comment by gaizoule** [comment]
原来是这样

**Comment by yutiansut** [comment]
如果需要更早的分钟数据 可以用transaction数据合成 这个没有时间限制

**Comment by yutiansut** [comment]
@gaizoule 检查了下 优化了一下获取的错误

https://github.com/yutiansut/QUANTAXIS/commit/8a6400fcf09674388ba1b6994064d3c04b00f4ce

**Comment by yutiansut** [comment]
@gaizoule  git pull

**Comment by gaizoule** [comment]
@yutiansut 谢谢！

**Comment by yutiansut** [comment]
@gaizoule 现在应该是在任意时间都可以了 只是再早的分钟线拿不到 不过可以先 get_transaction 然后用 tick_resample方式
