### ISSUE TITLE
关于复权算法的疑问

### ISSUE THREAD

**Issue by gaizoule** [yutiansut/QUANTAXIS#375]
是否支持对分钟数据的复权?

**Comment by yutiansut** [comment]
支持的

**Comment by yutiansut** [comment]
用的是wind的复权算法 支持批量复权

**Comment by gaizoule** [comment]
~/Dropbox/py_ws/QUANTAXIS/QUANTAXIS/QAData/data_fq.py:52: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  bfq_data['if_trade'] = 1

是可以的，但报了一个 warning，新版的 pandas 0.21 @yutiansut

**Comment by yutiansut** [comment]
这个ok的 只是warning

**Comment by gaizoule** [comment]
@yutiansut  还有个小问题
    QA.QA_fetch_stock_min_adv(["000001"], "2017-07-20", "2017-07-21", type_ = "5min").data 
    不包含 2017-07-21 的数据，是故意这么设计的，还是有问题呢？
    QA.QA_fetch_stock_min_adv(["000001"], "2017-07-20", "2017-07-22", type_ = "5min").data
    就包含了 2017-07-21 的数据了

**Comment by yutiansut** [comment]
电脑不在身边 明天看一下代码回复你

**Comment by gaizoule** [comment]
@yutiansut 好的，辛苦了

**Comment by yutiansut** [comment]
是的 是lte end 然后你给的日期是5月21 也就是 5月21 零点 你如果要21号的 应该写 21号15:00:00

**Comment by gaizoule** [comment]
@yutiansut 明白了，非常感谢！
