### ISSUE TITLE
QA_data_make_hfq 和 QA_data_make_qfq 问题

### ISSUE THREAD

**Issue by gaizoule** [yutiansut/QUANTAXIS#376]
QA_data_make_hfq 和 QA_data_make_qfq
return data.query('if_trade==1').drop(['fenhong', 'peigu', 'peigujia', 'songzhuangu'], axis=1)[data['open'] != 0]
会引发 warning，建议改成：
return data.query('if_trade==1').drop(['fenhong', 'peigu', 'peigujia', 'songzhuangu'],axis=1).query("open != 0")

data["open"] 的长度可能长一些，导致返回值并不是想要的结果。

**Comment by yutiansut** [comment]
已经修改

**Comment by yutiansut** [comment]
@gaizoule   谢谢
 https://github.com/yutiansut/QUANTAXIS/commit/20143ce01d07557041a66537a1dc56bcb9e92682
