### ISSUE TITLE
这个错误怎么处理啊？  界面能出来，但是登录不上去admin

### ISSUE THREAD

**Issue by better319** [yutiansut/QUANTAXIS#38]
![image](https://cloud.githubusercontent.com/assets/13842581/25564712/af343aee-2deb-11e7-85a7-d9f415f9bfd1.png)

**Comment by better319** [comment]
npm run install运行到这一步会出现错误

**Comment by better319** [comment]
npm run Xweb运行这个能出现界面但是登录不上去

**Comment by better319** [comment]
![Uploading image.png…]()

**Comment by yutiansut** [comment]
mongodb本地服务启动了吗
