### ISSUE TITLE
tushare 0.8.7

### ISSUE THREAD

**Issue by yssource** [yutiansut/QUANTAXIS#382]
最新的 tushare v1.0.5, 已经删除了pytdx的源代码了, 现在它只是import pytdx.
是否可以考虑取消 tushare==0.8.7 这一限制呢? 
[tushare==0.8.7](https://github.com/yutiansut/QUANTAXIS/blob/master/setup.py#L94)

**Comment by yutiansut** [comment]
我测试下哈

**Comment by yutiansut** [comment]
@yssource 没有删除 还在的
![qq 20171215173013](https://user-images.githubusercontent.com/11537812/34035662-b2cdb8d4-e1bd-11e7-8426-facf06838bfb.png)

**Comment by yssource** [comment]
我是 fork 后, 再 本地 pip install -e .
好像, https://github.com/waditu/tushare 上面是没有了 pytdx 这个文件夹
原作者的最新版本是 v1.0.5, 你的为啥是 v1.0.7 ?

**Comment by yutiansut** [comment]
你说的没错 github上没有 但是pypi上有 就是pip install的时候

或者一个解决方案是 pip install git+https://github.com/waditu/tushare

但是容易误导安装 比如pip install tushare了 pytdx还是会失效

**Comment by yutiansut** [comment]
还在和tushare作者沟通中 暂时没有较好的解决方案 或者是quantaxis官方fork一份tushare
