### ISSUE TITLE
QA_fetch_get_stock_transaction 2017-12-02 KeyError: 'datetime'

### ISSUE THREAD

**Issue by yssource** [yutiansut/QUANTAXIS#388]
```
  import QUANTAXIS as QA
  code = '000001'

  start = '2017-12-02'
  end = '2017-12-02'

  # start = '2017-12-02 09:30:00'
  # end = '2017-12-02 15:00:00'

  QA.QA_util_log_info('分笔成交')
  data=QA.QAFetch.QATdx.QA_fetch_get_stock_transaction(code, start, end)
  print(data)

```

2017-12-02 是 not trading date, 这里应该内部 try catch 处理吧, 不应该 抛出 `KeyError: 'datetime'`

**Comment by yssource** [comment]
好像代码里面都没有 try catch 处理. 只能外部 try catch 了

**Comment by yutiansut** [comment]
不是吧

**Comment by yutiansut** [comment]
@yssource 你是取的一天的是把

**Comment by yutiansut** [comment]
@yssource  我修改了一下 不过没有更新在master里面 因为涉及到QA_util_get_real_datelist这个函数 我还要评估一些影响

**Comment by yssource** [comment]
- 2017-12-02 星期六这一天
- master 分支

```
QUANTAXIS>> 分笔成交
Traceback (most recent call last):
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5239)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5085)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1207, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20405)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1215, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20359)
KeyError: 'datetime'
```
- 好的, 等你评估修改完, 我在试试

**Comment by yutiansut** [comment]
我知道 是这样的 

我做了一个获取真实周期的函数 所以在给出一段日期的时候  我会去找开始日期往后的第一个交易日(包括开始日期) 以及结束日期往前的第一个交易日(包括结束日期)

这样就会有一个bug  如果开始日期--结束日期中间完全没有交易 (也就是周末的时候)

开始日期往后的第一个交易日是下周一 而结束日期往前的第一个日期是周五 也就是返回的start比end还晚一点

这时候拿这个去获取就出错了



解决方法是  判断如果返回的开始日期在结束日期之后 那么就返回None,None

再根据这个去判断是否获取

**Comment by yutiansut** [comment]
新修改的部分是这个 但是这个函数还用在别的地方 我得测试测试


https://github.com/yutiansut/QUANTAXIS/blob/account-remake-version/QUANTAXIS/QAUtil/QADate_trade.py#L74

https://github.com/yutiansut/QUANTAXIS/blob/account-remake-version/QUANTAXIS/QAFetch/QATdx.py#L532

**Comment by yssource** [comment]
另外 顺便提一下.
为什么这里要 hard coding [trade_date_sse](https://github.com/yutiansut/QUANTAXIS/blob/account-remake-version/QUANTAXIS/QAUtil/QADate_trade.py#L122)
我觉得应该维护一份 trade_date_sse 的 db table, save xxx 数据时, 这个 table 也应该相对应的更新.

**Comment by yutiansut** [comment]
为了速度.....内存里面的list 是最快的  而且这个数据一年一换  更新频率太低了

**Comment by yssource** [comment]
我明白你的目的, 但是打开这个文件拉倒底部, 很吃内存. 
目前 2017年前的这个数据你是维护好了. 但是, 2018 则么办? 你也要花时间做数据. 你也不清楚 未来 那天是开盘, 那天出发事件是 休盘的.
做成 db 的话, 只要用户自己 他 save xxx, 也是增量 更新.

**Comment by yutiansut** [comment]
@yssource  可以是可以 以前维护过一个交易表的  但是这个参数用的地方太多了 如果每次都查表 其实是得不偿失的 性能损失严重

**Comment by yutiansut** [comment]
@yssource 已更新 https://github.com/yutiansut/QUANTAXIS/commit/acbcac2eb1ad93fa2ccbe9734f132387fb024716

**Comment by yutiansut** [comment]
@yssource 2018年的很简单 我只要上传代码 git pull一下就有18年的了 这个没有任何问题

**Comment by yssource** [comment]
acbcac2 这个 commit 结果是对的.

关于 trade_date_sse 这个问题, 
 1. 现在这样处理也行, 这不是很大的问题.
 2. 上传代码 和 git pull 是很简单. 但是 2018 年的数据是未来的.  历史是确定的, 未来是不确定的. 这个数据是做回测用的. 拿到了历史数据, 这个 trade_ddate_sse 也就自然拿到了(实际上你的历史数据是从 2015-01-01 开始的). 未来不知道哪一天突发事件休市, 那你每一次都要 hard coding 一次(当然概率很低, 无需经常hard coding). 我是从这个角度认为 db 取历史数据更合理. 
 3. 我也认同你现在这样的 array.index 读取数据效率高.

**Comment by yutiansut** [comment]
你说的没错 但是其实本质是一样的  都是用户需要更新代码  那么 save trade_list 和 git pull 本质没有区别

**Comment by yutiansut** [comment]
不过 如果下面是多市场的 就需要做calendar类了 比如说 比特币全年无休 比如说 美股和a股时差  就需要一个calendar类去动态的调整时间系统
