### ISSUE TITLE
获取不了数据，是因为时间不对吗？

### ISSUE THREAD

**Issue by better319** [yutiansut/QUANTAXIS#39]
mongodb-win32-x86_64-2008plus-ssl-3.4.4-signed
node-v6.10.2-x64
![Uploading 1111.PNG…]()

**Comment by better319** [comment]
![1111](https://cloud.githubusercontent.com/assets/13842581/25564843/589ed902-2dee-11e7-9954-2ab1b946e066.PNG)

**Comment by yutiansut** [comment]
你tushare能获取数据吗

**Comment by better319** [comment]
不太会，安装好了。。。给个傻瓜版的，，，跪求啊

**Comment by yutiansut** [comment]
安装完了mongodb要启动的
