### ISSUE TITLE
0.5.30 save all 貌似不会更新数据

### ISSUE THREAD

**Issue by kaikai03** [yutiansut/QUANTAXIS#393]
今天到老笔记本上更新了下文件，试了下更新数据，看打印输出好像还挺正常，但是更新的数据没有更新进数据库，最终新日期还是之前的。（环境是mac anacoda py3.5，但应该没有关系吧）

stock_xdxr部分或独立执行save stock_xdxr， 会停一会，直接打印sucess，没有其他输出。

常用工作机上的0.5.28目前工作正常。

**Comment by yutiansut** [comment]
Mongodb服务开启了吗

**Comment by yutiansut** [comment]
哦 是我的bug

**Comment by yutiansut** [comment]
是我的bug @kaikai03  回滚了修改
https://github.com/yutiansut/QUANTAXIS/commit/45af75b7854f6f4c120e09aaab7452e7921fff1f

**Comment by kaikai03** [comment]
试下OK了
