### ISSUE TITLE
parse & import tick 历史数据 to mongod

### ISSUE THREAD

**Issue by yssource** [yutiansut/QUANTAXIS#397]
能否 将这里改一下呢? 
1. mac 用户
 [fname = file_dir + '\\' + file](https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QASU/save_tdx_file.py#L51)
改成: `fname = file_dir + os.path.sep + file`

2. 有时外部引用不到 schema
[from schema import (](https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAData/fundamental.py#L15)
改成: `from .schema import (`

**Comment by yutiansut** [comment]
@yssource  我正常都用os.sep的  这是哪里的代码  是fundmental的吗  那是别人贡献的代码 我还没整合呢

**Comment by yssource** [comment]
[https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QASU/save_tdx_file.py#L51](https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QASU/save_tdx_file.py#L51)

**Comment by yutiansut** [comment]
哦哦 这个没有啥用 接口也可以拿这个

**Comment by yssource** [comment]
接口那边 有 "if lens > 20800:" 这个限制. 
我通达信软件那边, 保存了部分几个月以前的分钟数据, 想手动插入 db 里面试试.

**Comment by yutiansut** [comment]
没用的 20800是tdx的限制 不是我的限制....

**Comment by yutiansut** [comment]
或者这么说 20800 是tdx界面的最大容纳的bar量

**Comment by yssource** [comment]
我明白你的意思. 通达信是 限制了 近100天的分钟数据获取. 我以前在通达信官方的软件下面有一部分几个月前的数据, 想用 你这个 QA_save_tdx_to_mongo 插入 db, 把我以前的数据导入 再做一下我自己写的回测策略,实验一下.

**Comment by yssource** [comment]
通达信官方的软件我也是好久没有更新过分钟数据了. 半年前的分钟数据还有一部分. 不知道, 大家谁有比较完整的2017年这一年的分钟数据 (通达信的数据原文件, 或者 做好了的 mongo db 数据文件), 要是能分享出来就是万幸了. 当然数据量太大, 云盘上传会好些. 哈哈, 我要求有点过分 ....

**Comment by yutiansut** [comment]
不是这个意思 是20800个bar 是所有类别的上限 当然 日线就几千个数据 肯定能拿到90年  但是分钟线 1分钟线因为这个限制 就只能拿3个月 如果想要更细的 需要tick数据合成

**Comment by yssource** [comment]
我个人理解: 

    1. 通达信官方对日线是没有限制的, 对分钟线有限制. 只能拿到最近的100天分钟数据.
    2. pytdx 的作者 @rainx 是通过 socket 从通达信官方拿数据. 因为官方的限制. 所以 pytdx 也只能拿到近一百天的分钟数据.
    3. 因为我刚接触你这个项目, 通过 QA_fetch_get_stock_min 我只能拿到最近100天的分钟数据. (比我早接触的这个项目的人 是可以拿到更早的数据)
    4. 非常谢谢你提供了 QA_save_tdx_to_mongo 这个接口. 因为我有源文件 比如 sz000001.lc1, 我自己这个数据是含有近一年的分钟数据的. 让我能够导入通达信官方的源文件到 db. 
    5. 是可以先 get_transaction 然后用 tick_resample 方式 拿到数据. 但是没有 QA_save_tdx_to_mongo 这样拿原始数据爽

**Comment by yutiansut** [comment]
没有 就是这个长度的问题 你可以自己下一个通达信 看一下就知道了 他的界面 就只能容下20800条数据

**Comment by yutiansut** [comment]
transaction数据才是真正交易时候会用的数据 至于其他的数据 都是transaction合成的

**Comment by yssource** [comment]
我明白. 今天 2107-12-23 下载, 当然也只能拿到 最近 100天的数据. 
但是, 有很多用户(包过我)用通达信好多年了. 以前下载过分钟数据这些原始数据都保留在 对应的 `vipdoc\sz\minline` 这个目录下面. 

所以我觉得, 你这个 `QA_save_tdx_to_mongo`, **很有用**. 能把我以前的历史数据 import 到 db 里面去.

**Comment by yutiansut** [comment]
我的想法吧 下面还是要以tick作为核心 但是这个转化太耗时间了  所以现在的方式是用空间换时间的做法

**Comment by yutiansut** [comment]
@yssource os.sep已改

**Comment by yssource** [comment]
[data 解析. tic_reader 分支](https://github.com/rainx/pytdx/issues/149)
