### ISSUE TITLE
本地数据中次新股没有上市当天的数据

### ISSUE THREAD

**Issue by anno189** [yutiansut/QUANTAXIS#411]
数据是从第二天开始的

**Comment by yutiansut** [comment]
代码报一下?

**Comment by anno189** [comment]
如果每天保存数据，就会存在这种情况。最近的次新股都有类似情况。我发现最早的可以追溯到603803，2017年04月20日上市。最近的002919~002923以及都有这种情况。中间又抽查了几个数据，都存在第一天没有数据的情况。
怀疑通达信中的开盘第一天数据是后来追加上去的。
002922上市当天是个周五，当天确实没有数据，之后第二天有的数据，就没有留意第二天是否包含了第一天的数据了。
等下一次新股上市的时候我会继续留意的。

如果可以的话，建议让开发组的人都留意一下。谢谢。

**Comment by AD189** [comment]
发现新的情况，上述情况描述不完整。刚才查看数据的时候，是没有执行完save stock_day的时候。现在执行完了，开盘第一天的数据又没有了。
也就是在保存未全部执行完成的时候，这些数据是存在的。但是最后确没有了。
是否在save stock_day中做过数据清洗。处理掉了振幅超过20%的数据？
稍后我也会review一下代码。

**Comment by anno189** [comment]
补充，删除stock_day,重新save stock_day，问题依然存在
版本号：0.5.30

**Comment by yutiansut** [comment]
收到

**Comment by anno189** [comment]
QASU\save_tdx.py
line:78
QA_fetch_get_stock_day(str(code), start_date, end_date, '00')[1::]))

问题是否出在这个地方
[1::]在这部分代码中，一共使用了六次。

**Comment by yutiansut** [comment]
哦哦 是的  这个是更新的时候 为了不重叠导致的  确实是bug

**Comment by yutiansut** [comment]
@AD189  做了更新和修正 但是之前的数据可能补不齐了..... 解决方法是 删掉所有数据库 重新下载

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/commit/544d65b6fd3e17f3de1c48bee296341fae1c84cf
