### ISSUE TITLE
Wrong in Getting 600556 history transaction data in day 2017-03-29

### ISSUE THREAD

**Issue by yssource** [yutiansut/QUANTAXIS#414]
- [Wrong in Getting 600556 history transaction data in day 2017-03-29](#sec-1)

# Wrong in Getting 600556 history transaction data in day 2017-03-29<a id="sec-1"></a>

```python
import QUANTAXIS as QA
QA.QA_util_log_info('分笔成交')
# code = '000001'
code = '600556'
start = '2017-03-29'
end = '2017-03-29'
# start = '2017-12-29'
# end = '2017-12-29'

data=QA.QAFetch.QATdx.QA_fetch_get_stock_transaction(code,start,end)
print(data)
```

**Comment by yutiansut** [comment]
这一天停牌

**Comment by yutiansut** [comment]
@yssource  报错原因是因为当只取一天而那一天又停牌的时候 就会出现
```python
return data.assign(datetime=data['datetime'].apply(lambda x: str(x)[0:19]))
```
找不到datetime

已经修改:
```python
        if len(data)>0:

            return data.assign(datetime=data['datetime'].apply(lambda x: str(x)[0:19]))
        else:
            return None
```

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/commit/4fd6a3f02b26274ccd21208bd7e224855a863ba6

只在重构版本上做了修改 因为即将合并分支 就不在master上修改了

**Comment by yssource** [comment]
谢谢.
    哈哈. 奇怪, 昨天在 通达信软件查了一下. 这个 600556 2017-03-29 没有停牌. 原来自己看花眼了
    刚才又去查看了一下. 确实停牌了.

**Comment by yutiansut** [comment]
@yssource  最简单的办法就是获取下日线就知道有没有停牌了 
另外 你要不要体验下新版本的回测?

**Comment by yssource** [comment]
好的. thx!
