### ISSUE TITLE
指数名称显示不完成的问题

### ISSUE THREAD

**Issue by anno189** [yutiansut/QUANTAXIS#416]
QUANTAXIS/QAFetch/QATdx.py
line:416

.assign(name=data['name'].apply(lambda x: str(x)[0:4]))\

部分指数名称显示不完整，建议修改成[0:6]

**Comment by yutiansut** [comment]
收到 ~

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/commit/0c414aa85f2f49d597c66798edc31613689106cb

**Comment by yutiansut** [comment]
@AD189 已修改
