### ISSUE TITLE
数据库链接有没有一个全局配置文件可以更改,打算设置下mongo链接的用户名和密码.

### ISSUE THREAD

**Issue by codealphago** [yutiansut/QUANTAXIS#417]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
2018年1月25日更新的版本


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
ubuntu 16.04 64 bit




```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```
您好!
  我打算更改下mongo的连接帐号和密码.请问下有没有一个全局配置文件可以更改,谢谢.
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@codealphago 目前的mongo没有加权限

**Comment by yutiansut** [comment]
@codealphago 目前的mongo没有加权限

**Comment by codealphago** [comment]
好的.

**Comment by codealphago** [comment]
添加权限,修改QASetting和QACmd即可.
