### ISSUE TITLE
QA_fetch_get_stock_list Error

### ISSUE THREAD

**Issue by anno189** [yutiansut/QUANTAXIS#419]
QA_fetch_get_stock_list
line 407~409
增加408行：[data.code // 70000 != 1][data.code // 80000 != 1] #现在通达信中存在债转股
修正409行：data.query('sse=="sh"')  #此处是BUG
调整409行：.astype('U', True).str.rjust(6, '0')) #现在输出的是Int的，line402转换

data.query('sse=="sz"')[data.code // 10000 <= 30][data.code // 100000 != 2][data.code // 100000 != 1][data.code // 70000 != 1][data.code // 80000 != 1],data.query('sse=="sh"')[data.code // 100000 == 6]]).assign(code=data['code'].astype('U', True).str.rjust(6, '0')).assign(name=data['name'].apply(lambda x: str(x)[0:6]))

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/commit/7eef624326aa07b86b5bfb0f664cf83bc22bab82
已修正
