### ISSUE TITLE
容器安装后，用户功能不可用

### ISSUE THREAD

**Issue by xiaobitao** [yutiansut/QUANTAXIS#423]
# 容器安装后，用户功能不可用

使用的是亚马逊云，用户的请求连接是localhost开头，应该是本地容器才可以使用

## 最新版本容器

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
本地替换localhost为你的地址 npm run build 打包出静态 html/js/css文件

**Comment by kingvern** [comment]
我也遇到了一样的问题，不过我打包时出错了
> quantaxisweb@0.4.1 build /home/quantaxis/QUANTAXIS_Webkit/web
> node build/build.js

⠏ building for production...
Starting to optimize CSS...
Processing static/css/app.7c0d709dc1feffb0561aa77613e7de5b.css...
Processed static/css/app.7c0d709dc1feffb0561aa77613e7de5b.css, before: 157277, after: 137262, ratio: 87.27%
Hash: 37a67fa1a09422bbfd07
Version: webpack 2.7.0
Time: 14099ms
                                                  Asset       Size  Chunks                    Chunk Names
               static/js/vendor.e8555c3d321aae54c997.js    4.12 MB       0  [emitted]  [big]  vendor
                  static/js/app.fe0a74d06bc422cffaef.js      45 kB       1  [emitted]         app
             static/js/manifest.003dfa9efa00c3dfbdd9.js    1.51 kB       2  [emitted]         manifest
    static/css/app.7c0d709dc1feffb0561aa77613e7de5b.css     137 kB       1  [emitted]         app
           static/js/vendor.e8555c3d321aae54c997.js.map    5.14 MB       0  [emitted]         vendor
              static/js/app.fe0a74d06bc422cffaef.js.map     291 kB       1  [emitted]         app
static/css/app.7c0d709dc1feffb0561aa77613e7de5b.css.map     218 kB       1  [emitted]         app
         static/js/manifest.003dfa9efa00c3dfbdd9.js.map    14.6 kB       2  [emitted]         manifest
                                             index.html  478 bytes          [emitted]         

ERROR in static/js/vendor.e8555c3d321aae54c997.js from UglifyJs
Unexpected token: punc (() [./~/_vue-monaco-editor@0.0.19@vue-monaco-editor/src/MonacoLoader.js:3,0][static/js/vendor.e8555c3d321aae54c997.js:116631,6]

  Build complete.

**Comment by yutiansut** [comment]
@kingvern 可以先``` npm run dev```
