### ISSUE TITLE
没有换手率计算吗??

### ISSUE THREAD

**Issue by smallevil** [yutiansut/QUANTAXIS#426]
找了半天代码,也没找到有换手率的计算方法.
不知道从哪得到这个值???
是我没找到?还是没写呢?
能不能写一个呢?
特别是得到指定的一段时间的数据,计算换手率.

**Comment by smallevil** [comment]
或者是这样的:
在得到日线,周线甚至分钟线时,现在只返回了open/close等等相关的几列.
是不是可以再加两列,总股本,流通股本,这样返回来的值再拿出来做计算就会方便很多了.

**Comment by yutiansut** [comment]
哦 有的 不过在analysis里面

**Comment by yutiansut** [comment]
DataStruct只负责尽可能高效和统一的承载和传输数据

**Comment by smallevil** [comment]
原谅我python太烂.
找到程序里的换手率计算了.
可封装了好几层,没太看明白是怎么合并进去的计算的.

因为我是用直接copy了你的两个函数
QA_fetch_get_stock_day
QA_fetch_get_stock_xdxr
然后想进行合并后多两列流通股和总股本
可搞了半天也没搞出来.

不知道你有没有时间可以给出代码,或伪代码也行.
谢谢

**Comment by yutiansut** [comment]
因为不同时间的股本都不一样.然后还有补充报表什么的.. 很多接口给的都是错的  财务这块 没几家是对的

**Comment by yutiansut** [comment]
而且按照有效市场理论 财务信息作为公开信息已经表达在股价里面了 其实本质也没啥卵用

**Comment by yutiansut** [comment]
你要算的话 只能先粗略一点了:

```

1. 拿出xdxr的市值和时间
2. 组成一个市值的时间序列
3. append到dataframe上
4. 计算市值(得X100)
```
