### ISSUE TITLE
mac上使用pytdx时API上参数不一致问题

### ISSUE THREAD

**Issue by musicx** [yutiansut/QUANTAXIS#428]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.0.22


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

macos



```

## 您的系统环境是什么?
```
- monodb
- nodejs v8
- python3.6
- docker(无)
```
## 您需要反馈的问题
```
pytdx.hq.TdxHq_API.connect 函数，在mac上没有time_out参数。函数签名仅接受ip，port两个参数。
造成运行时无法选择有效ip

pytdx.exhq.TdxExHq_API.connect 可能有相同问题

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```

去除了QATdx，QATdx_adv 文件中所有time_out参数
即可正常运行。

```
## 您的联系方式(QQ/EMAIL)
```
musicxing    at  ____   gmail
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
使用 
```
pip uninstall pytdx
pip install pytdx
```
即可, 原因是因为tushare内置的pytdx没有timeout参数,导致覆盖了pytdx的路径

先卸载pytdx再重新安装即可

**Comment by musicx** [comment]
Very helpful!
