### ISSUE TITLE
Indicator需要做些测试啊

### ISSUE THREAD

**Issue by musicx** [yutiansut/QUANTAXIS#429]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.0.22

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
masOS

```

## 您的系统环境是什么?
```
- monodb
- nodejs v8
- python3.6
- docker (无)
```

## 您需要反馈的问题
```
QAIndicator.QAIndicator_Series.AVEDEV 是错的啊。。。用了tail(N)的话，就变成固定值了。。。
同理，QAIndicator.QAIndicator_DataFrame.CCI，tail(1)是单个值，即便去掉，AVEDEV是固定值的话，整个数列是错误的。。。

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```
建议对数据处理的部分，建一些测试样例。
修正后的指标和新的指标，可以提pull request的吗？

```
## 您的联系方式(QQ/EMAIL)
```
musicxing
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
提供下你的代码 @musicx

**Comment by musicx** [comment]
不好意思一阵时间没来。看到CCI等指标已经更正了，感谢！
再提交一个bug：  COUNT(COND, N) 是 错误的。
我的代码：

def count(cond, days):
    signal = cond * 1   # cond 是 true/false的话，换成1/0
    return reduce(lambda x, y: x + y, [signal.shift(x).fillna(0) for x in (range(days) if days >= 0 else range(-1, days-1, -1))])

没用rolling主要是要支持我用未来是否发生事件来做训练标签。

**Comment by yutiansut** [comment]
我测试一下

**Comment by yutiansut** [comment]
你的这个写法有点问题 @musicx 你会导致前N个的结果是错误的

**Comment by yutiansut** [comment]
```
import numpy as np
import pandas as pd

def count(cond,N):
   return pd.Series(np.where(cond,1,0),index=cond.index).rolling(N).sum()
```

**Comment by musicx** [comment]
CCI 还是不对，找了一下，是基础的AVEDEV函数还有问题

def AVEDEV(Series, N):
    return Series.rolling(N).apply(lambda x: (np.abs(x - x.mean())).sum()/x.size, raw=True)

**Comment by yutiansut** [comment]
```
def AVEDEV(Series, N):
return Series.rolling(N).apply(lambda x: (np.abs(x - x.mean())).mean(), raw=True)
```

**Comment by QUANTAXISER** [comment]
```
def AVEDEV(Series, N):
return Series.rolling(N).apply(lambda x: (np.abs(x - x.mean())).mean(), raw=True)
```

**Comment by QUANTAXISER** [comment]
用这个 @musicx
