### ISSUE TITLE
为什么我跑完策略没法在网页里面看呢

### ISSUE THREAD

**Issue by flemington** [yutiansut/QUANTAXIS#430]
安装都没问题。
我看代码里面有一个插入输入表格的 save_backtest.py 是将测试结果插入到表格 quantaxis.backtest_history 中去的。但是没有地方调这个类的函数保存数据到mongodb中。
所以网页中的回测界面中看不到数据。。

**Comment by yutiansut** [comment]
是的 因为网页版是旧版本的回测的内容, 新版本改了回测但还是一直没改网页
