### ISSUE TITLE
能否指定固定的user，account，portfolio？

### ISSUE THREAD

**Issue by royburns** [yutiansut/QUANTAXIS#432]
![image](https://user-images.githubusercontent.com/652375/39690462-d1d99fee-520c-11e8-80f0-f17a4591e305.png)

我看代码，user，account，portfolio这三个cookie都是随机生成的，能否指定固定的user，account，portfolio？

**Comment by yutiansut** [comment]
哦 可以的呀 你可以在创建的时候 自己传参进去

**Comment by yutiansut** [comment]
```
QA.QA_Account(account_cookie='Acc1111')
```
< QA_Account Acc1111>
