### ISSUE TITLE
将阿里云Docker部分代码开源一下，保证安全性

### ISSUE THREAD

**Issue by qzm** [yutiansut/QUANTAXIS#440]
你好，希望把阿里云Docker镜像生成的那部分代码开源一下，不然不敢直接使用

**Comment by yutiansut** [comment]
额 暂时不建议用docker 还没完全解决docker的数据库问题

**Comment by zsluedem** [comment]
docker 数据库有什么问题

**Comment by yutiansut** [comment]
数据库没法在docker里面运行 docker文件会越来越大

**Comment by zsluedem** [comment]
映射到外部文件

**Comment by yutiansut** [comment]
我研究研究

**Comment by EricQAQ** [comment]
使用了阿里云的镜像,发现没有找到mongod... @yutiansut 可以使用挂载磁盘的方式把mongo的数据存储在宿主机上

**Comment by yutiansut** [comment]
@EricQAQ 关键是我对怎么挂载不是很熟悉...

**Comment by zsluedem** [comment]
@yutiansut 挂载后，数据还是要自己下载的，我一会帮你弄弄

**Comment by EricQAQ** [comment]
@yutiansut 如果使用docker file去启动实例, 就是volume关键字, 如果是命令行的话, 加-v 这个参数

**Comment by yutiansut** [comment]
其实目前来说 全系统都支持的 win/mac/linux 所以可以直接部署的 @qzm @EricQAQ

**Comment by qzm** [comment]
可以用 docker-compose启动多个 service，一个mongodb的service，一个webserver的service，mongodb的数据映射到机器外部，需要的话，我这边写一个，过两天给你提PR

**Comment by yutiansut** [comment]
@qzm 好勒 谢谢辣~~ mongo这块的我确实不清楚 不过quantaxis可以通过改配置文件来设置数据库了
