### ISSUE TITLE
添加数据库配置设置方式，增加读取环境变量和读取home目录设置

### ISSUE THREAD

**Issue by zsluedem** [yutiansut/QUANTAXIS#441]

**Comment by zsluedem** [comment]
1. 在home目录创建一个.quantaxis目录，里面放一个config.json格式的配置文件
2. 读取环境变量 os.env
3. 默认配置

按照以上顺序读取配置

**Comment by zsluedem** [comment]
@yutiansut 建议群主把mongodb ip,host形式改为 uri形式

**Comment by yutiansut** [comment]
已经修改 在1.0.34中
