### ISSUE TITLE
测试tdx ip速度增加exclude ip功能

### ISSUE THREAD

**Issue by pchaos** [yutiansut/QUANTAXIS#446]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
测试tdx ip速度增加exclude ip功能

**Describe alternatives you've considered**
不同地区ip测试速度不同。考虑在配置文件中增加exclude ip list，方便用户排除速度慢的ip

**Additional context**
none

**Comment by yutiansut** [comment]
唔 可以搞

**Comment by yutiansut** [comment]
我会在第一次的时候做个初始化 把最优top 10 扔进配置文件 之后就从配置文件读取把

**Comment by pchaos** [comment]
那就再加个配置:下次是否重新测试top10

**Comment by pchaos** [comment]
已经提交pr
