### ISSUE TITLE
其实我觉得这个还是不够傻瓜

### ISSUE THREAD

**Issue by better319** [yutiansut/QUANTAXIS#48]
能够把相应的东西放到pip里面或者winpython里面那样就傻瓜了，够一键启动了。

**Comment by yutiansut** [comment]
我封了pip包 可是现在版本不够稳定,pip更新太快 跟不上

**Comment by better319** [comment]
![Uploading image.png…]()
这个帮我看下吧，英文不好

**Comment by better319** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd E:\QUANTAXIS\QUANTAXISWebkit

C:\Users\Administrator>e:

E:\QUANTAXIS\QUANTAXISWebkit>npm run Xweb

> quantaxis@0.3.9-dev-alpha Xweb E:\QUANTAXIS\QUANTAXISWebkit
>  npm run website|npm run backend


> quantaxis@0.3.9-dev-alpha backend E:\QUANTAXIS\QUANTAXISWebkit
> node ./backend/bin/www

(node:1780) DeprecationWarning: loaderUtils.parseQuery() received a non-string v
alue which can be problematic, see https://github.com/webpack/loader-utils/issue
s/56
parseQuery() will be replaced with getOptions() in the next major version of loa
der-utils.

**Comment by yutiansut** [comment]
这个没问题的,不影响运行

**Comment by yutiansut** [comment]
你现在用的如何了?  收集下反馈 @better319

**Comment by better319** [comment]
最后还是没配置好，，，伤心啊，求把nodejs 和mongodb一起放进去，直接生成win的服务。nodejs有一个后来一直安装不上去，好像是网速不够还是怎么的。。卡主了，就一直没处理

**Comment by yutiansut** [comment]
.....喵?  要不你加群或者加我qq吧 ?
