### ISSUE TITLE
使用save all 或者 save stock_day之后，数据库里没有stock_day数据

### ISSUE THREAD

**Issue by lijieamd** [yutiansut/QUANTAXIS#492]
![1](https://user-images.githubusercontent.com/4757414/40728823-88e587c2-645d-11e8-9031-c95d4263ec71.png)
![2](https://user-images.githubusercontent.com/4757414/40728824-8972419e-645d-11e8-8784-4142d974f810.png)

看起来除了stock_day以外的数据都存储成功了，只有stock_day的是0
执行回测example的时候，调用QA_fetch_stock_day时，也是返回空的，应该说明确实没有数据
请问这个有可能是哪里出问题了呢

**Comment by yutiansut** [comment]
你用 ```QA.QA_fetch_get_stock_day('tdx','000001','2018-01-01','2018-05-30')```试一下

**Comment by lijieamd** [comment]
你好，我试过了，在调用pytdx的api.connect的时候time_out了

**Comment by yutiansut** [comment]
@lijieamd 最近好了吗

**Comment by lijieamd** [comment]
刚才也试了，一直是time out。
我自己用pytdx的api试了下是可以获得日K的

**Comment by yutiansut** [comment]
你在qq群里面吗

**Comment by lijieamd** [comment]
不在，号码是多少呢，我加一下

**Comment by yutiansut** [comment]
563280067

**Comment by foxlisimulation** [comment]
@lijieamd  您是怎么解决的呢，我也出现了这个问题

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/issues/747
