### ISSUE TITLE
tdx 日线数据出错

### ISSUE THREAD

**Issue by engine2rt** [yutiansut/QUANTAXIS#509]
**Describe the bug**
600568， 2018-06-01没有交易，但是通过：
QA.QA_fetch_get_stock_day('tdx', '600568', '2018-05-31', '2018-06-01', if_fq='bfq')

拿到数据如下：
	open	close	high	low	vol	amount	date	code	date_stamp
date									
2018-06-01	6.49	6.49	6.49	6.49	5.877472e-39	5.877472e-39	2018-06-01	600568	1.527782e+09

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yutiansut** [comment]
哦 这个是ok的 可以用量去区分 因为他的量<1

**Comment by yutiansut** [comment]
5.877472e-39

**Comment by yutiansut** [comment]
@engine2rt

**Comment by yutiansut** [comment]
在本地读取的时候, 就会选择volume>1的 @engine2rt 
[QUANTAXIS/QAFetch/QAQuery.py Line66](https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QAQuery.py#L66)
```python
        try:
            res = res.drop('_id', axis=1).assign(volume=res.vol).query('volume>1').assign(date=pd.to_datetime(
                res.date)).drop_duplicates((['date', 'code'])).set_index('date', drop=False)
            res = res.ix[:, ['code', 'open', 'high', 'low',
                             'close', 'volume', 'amount', 'date']]
```
