### ISSUE TITLE
example of paper trading

### ISSUE THREAD

**Issue by andrewcz** [yutiansut/QUANTAXIS#521]
**Is your feature request related to a problem? Please describe.**
trading example

**Describe the solution you'd like**
example of paper trading maybe in Jupiter notebook

**Describe alternatives you've considered**
looked at some of the examples, would like full paper trading with backtest

**Additional context**
love the repo amazing work will buy you a coffee :)

**Comment by yutiansut** [comment]
here is some example of backtest [examples](https://github.com/QUANTAXIS/QUANTAXIS/tree/master/test_backtest) and [test](https://github.com/QUANTAXIS/QUANTAXIS/tree/master/QUANTAXIS_Test/QABacktest_Test)

here are the documents [documents](https://github.com/QUANTAXIS/QUANTAXIS/tree/master/Documents)

and here are the jupyterexamples[jupyterexamples](https://github.com/QUANTAXIS/QUANTAXIS/tree/master/jupyterexample)

if u have any questions about this, could ask me in this issue or add the qq group [link](https://jq.qq.com/?_wv=1027&k=4CEKGzn)

sorry for lack of english documents~ and i'll write about english doc  as soon as possible

@andrewcz

**Comment by andrewcz** [comment]
All good champion 😊!
Using Google translate.
Is there a paper trading example to see the framework in action.

Many thanks,
Andrew
