### ISSUE TITLE
看到一个很牛逼的组件 REACT的react-stockcharts, 希望会react的大佬一起开发

### ISSUE THREAD

**Issue by yutiansut** [yutiansut/QUANTAXIS#522]
https://demo.reactstockcharts.org/

https://github.com/rrag/react-stockcharts

![](http://osnhakmay.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180604183018.png)

**Comment by yutiansut** [comment]
https://gocharting.com/terminal/IN/EQINDEX/NIFTY/NSE

![](http://osnhakmay.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180604183254.png)

**Comment by tauruswang** [comment]
ok, 先写需求说明，布局，功能等。

**Comment by hardywu** [comment]
之前的vue 代码不要了？

**Comment by yutiansut** [comment]
现在在 [qadesk ](https://github.com/quantaxis/qadesk)
