### ISSUE TITLE
issues with the install

### ISSUE THREAD

**Issue by andrewcz** [yutiansut/QUANTAXIS#573]
(myenv) [andrewcz@andrewcz-pc QUANTAXIS]$ pip install tushare
Collecting tushare
  Using cached https://files.pythonhosted.org/packages/fa/29/a2c6e6d0899cf3b6a5da7eacc57bc4096f1be4b286617f3f929c6542c648/tushare-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ixbb5mxe/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-install-ixbb5mxe/tushare/tushare/__init__.py", line 106, in <module>
        from tushare.stock.minsdata import TsData
      File "/tmp/pip-install-ixbb5mxe/tushare/tushare/stock/minsdata.py", line 86
        print df
               ^
    SyntaxError: Missing parentheses in call to 'print'

issue with the install
apologies 
andrew

**Comment by andrewcz** [comment]
pretty sure this is an issue with tushare package.
Many thanks,
Best,
andrew

**Comment by yutiansut** [comment]
i'll make a pr to tushare for fix this question maybe a lower version would pass（the author of tushare using python2，so maybe he forget this）

**Comment by yutiansut** [comment]
@andrewcz 
my tushare version is 1.1.5, so defintly using``` pip install tushare==1.1.5 ```could fix this problem, and i'll make a pr to fix tushare latter

```
PS E:\> pip list | findstr tushare
tushare                            1.1.5
PS E:\>

```

**Comment by yutiansut** [comment]
most of time, we chat in QQ, so maybe you could using QQ International to join us ~ https://im.qq.com/download/ 
TIM product or QQ PCversion is both ok~ 

after installing qq, join us using find groups, input the group number 563280067 and make an apply~

we are waiting for U~   @andrewcz

**Comment by yutiansut** [comment]
tushare has already fixed pip install tushare -U
