### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by azluck** [yutiansut/QUANTAXIS#60]
data_fq.py下    
data.query('if_trade==1').drop(['fenhong', 'peigu', 'peigujia', 'songzhuangu'], axis=1).query("open != 0")
建议改为：
data.query('if_trade==1 & open != 0').drop(['fenhong',** 'peigu', 'peigujia', 'songzhuangu'], axis=1)

**Comment by yutiansut** [comment]
@azluck thx, https://github.com/QUANTAXIS/QUANTAXIS/pull/845  已经pr
