### ISSUE TITLE
pip install tornado==4.4.3  限制下 5.0出错

### ISSUE THREAD

**Issue by better319** [yutiansut/QUANTAXIS#654]
如题

**Comment by yutiansut** [comment]
我是5.0.2的呀

```
C:\Users\quantaxis
λ pip list| findstr tornado
tornado                            5.0.2

```

**Comment by yutiansut** [comment]
报错截图看下 @better319

**Comment by better319** [comment]
AttributeError: type object 'IOLoop' has no attribute 'initialized' 
启动jupyter notebook 会报错

**Comment by better319** [comment]
![image](https://user-images.githubusercontent.com/13842581/42018482-ce87838c-7ae4-11e8-9744-ec5f97c36596.png)
启动jupyter notebook会报错

**Comment by yutiansut** [comment]
这是zmq的问题吧 跟tornado没关系 @better319

**Comment by better319** [comment]
有可能，反正这样能解决就好了

**Comment by better319** [comment]
白猫黑猫能解决问题的是好猫！

**Comment by better319** [comment]
你没这个问题吗？

**Comment by yutiansut** [comment]
@better319 没见到过啊...

**Comment by better319** [comment]
![Uploading image.png…]()
我还每次会有这个出现，使用是没问题，就是看着纠结。这个是什么东西啊

**Comment by better319** [comment]
![360 16530712404823](https://user-images.githubusercontent.com/13842581/42022089-dcd88bfc-7aee-11e8-971f-0f0d7cc722e7.jpg)

**Comment by yutiansut** [comment]
是不是zmq版本太低了 似乎是zmq的eventloop出错了

**Comment by yutiansut** [comment]
@better319 哦 你这个只要降级pyecharts就行了  pyecharts他用了macropy 然后macropy里面会自检,打log

**Comment by yutiansut** [comment]
@better319 我后来更新过限制了pyecharts的版本, 不过你要卸载lml macropy这些以后 然后重装pyecharts到0.4.1版本

**Comment by better319** [comment]
好的，那就这样吧

**Comment by nuswgg** [comment]
![err](https://user-images.githubusercontent.com/46868109/81314742-0deb5780-90bc-11ea-8c4f-e00ea5941096.jpg)
我每次装都会遇到这个问题，现在新电脑也是这一个问题，搞了很久，没法解决，要么就把tornado降级, 要么就不能用jupyter

**Comment by yutiansut** [comment]
@nuswgg 不会的 升级jupyter zmq这些就可以了 我从来都是tornado5.1.1 包括docker 起码装过的都几千台了

**Comment by nuswgg** [comment]
问题解决了  pip install --upgrade pyzmq==17.0.0
应该是anaconda的zmq默认版本比较低，只支持4.5.3 
pip install pyzmq 不会安装较高版本  必须指定高版本

**Comment by nuswgg** [comment]
只是解决了jupyter 无法启动， 现在能启动，但没有办法连上kernel。
stackflow和github 上有很多讨论，除了喊降级tornado，没有看到其他有效的办法

**Comment by yutiansut** [comment]
> 只是解决了jupyter 无法启动， 现在能启动，但没有办法连上kernel。
> stackflow和github 上有很多讨论，除了喊降级tornado，没有看到其他有效的办法

就没听说过还有能解决不了这种问题的  你qq私聊我远程
