### ISSUE TITLE
后复权数据错误

### ISSUE THREAD

**Issue by zhongjyyy** [yutiansut/QUANTAXIS#702]
**Describe the bug**
后复权数据错误

**To Reproduce**
1、QAData/QADataStruct.py:113 ， 函数 QA_data_stock_to_fq调用无参数，使用默认参数，默认参数为前复权
2、QAData/data_fq.py:89, 函数 QA_data_make_hfq 结果错误, 后复权最后一条数据比不复权数据还小

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gaizoule** [comment]
对，这个问题现在还没有修复

**Comment by yutiansut** [comment]
already fixed https://github.com/QUANTAXIS/QUANTAXIS/pull/706
