### ISSUE TITLE
加上周线、月线、季线、年线的K线获取方法

### ISSUE THREAD

**Issue by pchaos** [yutiansut/QUANTAXIS#710]
**Is your feature request related to a problem? Please describe.**
QA中有分钟线的获取方法，没有周线、月线、季线、年线的

**Describe the solution you'd like**
希望加上周线、月线、季线、年线的

**Comment by yutiansut** [comment]
有的

**Comment by yutiansut** [comment]
存储也有

**Comment by pchaos** [comment]
忘了加上是本地的周线、月线、季线、年线

**Comment by yutiansut** [comment]
@pchaos 本地确实没有

**Comment by pchaos** [comment]
需要重新保存数据吗？如果直接从日线数据计算返回周线等数据，我来改吧？

**Comment by yutiansut** [comment]
@pchaos 我写了分钟线的降采样  日线也可以搞

**Comment by pchaos** [comment]
def resample(df, period='w'):
            # https://pandas-docs.github.io/pandas-docs-travis/timeseries.html#offset-aliases
            # 周 W、月 M、季度 Q、10天 10D、2周 2W
            df = df.reset_index(drop=True).set_index('date')
            weekly_df = df.resample(period).last()
            weekly_df['open'] = df['open'].resample(period).first()
            weekly_df['high'] = df['high'].resample(period).max()
            weekly_df['low'] = df['low'].resample(period).min()
            weekly_df['close'] = df['close'].resample(period).last()
            weekly_df['volume'] = df['volume'].resample(period).sum()
            weekly_df['amount'] = df['amount'].resample(period).sum()
            # 去除空的数据（没有交易的周）
            weekly_df = weekly_df[weekly_df.close.notnull()]
            weekly_df.reset_index(inplace=True)
            return weekly_df

        code = '000002'
        tdate = '2017-1-1'
        end = datetime.datetime.now().date()
        data = qa.QA_fetch_stock_day_adv(code, start=tdate, end=end).to_qfq()
        df = data.add_func(lambda x: resample(x, 'w'))

这样计算出来的周线数据和通达信的起始日期对不上，难道无解？

**Comment by pchaos** [comment]
通达信返回周线：
data1 = qa.QAFetch.QATdx.QA_fetch_get_stock_day(code, '2017-01-01', end.strftime("%Y-%m-%d"), frequence='w')
周期对不上，能解决吗？

**Comment by pchaos** [comment]
是我理解错了，其实是一样的，通达信显示的是周期结束日期，pd显示的是周期开始日期

**Comment by yutiansut** [comment]
DataStruct直接自动采样
