### ISSUE TITLE
QAFetch.QATdx.QA_fetch_get_stock_day返回未处理参数end？

### ISSUE THREAD

**Issue by pchaos** [yutiansut/QUANTAXIS#720]
**Describe the bug**
QAFetch.QATdx.QA_fetch_get_stock_day先调用结束时间晚的，再调用end时间之前的日期，返回相同的dataframe，

**To Reproduce**
 下面例子中，data和data1应该返回不同的数，实际返回相同的dataframe：

def test_QATdx_QA_fetch_get_stock_day(self):
        code = '000002'
        data = QA.QAFetch.QATdx.QA_fetch_get_stock_day(code, '2017-01-01',
                                                        datetime.datetime.now().date().strftime("%Y-%m-%d"))
        data1 = QA.QAFetch.QATdx.QA_fetch_get_stock_day(code, '2017-01-01', '2018-7-10')
        self.assertTrue(not data.equals(data1), '结束时间不同，获得数据应该不相同：{} {}'.format(data, data1))

**Expected behavior**
data1返回了到今天'2018-7-16'的数据，实际应该返回到'2018-7-10'的数据

**Screenshots**

**Desktop (please complete the following information):**
 - OS:federo
 - Version 26

**Additional context**
无

**Comment by yutiansut** [comment]
已修复
