### ISSUE TITLE
Trying to call QA_fetch_get_stock_day method

### ISSUE THREAD

**Issue by Annous87** [yutiansut/QUANTAXIS#742]
Hello,

I have just joined the Quantaxis community and I would like to make my first method call.

When trying to execute this command QA.QAFetch.QATdx.QA_fetch_get_stock_day('tdx', '000001', '2017-01-01', '2017-01-02') I get the first error of unexpected timeout argument in the method connect() in QUANTAXIS\QAFetch\QATdx.py

Then I removed the timeout argument and got this error:

    with api.connect(ip, port):
AttributeError: __enter__

Can someone help me please? I'm not a Chinese speaker so would you mine to write me in English?

Thank you

**Comment by yutiansut** [comment]
all right ...

the reason for timeout is a pr which i made for pytdx repo, in that pr, i add a timeout parameter, which is already updated  in pytdx, however the tushare package get a early version of pytdx, and made it inside..

so, here is the solution 
```
pip uninstall pytdx

pip install pytdx
``` 
@Annous87

**Comment by yutiansut** [comment]
the ``` AttributeError``` maybe a bad response if u re not in chinese , so firstly re-install the pytdx and try it again, QUANTAXIS will test the speed of best sever for U

**Comment by Annous87** [comment]
Thank you very much! That works fine for me and servers are responding

I uninstalled and re-installed pytdx package and changed my wifi connection too

Kind regards
