### ISSUE TITLE
使用save  stock_day的时候无法获取数据，报错

### ISSUE THREAD

**Issue by foxlisimulation** [yutiansut/QUANTAXIS#745]
如下所示
![image](https://user-images.githubusercontent.com/13410760/43381427-31f3884a-9407-11e8-88c8-5c080a54db6f.png)

**Comment by youweiliang** [comment]
我的情况也差不多，save all 的时候所有IP都显示"bad response"， 然后显示上图的"time out"。

**Comment by foxlisimulation** [comment]
把pytdx卸载重装就可以了

**Comment by youweiliang** [comment]
@foxlisimulation 确实可以了，非常感谢！

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/issues/747
