### ISSUE TITLE
QA_fetch_financial_report和QA_fetch_financial_report_adv总是返回None

### ISSUE THREAD

**Issue by youweiliang** [yutiansut/QUANTAXIS#750]
比如：
`res=QA.QA_fetch_financial_report(['000001','600100'],['2017-12-31','2018-03-31'])
`
`res`

`len(res)`
```
Traceback (most recent call last):

  File "<ipython-input-14-8a076ee39a0a>", line 1, in <module>
    len(res)

TypeError: object of type 'NoneType' has no len()
```

已经执行过数据初始化：
quantaxis> save all
quantaxis> save stock_block
quantaxis> save stock_info
也能够正常获取日线数据。

**Comment by yutiansut** [comment]
哦哦哦 没有存数据

财务数据是单独存的  @Youwei-Liang 


```
save financialfiles
```

pS.   你可以直接输入save来看下各种其他的命令

**Comment by youweiliang** [comment]
哦，原来如此。谢谢 ：）
@yutiansut
