### ISSUE TITLE
亲测，必须是32位py3.6才能跑，部署数据到本地有时会有error

### ISSUE THREAD

**Issue by luhongkai** [yutiansut/QUANTAXIS#762]
64位的跑不会code报错，但是会Kernel died, restarting，无论如何都跑不通回测
文档里说只有要交易才需要32位（我猜是交易接口是32位的？），但实际上回测也需要32位的
建议作者把教程文档里的图换成32位的anoconda，要不真的坑了新人

**Comment by yutiansut** [comment]
一直用64位开发 就没用过32位

**Comment by luhongkai** [comment]
那就放着吧。留着遇到跟我有相同问题的朋友有一个可能的解决方向

**Comment by yutiansut** [comment]
我就是64位 请你指责前至少说明你跑了什么回测 什么文件 谢谢
