### ISSUE TITLE
save stock_info报ERROR CODE

### ISSUE THREAD

**Issue by well847** [yutiansut/QUANTAXIS#765]
ver 1.1.0
不知道具体原因save stock_info每次都会报不同的ERROR CODE
但是这个好像每次执行都会drop collection然后重新保存，执行数次从来没有完整过
用的北方电信网

**Comment by well847** [comment]
ver 1.1.0
在《QUANTAXIS回测分析全过程讲解.ipynb》中
Account.receive_deal(Broker.receive_order(QA.QA_Event(order=order,market_data=item)))
receive_deal()不能正确获得（识别）参数了

**Comment by yutiansut** [comment]
这个代码我已经改掉了  git pull并参考新的代码

**Comment by well847** [comment]
QADealer.py的callback_message()返回了一个列表，
先不管值的顺序问题，这个列表又作为QAAccount.py的receive_deal()参数，

大概是这里没能正确分割参数，更深看不懂了

**Comment by yutiansut** [comment]
@well847 现在的模式不是这样的 现在是 Orderhandler去查询成交数据 然后推送给Order类, order类在1.1.x里面改成了一个有限状态机, 在收到交易后执行QA_Order.trade函数, trade函数会调用callback(在创建order的时候Account把receive_order函数做为参数传过去的), 从而更新account

**Comment by yutiansut** [comment]
@well847 这个主要也是因为要对接实盘做的修改 因为实盘的时候 交易没有回报,只能自己主动查询 于是就改成了如上所说的模式
