### ISSUE TITLE
pytdx相关的ip无法使用

### ISSUE THREAD

**Issue by williamjqk** [yutiansut/QUANTAXIS#786]
使用pytdx的时候https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAUtil/QASetting.py
里面的ip都ping不通.

**Comment by yutiansut** [comment]
报错贴个图  如果是timeout 参见https://github.com/QUANTAXIS/QUANTAXIS/issues/747

**Comment by williamjqk** [comment]
谢谢, 按照#747的做法
```sh
pip uninstall pytdx
pip install pytdx
```
之后大部分ip就能用了

**Comment by yutiansut** [comment]
ok
