### ISSUE TITLE
这是什么错误的啊？ 运行save all出现的错误

### ISSUE THREAD

**Issue by haohello** [yutiansut/QUANTAXIS#790]
QUANTAXIS>> ^_ ERROR CODE ^_

QUANTAXIS>> ['002502', '002503', '002504', '002505', '002506', '002507', '002508', '002509', '002510', '002511', '002512', '002513', '002514', '002515', '002516', '002517', '002518', '002519', '002520', '002521', '002523', '002524', '002526', '002527', '002528', '002529', '002530', '002531', '002532', '002533', '002534', '002535', '002536', '002537', '002538', '002539', '002540', '002542', '002543', '002544', '002545', '002546', '002547', '002548', '002549', '002550', '002551', '002552', '002553', '002554', '002555', '002556', '002557', '002558', '002559', '002560', '002561', '002562', '002563', '002564', '002565', '002566', '002567', '002568', '002569', '002570', '002571', '002572', '002573', '002574', '002576', '002577', '002578', '002579', '002580', '002581', '002582', '002583', '002936', '002937', '002938', '300204', '300220', '300221', '300223', '300234', '300242', '300748', '300749', '601577', '603583', '603587', '603588', '603589', '603590', '603595', '603596', '603598', '603599', '603600', '603601', '603602', '603603', '603605', '603606', '603607', '603608', '603609', '603611', '603612', '603615', '603616', '603617', '603618', '603619', '603626', '603628', '603630', '603633', '603636', '603637', '603638', '603639', '603648', '603650', '603655', '603656', '603657', '603658', '603659', '603660', '603661', '603663', '603665', '603666', '603667', '603668', '603669', '603676', '603677', '603678', '603679', '603680', '603683', '603685', '603686', '603688', '603689', '603690', '603693', '603696', '603698', '603699', '603701', '603703', '603706', '603707', '603708', '603709', '603711', '603712', '603713', '603716', '603717', '603718', '603721', '603722', '603725', '603726', '603727', '603728', '603729', '603730', '603733', '603737', '603738', '603757', '603758', '603766', '603767', '603768', '603773', '603776', '603777', '603778', '603779', '603787', '603788', '603789', '603790', '603797', '603798', '603799', '603800', '603801', '603803', '603806', '603808', '603809', '603810', '603811', '603813', '603816', '603817', '603818', '603819', '603822', '603823', '603825', '603826', '603828', '603829', '603833', '603838', '603839', '603843', '603848', '603855', '603856', '603858', '603859', '603860', '603861', '603866', '603868', '603869', '603871', '603876', '603877', '603878', '603879', '603880', '603881', '603882', '603883', '603885', '603886', '603887', '603888', '603889', '603890', '603895', '603896', '603897', '603898', '603899', '603900', '603901', '603903', '603906', '603908', '603909', '603912', '603916', '603917', '603918', '603919', '603920', '603922', '603926', '603928', '603929', '603933', '603936', '603937', '603938', '603939', '603955', '603958', '603959', '603960', '603963', '603966', '603968', '603969', '603970', '603976', '603977', '603978', '603979', '603980', '603985', '603986', '603987', '603988', '603989', '603990', '603991', '603993', '603996', '603997', '603998', '603999']
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\quantaxis-script.py", line 11, in <module>
    load_entry_point('quantaxis', 'console_scripts', 'quantaxis')()
  File "c:\projects\quantaxis\QUANTAXIS\QACmd\__init__.py", line 367, in QA_cmd
    cli.cmdloop()
  File "C:\ProgramData\Anaconda3\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\ProgramData\Anaconda3\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "c:\projects\quantaxis\QUANTAXIS\QACmd\__init__.py", line 225, in do_save
    QA_SU_save_index_day('tdx')
  File "c:\projects\quantaxis\QUANTAXIS\QASU\main.py", line 154, in QA_SU_save_index_day
    engine.QA_SU_save_index_day(client=client)
  File "c:\projects\quantaxis\QUANTAXIS\QASU\save_tdx.py", line 444, in QA_SU_save_index_day
    __index_list = QA_fetch_get_stock_list('index')
  File "c:\projects\quantaxis\QUANTAXIS\QAFetch\QATdx.py", line 523, in QA_fetch_get_stock_list
    with api.connect(ip, port):
AttributeError: __enter__

**Comment by yutiansut** [comment]
1. 先确保 pytdx没有安装错误
2. 部分ip临时出现了不可用 去 C:\users\你的用户名\.quantaxis\setting\config.ini  在ip中随意修改, 重新运行quantaxis, 会自动重新测速 选择最优ip
3. 重新运行save index_day
