### ISSUE TITLE
master主分支上，截止到9月10号，可以跑webkit吗？

### ISSUE THREAD

**Issue by XavierXia** [yutiansut/QUANTAXIS#792]
你好，
通过阅读project readme，发现master分支上没有QUANTAXIS_Webkit文件夹呢，
之前通过 命令行得到了一个quantaxiswebkit文件夹，
跑出的web如下图：

![1111](https://user-images.githubusercontent.com/6349081/45276060-d72dfa00-b4f2-11e8-9c2a-36b692d88706.png)

这个截图和您放出的截图内容不同呢？

这个新版的网页还没有开发好吗？

**Comment by yutiansut** [comment]
哦是的 目前主要精力都在python部分  基本web的东西 python上都重新实现了一遍

**Comment by XavierXia** [comment]
谢谢，知道了，那您还会继续开发web吗？若我们有web展示的需要的话，那最好是在您发出的哪个web版本上进行 二次开发呢？

**Comment by yutiansut** [comment]
会的  过段时间会放上来
