### ISSUE TITLE
回测运行失败

### ISSUE THREAD

**Issue by shenxingbei** [yutiansut/QUANTAXIS#81]
def QA_fetch_stocklist_day(stock_list, collections, date_range):
    data = []
    for item in stock_list:
        data.append(QA_fetch_stock_day(
            item, date_range[0], date_range[-1], collections))
    return data

这里QA_fetch_stock_day调用时没有指定type_参数，导致new_test/stragety.py运行失败。

def QA_fetch_stock_day(code, startDate, endDate, type_='numpy', collections=QA_Setting.client.quantaxis.stock_day,):

**Comment by yutiansut** [comment]
哦对,我改了参数... 不是这个问题 是吧type和coll换了个位置...

**Comment by yutiansut** [comment]
@shenxingbei 已经修改  [](https://github.com/yutiansut/QUANTAXIS/commit/7b9a0c4dc1492ea5fe76d253d5cc2aac48ce7f15)

git pull 一下就好啦
