### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by azluck** [yutiansut/QUANTAXIS#819]
QATdx.QA_fetch_get_stock_realtime中有许多类似
code = [code] if type(code) is str else code
这种写法不够精简，建议写成：
code = [code] if isinstance(code, str) else code

**Comment by yutiansut** [comment]
@azluck get  一会pr来

**Comment by yutiansut** [comment]
@azluck https://github.com/QUANTAXIS/QUANTAXIS/pull/820

**Comment by yutiansut** [comment]
fixed
