### ISSUE TITLE
quantaxiswebkit文件夹

### ISSUE THREAD

**Issue by yisongbetter** [yutiansut/QUANTAXIS#844]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

20181011版本

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```


mac os x 10.14

```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```

现在的版本没有webkit文件夹，请问如何安装web端呢？
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
yisongbetter@gmail.com
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@yisongbetter 在https://github.com/QUANTAXIS/QADESKTOP  群文件有打包好的dmg包
