### ISSUE TITLE
mssql？新模块？

### ISSUE THREAD

**Issue by pchaos** [yutiansut/QUANTAXIS#888]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.2.1.dev2



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
fedora 28 X64




```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.6
- docker(无)
```
## 您需要反馈的问题
```
启动quantaxis
显示如下：
no module named mssql
QUANTAXIS> version


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```
mssql是新加的模块？


```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
没有啊 已经删掉了

**Comment by pchaos** [comment]
我是凌晨才git pull,出现这个提示

**Comment by pchaos** [comment]
更新到最新版，开机第一次import QUANTAXIS as QA 就会出现：no module named mssql
应该是哪里用到了

**Comment by zsluedem** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAUtil/QAEtl.py#L4

**Comment by yutiansut** [comment]
现在已经彻底删除 @pchaos  @zsluedem

**Comment by zsluedem** [comment]
万岁
