### ISSUE TITLE
mac os也会执行matplotlib.use('Agg') 能否在QAARP/QARisk.py 中添加platform.system()!='Darwin'

### ISSUE THREAD

**Issue by momantang** [yutiansut/QUANTAXIS#890]
mac os也会执行matplotlib.use('Agg') 能否在QAARP/QARisk.py 中添加platform.system()!

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
ok ~ 我补一下

**Comment by yutiansut** [comment]
已经增加  @momantang 

https://github.com/QUANTAXIS/QUANTAXIS/commit/73d82ba0a8e7f11c4b9ea86504589ecb5f5616eb
