### ISSUE TITLE
QUANTAXIS 官方推荐配置清单/过程

### ISSUE THREAD

**Issue by yutiansut** [yutiansut/QUANTAXIS#91]
# 安装前准备:

### windows
直接安装exe版本即可

### linux
```
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo add-apt-repository ppa:jonathonf/python-3.6

sudo apt-get update
sudo apt-get install python3.6
```
### windows
下载安装mongodb 3.2+

到mongod的目录下 👍  一般是 
> C:\Program Files\MongoDB\Server\3.4\bin

MongoDB需要一个data目录一个logo目录 
一般我们会在D:中新建一个data目录
```
cd D:
md data
```
然后在data目录下 新建一个data目录用于存放mongo的数据,log目录用于存放log
```
cd data
md data
md log
```
使用命令:
```
.\mongod.exe --dbpath  你的数据path  --logpath 你的日志path.log --httpinterface --rest --serviceName 'MongoDB' --install
```
示例:
> .\mongod.exe --dbpath  D:\data\data  --logpath D:\data\log\mongo.log --httpinterface --rest --serviceName 'MongoDB' --install
### windows
官网链接: https://nodejs.org/zh-cn/download/current/
直接下载exe 按要求安装即可 最新版本 8.2.1

### Linux
linux 可以直接
```
sudo apt-get install nodejs

sudo npm install n -g
n lastest
```
linux/mac下的nodejs有一个版本管理包 叫n 需要全局安装 -g

所以无论装了什么版本的nodejs  只需要npm install n -g  就行  

### windows 
百度搜索:git 下载--exe安装
### linux  
自带 无需安装

**Comment by yutiansut** [comment]
# 安装过程

## 下载镜像:

1.  pip install quantaxis
2.  git clone https://github.com/yutiansut/quantaxis

github上的会比pypi上多一些 mod工具


## 安装QUANTAXIS

```bash

cd quantaxis
pip install -r  requirements.txt -i https://pypi.doubanio.com/simple
pip install .   #这个是直接安装
pip install -e .  # 这个是开发版本安装
```

**Comment by yutiansut** [comment]
# 数据初始化

在命令行中输入quantaxis  进入QUANTAXIS的CLI

输入save
```
QUANTAXIS> save

```
即可保存股票的全市场数据

**Comment by yutiansut** [comment]
# 开始你的回测

新建一个目录,cd 到该目录下
```
cd E:
md quant_strategy
cd quant_strayegy
quantaxis

QUANTAXIS>  examples

```

**Comment by haohello** [comment]
以后更新数据也是用save的吗？

**Comment by yutiansut** [comment]
是的 @haohello
