### ISSUE TITLE
关于股票的EPS"每股收益"的储存方式能否扩展的提议和请教。

### ISSUE THREAD

**Issue by Wier123** [yutiansut/QUANTAXIS#919]
我是在QA上正在使用2个自动化策略的用户。第三个策略月底核对，年后应该投入期货市场。

# 问题反馈
在股票这一特殊市场上，有一个可以说是股票的根本的数据EPS"每股收益"季度的数据。其他很多一些指标都可以根据他在建的。。而tdx 同花顺 所有的记录方式都是一个字段。旧的覆盖新的。这从根本上限制了策略的比较扩展性。
在此。我想求大家投票。看大家是否和我一样都需要在每次save的时候能否对该项数据可保存多个。或者至少2年（即4x2个季度）的8个历史最近值。我知道即使现在加入该功能。也是要2年后才填满。但慢点总比少了条路好吧。

 不知我表达完整我的意思没。

## 您使用的QUANTAXIS版本号是什么?
QA.__version__>='1.0.45'
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
在股票这一特殊市场上，有一个可以说是股票的根本的数据EPS"每股收益"季度的数据。tdx 同花顺 所有的记录方式都是一个字段。旧的覆盖新的。这从根本上限制了策略的比较扩展性。
在此。我想求大家投票。看大家是否和我一样都需要在每次save的时候能否对该项数据可保存多个。或者至少2年（即4x2个季度）的8个历史最近值。

 不知我表达完整我的意思没。

 如果这个功能太小众。或者。。。yutian大佬。。请大概告诉我怎么自己改可以吗？求你啦请你吃饭喝早茶啦。。。我心里有个数比较好。你知道我要干嘛的。嘻嘻嘻。。

谢谢啦。

```
## 您的联系方式(QQ/EMAIL)
qq：87532775

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
EPS的每季度数据都有  @Wier123  参见https://github.com/QUANTAXIS/QUANTAXIS/blob/master/Documents/financial_means.md#1%E6%AF%8F%E8%82%A1%E6%8C%87%E6%A0%87


使用 
```
save financialfiles
```
即可下载1996年以来每一季度的财报


使用
```
QA_fetch_financial_report_adv
```
即可获取财报  具体参见 https://github.com/QUANTAXIS/QUANTAXIS/blob/master/CHANGELOG.md#1068

**Comment by Wier123** [comment]
哦哦这样的么？我的意思是我想用去年第一季度的每股收益eps值也有么？？

我以为和tdx同花顺那样那个财务页面。是最新覆盖的。只保留最新的。。。

如果是能有历史数据的话。。那就关闭这个issue吧。。不好意思。。。我去查查看。。谢谢大佬
