### ISSUE TITLE
No QUATAXIS_WEBSERVER Module there

### ISSUE THREAD

**Issue by hpzhen** [yutiansut/QUANTAXIS#938]
# 问题反馈

架构图里面提到的AUANTAXIS_WEBSERVER等模块的代码缺失。请问是还没有实现吗？或者在另外的地方下载？谢谢！

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS_WEBSERVER
