### ISSUE TITLE
实盘多brokers 多账户的方面有什么计划？比如broker的统一Interface设计

### ISSUE THREAD

**Issue by wangzhe3224** [yutiansut/QUANTAXIS#95]

**Comment by yutiansut** [comment]
封装统一的api接口吧

**Comment by yutiansut** [comment]
目前是tradex  股票的broker没那么多  不像期货这种模式

**Comment by wangzhe3224** [comment]
请问交易的这部分代码在哪里呢具体？

**Comment by yutiansut** [comment]
quantaxis_trade

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/tree/0.3.9-gamma/QUANTAXISTrade 看之前版本的吧  最近通达信整改  免费版本的模拟回测没法用 然后实盘还是可以用的

**Comment by yutiansut** [comment]
加qq群说吧
