### ISSUE TITLE
select_time_with_gap 的bug？

### ISSUE THREAD

**Issue by barretthugh** [yutiansut/QUANTAXIS#955]
![image](https://user-images.githubusercontent.com/16146097/51137797-6c167a80-187a-11e9-819b-97c8fd72ce47.png)

select_time_with_gap设置gap=5，用query查code==xx，得到5条数据，但datastruct实际上有包含了所有time参数日期之后的所有数据，这是bug吗？

ps, datastruct resample后返回的是df，用QA_DataStruct_Stock_day再包一次返回datastruct后会不会好点？不知道这样会不会影响回测

**Comment by barretthugh** [comment]
![image](https://user-images.githubusercontent.com/16146097/51142097-e698c780-1885-11e9-871e-c0750af107f3.png)

还有另一个问题，这里groupby, query后返回的是df，长度正确，但拿index的时候，长度又变回原来的未query的长度，用QA_DataStruct_Stock_day包一下后，拿到的index就正确了
不知道是不是pandas的问题

**Comment by yutiansut** [comment]
@barretthugh 第二个问题是要remove_unused_levels 在重新包的时候做过 你单独做是要自己去掉的

**Comment by yutiansut** [comment]
@barretthugh 
![qq 20190115125551](https://user-images.githubusercontent.com/11537812/51159596-f1bf1800-18c4-11e9-853d-2e83c38bc386.png)
第一个问题  我这里没有复现成功, 要不你把你代码给我看看?
