### ISSUE TITLE
Loaded Trade.dll Failed When Real Trading Using CAITONG Securities Stock Account

### ISSUE THREAD

**Issue by 5267** [yutiansut/QUANTAXIS#975]
when i tried real trading by CAITONG Securities Stock Account，failed N times in loading trade.dll，i  got alert information： load dll failed.

**Comment by 5267** [comment]
Finally，i found a easy and convenient solution to this question.  the main reason behind this is that OS lack some components to launch trade.dll program， one way to get rid of this problem is to install related components。the steps are as follows：
 
- 1、Download 360 security guard software
- 2、Then，go to software assistant
- 3、Enter 'visualcpp‘  in the search box
- 4、Find the right version to your operating system
![image](https://user-images.githubusercontent.com/19160836/51652968-72200000-1fcc-11e9-8aa3-a7464577d89e.png)
- 5、Just install it，then you can launch dll successfully.

**Comment by yutiansut** [comment]
good work~

**Comment by yutiansut** [comment]
https://github.com/rainx/TdxTradeServer

**Comment by royburns** [comment]
👍

**Comment by better319** [comment]
这是个假外国人吧

**Comment by yutiansut** [comment]
@5267 被发现了哈哈哈 @better319
