### ISSUE TITLE
backtest.py in EXAMPLE/test_backtest 回测结果和预期不符

### ISSUE THREAD

**Issue by Breath123** [yutiansut/QUANTAXIS#980]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
版本号： 最新的master branch


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
64位windows10, 8G内存




```

## 您的系统环境是什么?
```
- monodb
- python3.6
- 无docker
```
## 您需要反馈的问题
```
使用示例代码回测时，根据策略MAStrategy类中的代码：                
if sellavailable.get(item, 0) > 0:
                    event.send_order(account_cookie=self.account_cookie,
                                     amount=sellavailable[item], amount_model=AMOUNT_MODEL.BY_AMOUNT,
                                     time=self.current_time, code=item, price=0,
                                     order_model=ORDER_MODEL.MARKET, towards=ORDER_DIRECTION.SELL,
                                     market_type=self.market_type, frequence=self.frequence,
                                     broker_name=self.broker
                                     )
                else:
                    event.send_order(account_cookie=self.account_cookie,
                                     amount=100, amount_model=AMOUNT_MODEL.BY_AMOUNT,
                                     time=self.current_time, code=item, price=0,
                                     order_model=ORDER_MODEL.MARKET, towards=ORDER_DIRECTION.BUY,
                                     market_type=self.market_type, frequence=self.frequence,
                                     broker_name=self.broker)
回测结果预期应是没有持仓时，买入100股，有持仓时，全部卖出，也就是一天买入一天卖出，但示例执行结果为连续买入两天，连续卖出两天：
```
![result](https://user-images.githubusercontent.com/13479651/51811362-9e4ac200-22e7-11e9-8a76-0a5d744e3dd0.png)
```

从执行结果猜测，策略每日在0点进行执行，当空仓时，第一日0点判断，没有股票可卖出，执行买入100股，第二日0点判断，前一日买入的股票还不能卖出（第二日9.30后才可卖出），故继续执行买入100股，卖出基于同样的原因，也是连续卖出两日。
但实际情况为，若空仓，第一日0点判断，执行买入100股的操作，第二日0点再判断时，因第二日9.30后才可交际，前一日买入的股票在该日开市后便可正常交易，因此应该执行卖出100股的策略。
不知道我的理解是否正确，望解答，谢谢！

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@Breath123 我看一下

**Comment by Breath123** [comment]
@yutiansut 谢谢！

**Comment by yutiansut** [comment]
@Breath123 现在已经一致了

**Comment by Breath123** [comment]
@yutiansut 使用最新master测验，这个问题已经fix，谢谢！请问是**哪个commit** fix了这个问题？
另外在执行的过程中发现两个问题：
1. QUANTAXIS\QUANTAXIS\__init__.py 需注释第90行QA_fetch_get_shibor, 否则会提示找不到这个类；
2. QUANTAXIS\EXAMPLE\4_回测实盘交易\回测\股票回测\基于QAMARKET的回测\backtest.py 不能反复执行，需改变该文件第45行account_cookie的value，否则会提示如下错误：
![11](https://user-images.githubusercontent.com/13479651/52543831-c0fcd080-2de7-11e9-8cd5-d2e9816b8074.png)

**Comment by yutiansut** [comment]
@Breath123 新的版本限制了相同的account_cookie,因此不能重复执行  你可以改改代码


具体可能需要等到 1.3.0正式发布才可以看到,  因为下面 会强化组合的概念 (QA_PORTFOLIO) 因此 组合内的QA_Account不能重复,  所以你用相同的account_cookie是会返回None的

**Comment by yutiansut** [comment]
@Breath123 安装dev11 已经修正了这个问题  因为提交的时候发现 不是shibor而是chibor的爬虫 改了下

pip install quantaxis==1.3.0.dev11

**Comment by Breath123** [comment]
@yutiansut 谢谢！请问是哪个code commit解决了这个问题？可以列一下commit id 或者link吗？
想通过这个fix学习下代码。

另外这个问题已解决，我把issue close了。

**Comment by yutiansut** [comment]
@Breath123 哈 是因为多线程引擎的问题 改动较大 可以看下 QAMarket  和  QAApplication/QABacktest的代码  具体部署单个commit解决的  233

**Comment by yutiansut** [comment]
@Breath123 我把broker线程的任务改到主线程了 就不会出现状态不同步了  settle就正确了

**Comment by yutiansut** [comment]
@Breath123 另外 还有速度更快的 回测方式 参见 https://github.com/QUANTAXIS/QUANTAXIS/tree/master/EXAMPLE/4_%E5%9B%9E%E6%B5%8B%E5%AE%9E%E7%9B%98%E4%BA%A4%E6%98%93/%E5%9B%9E%E6%B5%8B/%E8%82%A1%E7%A5%A8%E5%9B%9E%E6%B5%8B

**Comment by Breath123** [comment]
@yutiansut 非常感谢!

**Comment by yutiansut** [comment]
@Breath123 你在qq群里面吗  群号 563280067
