### ISSUE TITLE
future_ip_list的优化问题

### ISSUE THREAD

**Issue by anno189** [yutiansut/QUANTAXIS#985]
扩展IP中的下列IP会导致QA_fetch_get_extensionmarket_list取出来的列表不完整。
建议删除
        'ip': '124.74.236.94',
        'ip': '218.80.248.229',
        'ip': '58.246.109.27',

文件QASetting.py，line:352~367

**Comment by yutiansut** [comment]
我看下 谢谢~

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/commit/a9d508ded76cc70d2b3b665997b48650d590ec8e

**Comment by yutiansut** [comment]
@AD189 已经注释 谢谢~

**Comment by anno189** [comment]
360 ~ 363, IP：124.74.236.94，这段没有注释。
352 ~ 355和360 ~ 363应该是重复的。
