### ISSUE TITLE
QA_fetch_index_min_adv 报错

### ISSUE THREAD

**Issue by zdxonline** [yutiansut/QUANTAXIS#999]
# 问题反馈
item['low']), float(item['close']), int(item['up_count']), int(item['down_count']), float(item['vol']), float(item['amount']), item['datetime'], item['time_stamp'], item['date'], item['type']])
**KeyError: 'up_count'**

**我看了下代码这个函数是从index_min这个表里取数据，一般的指数是有up_count这个字段的，但是指数基金没有。**

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@zdonline 收到 我修复一下

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/pull/998 fixed @zdxonline

**Comment by yutiansut** [comment]
@zdxonline pip install quantaxis==1.3.0.dev13
